export type Difficulty = "facil" | "moderado" | "dificil";

export interface BarbaraRoute {
  destino: string;
  endereco: string;
  carN: string;
  carH: string;
  tp: string;
  dist: string;
  diff: Difficulty;
  mapsUrl: string;
}

export interface BarbaraBase {
  id: string;
  emoji: string;
  cidade: string;
  periodo: string;
  hotel: string;
  hotelAddr: string;
  nota?: string;
  fuso?: string;
  referenciaLabel?: string;
  referenciaAddr?: string;
  routes: BarbaraRoute[];
  transitoInfo?: string[];
  insights: string[];
}

export const BARBARA_BASES: BarbaraBase[] = [

  // ── BASE 1 — Toronto, ON · 09–13 jun ──────────────────────────
  {
    id: "toronto",
    emoji: "🍁",
    cidade: "Toronto ON",
    periodo: "09–13 jun",
    hotel: "Holiday Inn Express Toronto Downtown by IHG",
    hotelAddr: "111 Lombard St, Toronto, ON M5C 2T9",
    nota: "Old Town / St. Lawrence Market — bairro seguro e central. Union Station a 12 min a pé.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: BMO Field",
    referenciaAddr: "170 Princes' Blvd, Toronto, ON M6K 3C3",
    routes: [
      {
        destino: "BMO Field",
        endereco: "170 Princes' Blvd, Toronto, ON M6K 3C3",
        carN: "12 min",
        carH: "18–25 min",
        tp: "Metrô Line 1 → ônibus 509/511 ~20 min / $3,30 CAD",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=170+Princes+Blvd,+Toronto,+ON",
      },
      {
        destino: "Union Station",
        endereco: "65 Front St W, Toronto, ON M5J 1E6",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 12 min / $0",
        dist: "0,9 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=65+Front+St+W,+Toronto,+ON",
      },
      {
        destino: "Toronto Pearson (YYZ)",
        endereco: "6301 Silver Dart Dr, Mississauga, ON L5P 1B2",
        carN: "30 min",
        carH: "45–65 min",
        tp: "UP Express de Union ~25 min / $12,35 CAD",
        dist: "28 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=6301+Silver+Dart+Dr,+Mississauga,+ON",
      },
      {
        destino: "Billy Bishop Airport (YTZ)",
        endereco: "2 Eireann Quay, Toronto, ON M5V 1A1",
        carN: "8 min",
        carH: "12 min",
        tp: "Ferry ou túnel gratuito ~15 min",
        dist: "3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=2+Eireann+Quay,+Toronto,+ON",
      },
      {
        destino: "TTC King Station (Line 1)",
        endereco: "King St W, Toronto, ON M5H 1A1",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 10 min / $0",
        dist: "0,7 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=King+Station,+Toronto,+ON",
      },
      {
        destino: "Distillery District",
        endereco: "55 Mill St, Toronto, ON M5A 3C4",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 10 min / $0",
        dist: "0,8 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=55+Mill+St,+Toronto,+ON",
      },
      {
        destino: "CN Tower / Harbourfront",
        endereco: "290 Bremner Blvd, Toronto, ON M5V 3L9",
        carN: "10 min",
        carH: "15 min",
        tp: "Metrô ~12 min / $3,30 CAD",
        dist: "2,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=290+Bremner+Blvd,+Toronto,+ON",
      },
      {
        destino: "Atlanta (próxima base)",
        endereco: "Atlanta, GA — voo YYZ → ATL",
        carN: "—",
        carH: "—",
        tp: "Voo YYZ → ATL ~2h",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=111+Lombard+St,+Toronto,+ON&daddr=6301+Silver+Dart+Dr,+Mississauga,+ON",
      },
    ],
    transitoInfo: [
      "Union Station a 12 min a pé — hub central: UP Express (YYZ), GO Transit, Via Rail, TTC.",
      "UP Express para YYZ: parte de Union Station — ~25 min direto / a cada 15 min / $12,35 CAD.",
      "Estação TTC mais próxima: King Station (Line 1 Yonge–University) — a 10 min a pé.",
      "Até BMO Field: Line 1 → Bathurst → ônibus 511 ou 509 Harbourfront.",
      "Tarifa TTC: $3,30 CAD por viagem. Cartão Presto recomendado.",
      "⚠️ Documentação: passagem Canadá → EUA exige passaporte válido + ESTA ($21 USD).",
    ],
    insights: [
      "BMO Field em dias de Copa: usar TTC. Não dirigir — estacionamento no Exhibition Place é caótico.",
      "UP Express para YYZ é mais rápido que Uber — evita trânsito da Hwy 427.",
      "Union Station a 12 min a pé: hub de UP Express (aeroporto), GO Transit e Via Rail.",
      "Documentação: ESTA exigida para brasileiros ao entrar nos EUA. Solicitar com antecedência.",
      "Moeda: Canadá usa CAD. ~1 USD = $1,37 CAD / ~1 BRL = $0,27 CAD. ATMs em Union Station.",
      "Fuso: Toronto é EDT (UTC -4h) — BRT = EDT +1h.",
    ],
  },

  // ── BASE 2 — Atlanta, GA · base recorrente ────────────────────
  // 13–15 jun (Hotel Indigo) · 20–21 jun (Courtyard Downtown)
  {
    id: "atlanta",
    emoji: "🍑",
    cidade: "Atlanta GA",
    periodo: "recorrente · 13–15 · 20–21 jun",
    hotel: "Hotel Indigo Atlanta Downtown (13–15) / Courtyard Downtown (20–21)",
    hotelAddr: "230 Peachtree Rd NE (Indigo) · 133 Carnegie Way NW (Courtyard)",
    nota: "Hotel Indigo: MARTA Peachtree Center a 2 min a pé. Courtyard: MARTA Five Points a 5 min. Courtyard fica a 1,5 km do Mercedes-Benz Stadium — possível a pé.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Mercedes-Benz Stadium",
    referenciaAddr: "1 AMB Dr NW, Atlanta, GA 30313",
    routes: [
      {
        destino: "Mercedes-Benz Stadium",
        endereco: "1 AMB Dr NW, Atlanta, GA 30313",
        carN: "8 min",
        carH: "12–20 min",
        tp: "MARTA Red/Gold → GWCC/CNN Center ~15 min / $2,50",
        dist: "3,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=1+AMB+Dr+NW,+Atlanta,+GA",
      },
      {
        destino: "Hartsfield-Jackson ATL",
        endereco: "6000 N Terminal Pkwy, Atlanta, GA 30320",
        carN: "20 min",
        carH: "30–50 min",
        tp: "MARTA Red/Gold direto ~20 min / $2,50",
        dist: "18 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=6000+N+Terminal+Pkwy,+Atlanta,+GA",
      },
      {
        destino: "MARTA Peachtree Center",
        endereco: "Peachtree Center Station, Atlanta, GA 30303",
        carN: "2 min",
        carH: "3 min",
        tp: "A pé 2 min / $0 (Hotel Indigo)",
        dist: "0,1 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=Peachtree+Center+Station,+Atlanta,+GA",
      },
      {
        destino: "MARTA Five Points (Courtyard)",
        endereco: "Five Points Station, Atlanta, GA 30303",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 5 min / $0 (Courtyard)",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=133+Carnegie+Way+NW,+Atlanta,+GA&daddr=Five+Points+Station,+Atlanta,+GA",
      },
      {
        destino: "Amtrak Peachtree Station",
        endereco: "1688 Peachtree Rd NW, Atlanta, GA 30309",
        carN: "10 min",
        carH: "15 min",
        tp: "MARTA ~12 min / Uber $10",
        dist: "3,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=1688+Peachtree+Rd+NW,+Atlanta,+GA",
      },
      {
        destino: "Kansas City (próxima base, 15 jun)",
        endereco: "Kansas City, MO — voo ATL → MCI",
        carN: "—",
        carH: "—",
        tp: "Voo ATL → MCI ~2h15 ⚠️ localizador Delta pendente",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=6000+N+Terminal+Pkwy,+Atlanta,+GA",
      },
      {
        destino: "Dallas (próxima base, 21 jun)",
        endereco: "Dallas, TX — voo ATL → DAL/DFW",
        carN: "—",
        carH: "—",
        tp: "Voo ATL → DAL/DFW ~2h30",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=133+Carnegie+Way+NW,+Atlanta,+GA&daddr=6000+N+Terminal+Pkwy,+Atlanta,+GA",
      },
    ],
    transitoInfo: [
      "Hotel Indigo: MARTA Peachtree Center a 2 min a pé. Courtyard: MARTA Five Points a 5 min.",
      "Até Mercedes-Benz: Red/Gold Line → GWCC/CNN Center Station — ~12 min / $2,50.",
      "Até ATL Airport: Red ou Gold Line direto → Airport Station — ~20 min / $2,50.",
      "Tarifa MARTA: $2,50 por viagem com Breeze Card. Máquinas em todas as estações.",
      "⚠️ VOO ATL → MCI (15 jun): localizador Delta pendente — confirmar com Julio Tonin.",
    ],
    insights: [
      "⚠️ VOO ATLANTA → KANSAS CITY (15 jun): localizador Delta pendente — confirmar horário com Julio Tonin antes do dia 15.",
      "Mercedes-Benz em dias de Copa: MARTA obrigatório. Ambos os hotéis têm estação próxima.",
      "Courtyard Downtown: 1,5 km do Mercedes-Benz — possível ir a pé em dias de jogo.",
      "Trânsito intenso Atlanta 7h–10h e 16h–20h. MARTA sempre mais rápido que carro.",
      "ATL Airport: 2h30 para internacionais / 2h para domésticos. MARTA direto de ambos os hotéis.",
      "Fuso: Atlanta é EDT (UTC -4h) — BRT = EDT +1h.",
    ],
  },

  // ── BASE 3 — Kansas City, MO · 15–17 jun ─────────────────────
  {
    id: "kansas-city",
    emoji: "🏈",
    cidade: "Kansas City MO",
    periodo: "15–17 jun",
    hotel: "Hotel Phillips Kansas City Curio Collection by Hilton",
    hotelAddr: "106 W 12th St, Kansas City, MO 64105",
    nota: "Hotel histórico de 1931 no Downtown Kansas City. RideKC Streetcar gratuito a 5 min a pé. ⚠️ Confirmar localizador do voo ATL → MCI antes do embarque.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h | EDT (Atlanta) = CDT +1h",
    referenciaLabel: "Estádio Copa: GEHA Field at Arrowhead Stadium",
    referenciaAddr: "1 Arrowhead Dr, Kansas City, MO 64129",
    routes: [
      {
        destino: "GEHA Field at Arrowhead Stadium",
        endereco: "1 Arrowhead Dr, Kansas City, MO 64129",
        carN: "18 min",
        carH: "25–40 min",
        tp: "Uber ~$25–40 / shuttle Copa (confirmar)",
        dist: "17 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Arrowhead+Dr,+Kansas+City,+MO",
      },
      {
        destino: "Kansas City Intl (MCI)",
        endereco: "1 Kansas City Blvd, Kansas City, MO 64153",
        carN: "25 min",
        carH: "35 min",
        tp: "Uber ~$35–55 / KCI Express ~$30",
        dist: "27 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Kansas+City+Blvd,+Kansas+City,+MO",
      },
      {
        destino: "Union Station (Amtrak)",
        endereco: "30 W Pershing Rd, Kansas City, MO 64108",
        carN: "10 min",
        carH: "15 min",
        tp: "A pé 15 min / Uber $8",
        dist: "1,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=30+W+Pershing+Rd,+Kansas+City,+MO",
      },
      {
        destino: "RideKC Streetcar",
        endereco: "12th & Main St Station, Kansas City, MO",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 5 min / $0 — gratuito",
        dist: "0,3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=12th+%26+Main+St,+Kansas+City,+MO",
      },
      {
        destino: "Power & Light District",
        endereco: "1323 Walnut St, Kansas City, MO 64106",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 8 min / $0",
        dist: "0,6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1323+Walnut+St,+Kansas+City,+MO",
      },
      {
        destino: "Boston (próxima base)",
        endereco: "Boston, MA — voo MCI → BOS",
        carN: "—",
        carH: "—",
        tp: "Voo MCI → BOS ~2h45",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Kansas+City+Blvd,+Kansas+City,+MO",
      },
    ],
    transitoInfo: [
      "RideKC Streetcar: gratuito — estação a 5 min a pé. Rota Union Station → Power & Light → River Market.",
      "Frequência Streetcar: a cada 10–15 min / Seg–Dom 5h–0h (Sex–Sáb até 1h).",
      "GEHA Field (Arrowhead): sem transporte público direto. Uber ~$25–40 de ida.",
      "Amtrak: Southwest Chief (KC → Chicago ~7h). Missouri River Runner (KC → St. Louis ~5h30).",
      "⚠️ Arrowhead em dias de jogo: pedir Uber com 30 min de antecedência — surge pricing é alto.",
    ],
    insights: [
      "⚠️ VOO ATL → MCI (15 jun): confirmar localizador Delta atualizado antes de embarcar.",
      "Arrowhead Stadium: sem transporte público direto. Uber obrigatório. Pedir 30 min antes.",
      "RideKC Streetcar gratuito — ideal para explorar Downtown Kansas City sem Uber.",
      "MCI Airport: eficiente e compacto, terminal único. Chegar 1h30–2h antes.",
      "Fuso: Kansas City é CDT (UTC -5h). BRT = CDT +2h | EDT (Atlanta/Boston) = CDT +1h.",
    ],
  },

  // ── BASE 4 — Boston, MA · 17–20 jun ──────────────────────────
  {
    id: "boston",
    emoji: "🦞",
    cidade: "Boston MA",
    periodo: "17–20 jun",
    hotel: "Aloft by Marriott Boston Seaport District",
    hotelAddr: "401-403 D St, Boston, MA 02210",
    nota: "Seaport District — Silver Line SL1 (gratuita do aeroporto) a 5 min a pé. BCEC a 5 min a pé.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h | CDT (Kansas City) = EDT -1h",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      {
        destino: "Gillette Stadium",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "40 min",
        carH: "55–80 min",
        tp: "Commuter Rail + shuttle Copa ~75 min / $15",
        dist: "55 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      {
        destino: "Boston Logan Airport (BOS)",
        endereco: "East Boston, MA 02128",
        carN: "10 min",
        carH: "15 min",
        tp: "Silver Line SL1 gratuita ~20 min",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=East+Boston,+MA+02128",
      },
      {
        destino: "South Station (Amtrak/Greyhound)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "8 min",
        carH: "10 min",
        tp: "Silver Line ~12 min / $2,40",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Back Bay Station (Amtrak)",
        endereco: "145 Dartmouth St, Boston, MA 02116",
        carN: "15 min",
        carH: "20 min",
        tp: "Silver Line + Orange Line ~20 min / $2,40",
        dist: "6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=145+Dartmouth+St,+Boston,+MA",
      },
      {
        destino: "Silver Line Way (SL1)",
        endereco: "Silver Line Way Station, Boston, MA 02210",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 5 min / $0",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=Silver+Line+Way+Station,+Boston,+MA",
      },
      {
        destino: "Boston Conv. Center (BCEC)",
        endereco: "415 Summer St, Boston, MA 02210",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 5 min / $0",
        dist: "0,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=415+Summer+St,+Boston,+MA",
      },
      {
        destino: "Atlanta (próxima base)",
        endereco: "Atlanta, GA — voo BOS → ATL",
        carN: "—",
        carH: "—",
        tp: "Voo BOS → ATL ~2h30",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=East+Boston,+MA+02128",
      },
    ],
    transitoInfo: [
      "Silver Line SL1: do aeroporto Logan ao Seaport — gratuita. A 5 min a pé do hotel.",
      "Gillette Stadium (55 km): South Station → Commuter Rail Providence/Stoughton → Canton Junction + shuttle.",
      "⚠️ Gillette em dias de Copa: sair 2h30 antes. Commuter Rail lota — comprar bilhete antecipado.",
      "South Station: hub de Amtrak (NYC ~3h30 / Philly ~5h) e ônibus regionais.",
      "Tarifa MBTA (T): $2,40 por viagem. CharlieCard recomendado.",
    ],
    insights: [
      "Silver Line SL1 gratuita do Logan — melhor opção chegando ao aeroporto diretamente no Seaport.",
      "Gillette 55 km ao sul — única opção viável é Commuter Rail + shuttle Copa.",
      "South Station a 8 min de carro — Amtrak para NYC/Philly e ônibus regionais.",
      "MCI (Kansas City) → BOS: chegar 2h antes para voos domésticos.",
      "Fuso: Boston é EDT (UTC -4h) — BRT = EDT +1h.",
    ],
  },

  // ── BASE 5 — Dallas, TX · base recorrente ─────────────────────
  // 21–22 jun · 27–29 jun (mesmo hotel)
  {
    id: "dallas",
    emoji: "🤠",
    cidade: "Dallas TX",
    periodo: "recorrente · 21–22 · 27–29 jun",
    hotel: "AC Hotel by Marriott Dallas Downtown",
    hotelAddr: "1712 Commerce St, Dallas, TX 75201",
    nota: "Downtown Dallas — DART Pearl/Arts District a 3 min a pé. Hub DART com linhas Red, Blue, Orange e Green.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h | EDT (Atlanta/Boston) = CDT +1h",
    referenciaLabel: "Estádio Copa: AT&T Stadium",
    referenciaAddr: "1 AT&T Way, Arlington, TX 76011",
    routes: [
      {
        destino: "AT&T Stadium (Arlington)",
        endereco: "1 AT&T Way, Arlington, TX 76011",
        carN: "25 min",
        carH: "35–55 min",
        tp: "DART + TRE → AT&T Station ~50 min / $2,50",
        dist: "28 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1712+Commerce+St,+Dallas,+TX&daddr=1+ATT+Way,+Arlington,+TX",
      },
      {
        destino: "Dallas Love Field (DAL)",
        endereco: "8008 Herb Kelleher Way, Dallas, TX 75235",
        carN: "15 min",
        carH: "20–30 min",
        tp: "DART Green Line → Inwood/Love Field ~20 min / $2,50",
        dist: "11 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1712+Commerce+St,+Dallas,+TX&daddr=8008+Herb+Kelleher+Way,+Dallas,+TX",
      },
      {
        destino: "Dallas Fort Worth (DFW)",
        endereco: "2400 Aviation Dr, DFW Airport, TX 76051",
        carN: "30 min",
        carH: "45–60 min",
        tp: "DART Orange Line → Terminal A ~45 min / $2,50",
        dist: "32 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1712+Commerce+St,+Dallas,+TX&daddr=2400+Aviation+Dr,+DFW+Airport,+TX",
      },
      {
        destino: "Amtrak Union Station Dallas",
        endereco: "400 S Houston St, Dallas, TX 75202",
        carN: "8 min",
        carH: "10 min",
        tp: "A pé 12 min / $0",
        dist: "0,9 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1712+Commerce+St,+Dallas,+TX&daddr=400+S+Houston+St,+Dallas,+TX",
      },
      {
        destino: "DART Pearl/Arts District",
        endereco: "Pearl Station, Dallas, TX 75201",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 3 min / $0",
        dist: "0,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1712+Commerce+St,+Dallas,+TX&daddr=Pearl+Arts+District+Station,+Dallas,+TX",
      },
      {
        destino: "Deep Ellum",
        endereco: "Deep Ellum, Dallas, TX 75226",
        carN: "8 min",
        carH: "12 min",
        tp: "DART ~10 min / A pé 15 min",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1712+Commerce+St,+Dallas,+TX&daddr=Deep+Ellum,+Dallas,+TX",
      },
      {
        destino: "Houston (1ª transferência, 22 jun)",
        endereco: "Houston, TX — voo DAL → HOU",
        carN: "3h30",
        carH: "4h30",
        tp: "Voo DAL → HOU Hobby ~1h / Carro I-45 Sul ~3h30",
        dist: "385 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1712+Commerce+St,+Dallas,+TX&daddr=710+Crawford+St,+Houston,+TX",
      },
    ],
    transitoInfo: [
      "DART Pearl/Arts District a 3 min a pé — hub com linhas Red, Blue, Orange e Green.",
      "Love Field (DAL): DART Green Line → Inwood/Love Field ~20 min / $2,50.",
      "DFW Airport: DART Orange Line → Airport Station ~45 min / $2,50.",
      "AT&T Stadium (Arlington): sem metrô direto. DART + TRE funciona, mas Uber (~$35–55) é mais prático.",
      "Tarifa DART: $2,50 por viagem / $5 diário. Horário: 5h–0h (Seg–Sex) / 6h–0h (Sáb–Dom).",
      "⚠️ Greyhound Dallas: terminal na Harry Hines Blvd — área de risco. Não recomendar chegada noturna.",
    ],
    insights: [
      "AT&T Stadium em Arlington: sem metrô direto. DART + TRE funciona mas Uber é mais prático ($35–55).",
      "DART Pearl/Arts District a 3 min: acesso rápido a Love Field e DFW Airport.",
      "Love Field (DAL): preferir para voos domésticos — mais próximo e simples que DFW.",
      "Dallas → Houston (22 jun): voo DAL → HOU Hobby ~1h. Carro pela I-45 Sul ~3h30 sem trânsito.",
      "Guadalajara → Dallas (27 jun): voo GDL → DFW ~2h30.",
      "Fuso: Dallas é CDT (UTC -5h) — BRT = CDT +2h | EDT (Atlanta/Boston) = CDT +1h.",
    ],
  },

  // ── BASE 6 — Houston, TX · 22–24 jun ─────────────────────────
  {
    id: "houston",
    emoji: "🛢️",
    cidade: "Houston TX",
    periodo: "22–24 jun",
    hotel: "Hampton Inn Houston Downtown",
    hotelAddr: "710 Crawford St, Houston, TX 77002",
    nota: "Downtown Houston — METRORail Red Line a 1 min a pé (Downtown Transit Center). Melhor conexão de metrô ao estádio de toda a Copa para esta equipe.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h | EDT = CDT +1h",
    referenciaLabel: "Estádio Copa: NRG Stadium",
    referenciaAddr: "1 NRG Pkwy, Houston, TX 77054",
    routes: [
      {
        destino: "NRG Stadium",
        endereco: "1 NRG Pkwy, Houston, TX 77054",
        carN: "10 min",
        carH: "15–25 min",
        tp: "METRORail Red Line ~15 min / $1,25",
        dist: "7 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=710+Crawford+St,+Houston,+TX&daddr=1+NRG+Pkwy,+Houston,+TX",
      },
      {
        destino: "Houston IAH (Bush Intercontinental)",
        endereco: "2800 N Terminal Rd, Houston, TX 77032",
        carN: "35 min",
        carH: "50–70 min",
        tp: "Metrô + ônibus ~1h20 / $3,50 / Uber ~$45–65",
        dist: "45 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=710+Crawford+St,+Houston,+TX&daddr=2800+N+Terminal+Rd,+Houston,+TX",
      },
      {
        destino: "Hobby Airport (HOU)",
        endereco: "7800 Airport Blvd, Houston, TX 77061",
        carN: "20 min",
        carH: "30 min",
        tp: "METRORail + ônibus ~40 min / $2,50",
        dist: "17 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=710+Crawford+St,+Houston,+TX&daddr=7800+Airport+Blvd,+Houston,+TX",
      },
      {
        destino: "Houston Amtrak (Union Station)",
        endereco: "902 Washington Ave, Houston, TX 77002",
        carN: "8 min",
        carH: "10 min",
        tp: "METRORail Red Line ~10 min / $1,25",
        dist: "4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=710+Crawford+St,+Houston,+TX&daddr=902+Washington+Ave,+Houston,+TX",
      },
      {
        destino: "METRORail Downtown Transit Center",
        endereco: "1100 Main St, Houston, TX 77002",
        carN: "1 min",
        carH: "2 min",
        tp: "A pé 1 min / $0",
        dist: "0,1 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=710+Crawford+St,+Houston,+TX&daddr=Downtown+Transit+Center,+Houston,+TX",
      },
      {
        destino: "Guadalajara (próxima base)",
        endereco: "Guadalajara, Jal. — voo IAH → GDL",
        carN: "—",
        carH: "—",
        tp: "Voo IAH → GDL ~2h30",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=710+Crawford+St,+Houston,+TX&daddr=2800+N+Terminal+Rd,+Houston,+TX",
      },
    ],
    transitoInfo: [
      "METRORail Red Line: Downtown Transit Center a 1 min a pé — acesso direto ao NRG Stadium.",
      "Até NRG Stadium: Red Line → Reliant Park Station — ~15 min / $1,25.",
      "Até IAH (Bush): sem metrô direto — Uber ~$45–65 / metrô + ônibus ~1h20.",
      "Tarifa METRORail: $1,25 por viagem. Cartão Q recomendado.",
      "Houston → Guadalajara: voo IAH → GDL (direto, Aeromexico) ~2h30. Preferir IAH para GDL.",
    ],
    insights: [
      "METRORail a 1 min do hotel: melhor acesso ao estádio de toda a Copa para esta equipe.",
      "NRG em dias de Copa: METRORail obrigatório. Ir 1h30 antes do jogo.",
      "IAH (Bush): Uber ~$45–65. Chegar 2h30 antes para internacional (GDL).",
      "HOU (Hobby): para voos domésticos. METRORail + ônibus ~40 min.",
      "Fuso: Houston é CDT (UTC -5h) — BRT = CDT +2h | EDT = CDT +1h.",
    ],
  },

  // ── BASE 7 — Guadalajara, Jalisco · 24–27 jun ─────────────────
  {
    id: "guadalajara",
    emoji: "🌮",
    cidade: "Guadalajara Jal.",
    periodo: "24–27 jun",
    hotel: "Becquer Hotel Guadalajara",
    hotelAddr: "Av. Guadalupe 596, Chapalita, 44500 Guadalajara, Jal., México",
    nota: "Hotel em Chapalita (zona oeste de Guadalajara) — mais perto do Estadio Akron que do Centro Histórico. ⚠️ Uber/Didi proibidos no desembarque do GDL Airport — usar táxi credenciado do counter.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h — mesmo fuso que Dallas e Houston, sem mudança",
    referenciaLabel: "Estádio Copa: Estadio Akron",
    referenciaAddr: "Cto. J.V.C. 2800, El Bajío, 45014 Zapopan, Jal.",
    routes: [
      {
        destino: "Estadio Akron (Zapopan)",
        endereco: "Cto. J.V.C. 2800, El Bajío, 45014 Zapopan, Jal.",
        carN: "20 min",
        carH: "30–50 min",
        tp: "Uber ~$150–250 MXN (sem metrô direto)",
        dist: "12 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Cto+JVC+2800,+El+Bajío,+Zapopan",
      },
      {
        destino: "GDL Airport (Miguel Hidalgo)",
        endereco: "Carr. Guadalajara-Chapala km 17.5, Jalisco",
        carN: "25 min",
        carH: "35–50 min",
        tp: "Táxi credenciado ~$350–500 MXN / Uber (fora do terminal) ~$150–200 MXN",
        dist: "22 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Carr+Guadalajara-Chapala+km+17.5",
      },
      {
        destino: "Centro Histórico",
        endereco: "Plaza Tapatía, Centro Histórico, Guadalajara, Jal.",
        carN: "15 min",
        carH: "20–35 min",
        tp: "Metrô Linha 1 ~20 min / $9 MXN",
        dist: "8 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Plaza+Tapatia,+Centro+Historico,+Guadalajara",
      },
      {
        destino: "Nueva Central de Autobuses",
        endereco: "Tlaquepaque, Guadalajara, Jal.",
        carN: "20 min",
        carH: "30–45 min",
        tp: "Uber ~$100–150 MXN",
        dist: "18 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Nueva+Central+de+Autobuses,+Guadalajara",
      },
      {
        destino: "Dallas (próxima base)",
        endereco: "Dallas, TX — voo GDL → DFW",
        carN: "—",
        carH: "—",
        tp: "Voo GDL → DFW ~2h30",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Carr+Guadalajara-Chapala+km+17.5",
      },
    ],
    transitoInfo: [
      "Uber e Didi: principais opções de transporte local. Táxi credenciado obrigatório no GDL Airport.",
      "⚠️ GDL Airport: Uber/Didi proibidos no desembarque. Usar táxi credenciado do counter oficial.",
      "Estadio Akron (Zapopan): sem metrô direto. Uber ~$150–250 MXN. Saída 2h antes em dias de Copa.",
      "Metrô de Guadalajara: útil para Centro Histórico e zonas centrais. Tarifa: $9 MXN.",
      "Ônibus para CDMX (Nova Central): ~5h / $300–500 MXN. Múltiplos horários.",
    ],
    insights: [
      "GDL Airport: Uber proibido no desembarque — usar táxi credenciado. ~$350–500 MXN.",
      "Estadio Akron: sem metrô direto — saída 2h antes em dias de Copa. Trânsito na Periférica é intenso.",
      "Hotel em Chapalita (zona oeste): mais perto de Zapopan/Akron que do Centro Histórico.",
      "Moeda: MXN (~$17–18 MXN = $1 USD / ~$3,30 MXN = $1 BRL). ATMs no hotel e no aeroporto.",
      "Fuso: Guadalajara é CDT (UTC -5h) — mesmo fuso que Dallas e Houston. Sem mudança nesta etapa.",
    ],
  },
];
