import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type AlemanhaPermit = "none" | "film_office" | "city_permit" | "venue_specific";

export const ALEMANHA_PERMIT_LABEL: Record<
  AlemanhaPermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",          tone: "green" },
  film_office:    { label: "Film Office local",   tone: "amber" },
  city_permit:    { label: "Prefeitura local",    tone: "amber" },
  venue_specific: { label: "Negociar com o local",tone: "orange" },
};

export interface AlemanhaVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade: "winston-salem" | "houston" | "toronto" | "hoboken";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: AlemanhaPermit;
  permitNote?: string;
  tips: string;
}

export const ALEMANHA_VENUES: AlemanhaVenueItem[] = [
  // ── Winston-Salem 09–12 jun ────────────────────────────────
  {
    id: "ws-corpening",
    name: "Corpening Plaza",
    category: "park",
    address: "100 N Liberty St, Winston-Salem, NC 27101",
    area: "Downtown",
    cidade: "winston-salem",
    cidadeLabel: "Winston-Salem",
    periodo: "09–12 jun",
    rating: 4.5,
    reviewCount: "900+",
    hours: "Aberto ao público",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Cidade de Winston-Salem",
    tips:
      "Praça pública no coração do downtown, a 5 min a pé do hotel. Palco central, bom para gravações ao ar livre durante o dia.",
  },
  {
    id: "ws-bailey",
    name: "Bailey Park",
    category: "park",
    address: "650 N Trade St, Winston-Salem, NC 27101",
    area: "Innovation Quarter",
    cidade: "winston-salem",
    cidadeLabel: "Winston-Salem",
    periodo: "09–12 jun",
    rating: 4.6,
    reviewCount: "600+",
    hours: "Diariamente 7h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Cidade de Winston-Salem",
    tips:
      "Parque moderno no Innovation Quarter com arquitetura industrial ao fundo. Frequentado por jovens locais — boa ambiência urbana para transmissões.",
  },
  {
    id: "ws-foothills",
    name: "Foothills Brewing",
    category: "sports_bar",
    address: "638 W 4th St, Winston-Salem, NC 27101",
    area: "Downtown",
    cidade: "winston-salem",
    cidadeLabel: "Winston-Salem",
    periodo: "09–12 jun",
    rating: 4.5,
    reviewCount: "3.500+",
    hours: "Seg–Qui 11h–22h · Sex–Sáb 11h–23h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Cervejaria e bar mais famosos de Winston-Salem. Transmite esportes, ambiente animado. Ótimo para conteúdo de bar/fã zone local.",
  },
  {
    id: "ws-oldsalem",
    name: "Old Salem Museums & Gardens",
    category: "park",
    address: "900 Old Salem Rd, Winston-Salem, NC 27101",
    area: "Old Salem",
    cidade: "winston-salem",
    cidadeLabel: "Winston-Salem",
    periodo: "09–12 jun",
    rating: 4.6,
    reviewCount: "2.800+",
    hours: "Ter–Sáb 9h30–16h30 · Dom 13h–16h30",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "Entrada ~$15/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Old Salem Inc.",
    tips:
      "Vilarejo histórico moraviano do séc. XVIII. Visual diferenciado para conteúdo cultural. A 5 min de carro do hotel.",
  },

  // ── Houston 12–15 jun ─────────────────────────────────────
  {
    id: "hou-hotel-zazabar",
    name: "Spire Bar — Hotel ZaZa",
    category: "rooftop",
    address: "5701 Main St, Houston, TX 77005",
    area: "Museum District",
    cidade: "houston",
    cidadeLabel: "Houston",
    periodo: "12–15 jun",
    rating: 4.4,
    reviewCount: "2.100+",
    hours: "Seg–Qui 17h–0h · Sex–Sáb 17h–2h · Dom 17h–23h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Hotel ZaZa",
    tips:
      "Rooftop bar com piscina no Museum District — a 5 min do hotel. Vista do skyline de Houston à noite. Ambiente sofisticado.",
  },
  {
    id: "hou-hermann",
    name: "Hermann Park",
    category: "park",
    address: "6001 Fannin St, Houston, TX 77030",
    area: "Museum District",
    cidade: "houston",
    cidadeLabel: "Houston",
    periodo: "12–15 jun",
    rating: 4.7,
    reviewCount: "22.000+",
    hours: "Diariamente 6h–23h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Houston Film Commission",
    tips:
      "Parque enorme a 5 min do hotel. Lago, jardim japonês, estátua de Sam Houston. Referência visual reconhecível de Houston.",
  },
  {
    id: "hou-discovery",
    name: "Discovery Green",
    category: "park",
    address: "1500 McKinney St, Houston, TX 77010",
    area: "Downtown",
    cidade: "houston",
    cidadeLabel: "Houston",
    periodo: "12–15 jun",
    rating: 4.7,
    reviewCount: "15.000+",
    hours: "Diariamente 6h–23h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "Houston Film Commission",
    tips:
      "Parque urbano no downtown com lago e palco. Fica lotado em dias de jogos no NRG. Ótima ambiência de cidade para transmissões.",
  },
  {
    id: "hou-chama",
    name: "Chama Gaúcha Brazilian Steakhouse",
    category: "brazilian",
    address: "5865 Westheimer Rd, Houston, TX 77057",
    area: "Galleria",
    cidade: "houston",
    cidadeLabel: "Houston",
    periodo: "12–15 jun",
    rating: 4.6,
    reviewCount: "8.200+",
    hours: "Seg–Sex 11h30–22h · Sáb 11h30–22h30 · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Referência de churrascaria gaúcha no Texas. Ambiente brasileiro autêntico — ótimo para conteúdo gastronômico. Uber ~20 min do hotel.",
  },
  {
    id: "hou-pitch25",
    name: "Pitch 25 Beer Park",
    category: "sports_bar",
    address: "2120 Walker St, Houston, TX 77003",
    area: "EaDo",
    cidade: "houston",
    cidadeLabel: "Houston",
    periodo: "12–15 jun",
    rating: 4.5,
    reviewCount: "4.800+",
    hours: "Ter–Sex 16h–2h · Sáb–Dom 12h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Sports bar dedicado ao futebol (soccer) em Houston. Outdoor + indoor, várias TVs. Energia alta em dias de Copa — a 10 min do NRG.",
  },
  {
    id: "hou-spacecenter",
    name: "Space Center Houston",
    category: "observatory",
    address: "1601 E NASA Pkwy, Webster, TX 77058",
    area: "Webster (Grande Houston)",
    cidade: "houston",
    cidadeLabel: "Houston",
    periodo: "12–15 jun",
    rating: 4.5,
    reviewCount: "37.000+",
    hours: "Seg–Sex 10h–17h · Sáb–Dom 10h–18h",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "~$35/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com NASA/Space Center",
    tips:
      "Centro oficial da NASA. Rockets, missão Artemis, conteúdo visual único. ~35 min do hotel. Exige agendamento com antecedência para filmagens comerciais.",
  },

  // ── Toronto 15–21 jun ─────────────────────────────────────
  {
    id: "tor-cntower",
    name: "CN Tower — LookOut Level",
    category: "observatory",
    address: "290 Bremner Blvd, Toronto, ON M5V 3L9",
    area: "Downtown",
    cidade: "toronto",
    cidadeLabel: "Toronto",
    periodo: "15–21 jun",
    rating: 4.6,
    reviewCount: "65.000+",
    hours: "Diariamente 9h–22h30",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "~$45 CAD/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com CN Tower",
    tips:
      "Ícone de Toronto. Vista 360° da cidade e do Lago Ontário. A 5 min do hotel a pé. Melhor combinação de dia + noite.",
  },
  {
    id: "tor-harbourfront",
    name: "Harbourfront Centre",
    category: "park",
    address: "235 Queens Quay W, Toronto, ON M5J 2G8",
    area: "Waterfront",
    cidade: "toronto",
    cidadeLabel: "Toronto",
    periodo: "15–21 jun",
    rating: 4.6,
    reviewCount: "8.500+",
    hours: "Diariamente (espaços externos 24h)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Toronto Film Office",
    tips:
      "Complexo cultural na orla do Lago Ontário — a 5 min do hotel. Palcos ao ar livre, marina, vistas da cidade. Muito animado no verão.",
  },
  {
    id: "tor-kost",
    name: "Kost — Bisha Hotel Rooftop",
    category: "rooftop",
    address: "80 Blue Jays Way, Toronto, ON M5V 2G3",
    area: "Entertainment District",
    cidade: "toronto",
    cidadeLabel: "Toronto",
    periodo: "15–21 jun",
    rating: 4.3,
    reviewCount: "3.800+",
    hours: "Ter–Dom 17h–23h (rooftop)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Bisha Hotel",
    tips:
      "Rooftop com piscina e vista do skyline de Toronto. A 10 min do hotel. Ambiente festivo — ideal para conteúdo noturno com cidade ao fundo.",
  },
  {
    id: "tor-realsports",
    name: "Real Sports Bar & Grill",
    category: "sports_bar",
    address: "15 York St, Toronto, ON M5J 2Z1",
    area: "Downtown",
    cidade: "toronto",
    cidadeLabel: "Toronto",
    periodo: "15–21 jun",
    rating: 4.3,
    reviewCount: "11.000+",
    hours: "Seg–Qui 11h30–0h · Sex–Sáb 11h30–2h · Dom 11h–0h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Um dos maiores sports bars do Canadá — a 3 min do hotel a pé. Centenas de TVs. Em dias de Copa fica lotado. Ótimo para conteúdo de fan experience.",
  },
  {
    id: "tor-copacabana",
    name: "Copacabana Brazilian Steakhouse",
    category: "brazilian",
    address: "230 Adelaide St W, Toronto, ON M5H 1W7",
    area: "Downtown",
    cidade: "toronto",
    cidadeLabel: "Toronto",
    periodo: "15–21 jun",
    rating: 4.5,
    reviewCount: "4.600+",
    hours: "Seg–Sex 11h30–22h · Sáb–Dom 16h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria brasileira mais conhecida de Toronto. Ambiente com decoração verde-amarela — perfeito para conteúdo com brasilidade. A 10 min do hotel.",
  },

  // ── Hoboken NJ 21–26 jun ──────────────────────────────────
  {
    id: "hob-waterfront",
    name: "Hoboken Waterfront",
    category: "park",
    address: "Sinatra Dr, Hoboken, NJ 07030",
    area: "Hoboken NJ",
    cidade: "hoboken",
    cidadeLabel: "Hoboken / NYC",
    periodo: "21–26 jun",
    rating: 4.9,
    reviewCount: "550+",
    hours: "Aberto ao público (orla)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Cidade de Hoboken — uso comercial",
    tips:
      "Vista do skyline inteiro de Manhattan a partir de NJ. Perfeito para pôr do sol. A 5 min do hotel. Um dos locais mais fotografados da região.",
  },
  {
    id: "hob-weehawken",
    name: "Weehawken Waterfront Park",
    category: "park",
    address: "1 Port Imperial Blvd, Weehawken, NJ 07086",
    area: "Weehawken NJ",
    cidade: "hoboken",
    cidadeLabel: "Hoboken / NYC",
    periodo: "21–26 jun",
    rating: 4.7,
    reviewCount: "1.400+",
    hours: "Seg–Dom 7h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Município de Weehawken",
    tips:
      "Vista privilegiada de Midtown Manhattan. Trilhas e área aberta. Ótima luz natural — dos melhores backdrops da região para conteúdo externo.",
  },
  {
    id: "hob-nohu",
    name: "NoHu Rooftop Bar",
    category: "rooftop",
    address: "550 Ave at Port Imperial, Weehawken, NJ 07086",
    area: "Weehawken NJ",
    cidade: "hoboken",
    cidadeLabel: "Hoboken / NYC",
    periodo: "21–26 jun",
    rating: 4.0,
    reviewCount: "1.900+",
    hours: "Seg–Qui 17h–23h · Sex–Sáb 17h–0h · Dom 17h–23h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "city_permit",
    permitNote: "Município de Weehawken",
    tips:
      "Uma das melhores vistas de Manhattan a partir de NJ. Na beira do Hudson River. 3 min da NJ Light Rail — fácil de Hoboken.",
  },
  {
    id: "hob-230fifth",
    name: "230 Fifth Rooftop Bar",
    category: "rooftop",
    address: "230 5th Ave, New York, NY 10001",
    area: "Manhattan (Midtown)",
    cidade: "hoboken",
    cidadeLabel: "Hoboken / NYC",
    periodo: "21–26 jun",
    rating: 4.3,
    reviewCount: "25.000+",
    hours: "Seg–Sex 12h–1h · Sáb 11h–4h · Dom 11h–1h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "film_office",
    permitNote: "NYC MOME",
    tips:
      "Vista direta do Empire State Building. PATH de Hoboken até 33rd St, 3 min a pé. Um dos rooftops mais filmados de NYC.",
  },
  {
    id: "hob-smithfield",
    name: "Smithfield Hall",
    category: "sports_bar",
    address: "138 W 25th St, Manhattan, NY 10001",
    area: "Manhattan",
    cidade: "hoboken",
    cidadeLabel: "Hoboken / NYC",
    periodo: "21–26 jun",
    rating: 4.4,
    reviewCount: "1.800+",
    hours: "Seg–Sex 12h–0h · Sáb 9h–0h · Dom 10h–0h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Eventos podem cobrar ingresso",
    permit: "none",
    tips:
      "Popular para futebol e Copa. PATH de Hoboken até 23rd St, 5 min a pé. Alta energia em dias de jogo.",
  },
];
