import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type BarbaraLocPermit = "none" | "film_office" | "venue_specific" | "gov_mx";

export const BARBARA_LOC_PERMIT_LABEL: Record<
  BarbaraLocPermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",            tone: "green"  },
  film_office:    { label: "Film Office local",     tone: "amber"  },
  venue_specific: { label: "Negociar com o local",  tone: "orange" },
  gov_mx:         { label: "Secretaria Cultura MX", tone: "amber"  },
};

export interface BarbaraVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade: "toronto" | "atlanta" | "kansas-city" | "boston" | "dallas" | "houston" | "guadalajara";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: BarbaraLocPermit;
  permitNote?: string;
  tips: string;
}

export const BARBARA_VENUES: BarbaraVenueItem[] = [

  // ── Toronto · 09–13 jun ───────────────────────────────────────
  {
    id: "tor-nathan-phillips",
    name: "Nathan Phillips Square",
    category: "park",
    address: "100 Queen St W, Toronto, ON M5H 2N1",
    area: "City Hall / Downtown",
    cidade: "toronto",
    cidadeLabel: "Toronto ON",
    periodo: "09–13 jun",
    rating: 4.6,
    reviewCount: "45.000+",
    hours: "24h (área externa)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "City of Toronto Film Office — toronto.ca/film",
    tips:
      "Praça icônica com o sinal TORONTO em letras grandes e a prefeitura ao fundo — backdrop reconhecível internacionalmente. A 10 min de metrô do hotel (King Station → Queen Station). Permit via Toronto Film Office — prazo recomendado de 3–5 dias úteis.",
  },
  {
    id: "tor-cn-tower",
    name: "CN Tower LookOut Level",
    category: "observatory",
    address: "290 Bremner Blvd, Toronto, ON M5V 3L9",
    area: "Entertainment District",
    cidade: "toronto",
    cidadeLabel: "Toronto ON",
    periodo: "09–13 jun",
    rating: 4.7,
    reviewCount: "155.000+",
    hours: "9h–22h30 (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    costNote: "Ingresso ~$43 CAD adulto",
    permit: "venue_specific",
    permitNote: "Contato comercial: cntower.ca",
    tips:
      "Vista de 360° de Toronto do 346m — skyline, lago Ontário e BMO Field visíveis. Glass Floor incluso no ingresso. Reservar com antecedência. Contato para produções: cntower.ca.",
  },
  {
    id: "tor-thompson-rooftop",
    name: "Thompson Toronto Rooftop Bar",
    category: "rooftop",
    address: "550 Wellington St W, Toronto, ON M5V 2V4",
    area: "King West",
    cidade: "toronto",
    cidadeLabel: "Toronto ON",
    periodo: "09–13 jun",
    rating: 4.3,
    reviewCount: "1.800+",
    hours: "12h–2h (Seg–Sáb) · 12h–0h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Thompson Hotel",
    tips:
      "Rooftop do Thompson Hotel com vista para o Lake Ontario e o Entertainment District. Atmosfera vibrante, ideal para gravações ao entardecer e noturnas. A 12 min a pé do hotel.",
  },
  {
    id: "tor-real-sports",
    name: "Real Sports Bar & Grill",
    category: "sports_bar",
    address: "15 York St, Toronto, ON M5J 2Z1",
    area: "Downtown / Scotiabank Arena",
    cidade: "toronto",
    cidadeLabel: "Toronto ON",
    periodo: "09–13 jun",
    rating: 4.2,
    reviewCount: "7.500+",
    hours: "11h–2h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Um dos maiores sports bars do Canadá — 199 telas, incluindo a maior tela interior do país. Próximo ao Scotiabank Arena e ao CN Tower. Energia máxima em dias de Copa. A 15 min a pé do hotel.",
  },
  {
    id: "tor-bairrada",
    name: "Bairrada Churrasqueira",
    category: "brazilian",
    address: "1000 College St W, Toronto, ON M6H 1A8",
    area: "Little Portugal",
    cidade: "toronto",
    cidadeLabel: "Toronto ON",
    periodo: "09–13 jun",
    rating: 4.5,
    reviewCount: "800+",
    hours: "12h–22h (Seg–Qui) · 12h–23h (Sex–Sáb) · 12h–21h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    permit: "none",
    tips:
      "Churrascaria portuguesa / brasileira no bairro Little Portugal de Toronto. Referência da comunidade lusófona da cidade. A ~20 min do hotel de metrô (King → Queen → bonde 501 westbound). Negociar janela de produção com a gerência.",
  },

  // ── Atlanta · 13–15 · 20–21 jun ───────────────────────────────
  {
    id: "atl-centennial-park",
    name: "Centennial Olympic Park",
    category: "park",
    address: "265 Park Ave W NW, Atlanta, GA 30313",
    area: "Downtown",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "13–15 · 20–21 jun",
    rating: 4.7,
    reviewCount: "45.000+",
    hours: "7h–23h (todos os dias)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Georgia World Congress Authority — gwcc.com",
    tips:
      "Parque histórico dos Jogos de 1996 com a fonte das 5 argolas. A 10 min de MARTA de ambos os hotéis. Permit via GWCC — processar com antecedência para uso comercial.",
  },
  {
    id: "atl-glenn-rooftop",
    name: "Glenn Hotel Sun Deck",
    category: "rooftop",
    address: "110 Marietta St NW, Atlanta, GA 30303",
    area: "Downtown",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "13–15 · 20–21 jun",
    rating: 4.5,
    reviewCount: "2.500+",
    hours: "17h–0h (Seg–Qui) · 17h–1h (Sex–Sáb) · 14h–22h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Glenn Hotel",
    tips:
      "Rooftop do hotel boutique Glenn com vista para o skyline e o Mercedes-Benz Stadium. A 10 min a pé de ambos os hotéis da equipe. Ideal para gravações ao entardecer e noturnas.",
  },
  {
    id: "atl-skyview",
    name: "SkyView Atlanta",
    category: "observatory",
    address: "168 Luckie St NW, Atlanta, GA 30303",
    area: "Downtown",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "13–15 · 20–21 jun",
    rating: 4.3,
    reviewCount: "6.000+",
    hours: "Seg–Qui 12h–22h · Sex 12h–23h · Sáb 10h–23h · Dom 10h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Ingresso ~$14–16 por pessoa",
    permit: "venue_specific",
    permitNote: "Contato: skyviewatlanta.com",
    tips:
      "Roda-gigante de 20 andares próxima ao Centennial Park. Gôndolas climatizadas. Contato comercial: skyviewatlanta.com.",
  },
  {
    id: "atl-fogo-de-chao",
    name: "Fogo de Chão Atlanta",
    category: "brazilian",
    address: "3101 Piedmont Rd NE, Atlanta, GA 30305",
    area: "Buckhead",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "13–15 · 20–21 jun",
    rating: 4.7,
    reviewCount: "7.500+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Em Buckhead — ~20 min dos hotéis de Uber ou MARTA. Ambiente elegante com boa iluminação. Negociar janela de produção com a gerência.",
  },
  {
    id: "atl-stats-brewpub",
    name: "Stats Brewpub",
    category: "sports_bar",
    address: "300 Marietta St NW, Atlanta, GA 30313",
    area: "Downtown / CNN Center",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "13–15 · 20–21 jun",
    rating: 4.2,
    reviewCount: "3.800+",
    hours: "11h–2h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Sports bar a 2 quarteirões do Centennial Park e do CNN Center. Mais de 100 TVs, cervejas artesanais e ótima energia em dias de Copa. A 12 min a pé de ambos os hotéis.",
  },

  // ── Kansas City · 15–17 jun ───────────────────────────────────
  {
    id: "kc-penn-valley",
    name: "Penn Valley Park",
    category: "park",
    address: "4800 Penn Valley Dr, Kansas City, MO 64108",
    area: "Downtown / Westside",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.5,
    reviewCount: "1.500+",
    hours: "Diariamente 6h–23h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Kansas City Film Office — filmkc.com",
    tips:
      "Parque urbano com vistas para o Memorial Liberty. A 20 min a pé ou 8 min de RideKC Streetcar. Permit via Kansas City Film Office (filmkc.com).",
  },
  {
    id: "kc-1hotel-rooftop",
    name: "1 Hotel Kansas City — Rooftop",
    category: "rooftop",
    address: "1 W Pershing Rd, Kansas City, MO 64108",
    area: "Downtown / Union Station",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.6,
    reviewCount: "1.200+",
    hours: "16h–23h (Seg–Qui) · 14h–1h (Sex–Sáb) · 14h–22h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do 1 Hotel KC",
    tips:
      "Rooftop com vista para o Union Station e o skyline de KC. A 15 min a pé do hotel. Ambiente sustentável e sofisticado.",
  },
  {
    id: "kc-wwi-memorial",
    name: "National WWI Museum & Memorial",
    category: "observatory",
    address: "2 Memorial Dr, Kansas City, MO 64108",
    area: "Downtown / Union Station",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.8,
    reviewCount: "15.000+",
    hours: "10h–17h (Ter–Dom — fechado seg)",
    goodDay: "yes",
    goodNight: "no",
    cost: "$",
    costNote: "Ingresso ~$16 por pessoa",
    permit: "venue_specific",
    permitNote: "Contato: theworldwar.org",
    tips:
      "Torre memorial com vista panorâmica de KC e do Union Station. Ícone arquitetônico. A 15 min a pé do hotel. Contato comercial via theworldwar.org.",
  },
  {
    id: "kc-fogo-de-chao",
    name: "Fogo de Chão Kansas City",
    category: "brazilian",
    address: "4951 Wyoming St, Kansas City, MO 64112",
    area: "Country Club Plaza",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.7,
    reviewCount: "3.800+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "No Country Club Plaza — a ~12 min de Uber do hotel. Ambiente elegante para gravações internas.",
  },

  // ── Boston · 17–20 jun ────────────────────────────────────────
  {
    id: "bos-harborwalk",
    name: "Boston Harborwalk — Seaport",
    category: "park",
    address: "Seaport Blvd, Boston, MA 02210",
    area: "Seaport District",
    cidade: "boston",
    cidadeLabel: "Boston MA",
    periodo: "17–20 jun",
    rating: 4.6,
    reviewCount: "12.000+",
    hours: "24h (área externa)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Mayor's Office of Arts & Culture — boston.gov/film",
    tips:
      "Orla do Seaport com vista para o porto de Boston e os edifícios do Financial District. A 5 min a pé do hotel. Permit via Boston Film Bureau — prazo recomendado de 5 dias úteis.",
  },
  {
    id: "bos-lookout-envoy",
    name: "The Lookout Rooftop Bar (Envoy Hotel)",
    category: "rooftop",
    address: "70 Sleeper St, Boston, MA 02210",
    area: "Seaport District",
    cidade: "boston",
    cidadeLabel: "Boston MA",
    periodo: "17–20 jun",
    rating: 4.5,
    reviewCount: "3.200+",
    hours: "15h–0h (Seg–Qui) · 12h–1h (Sex–Sáb) · 12h–22h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Envoy Hotel",
    tips:
      "Rooftop a 3 min a pé do hotel com vista para o porto de Boston e o skyline. Um dos melhores rooftops do Seaport. Negociar janela exclusiva com a gerência.",
  },
  {
    id: "bos-prudential-skywalk",
    name: "Prudential Center Skywalk Observatory",
    category: "observatory",
    address: "800 Boylston St, Boston, MA 02199",
    area: "Back Bay",
    cidade: "boston",
    cidadeLabel: "Boston MA",
    periodo: "17–20 jun",
    rating: 4.5,
    reviewCount: "8.000+",
    hours: "10h–22h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Ingresso ~$23 adulto",
    permit: "venue_specific",
    permitNote: "Contato: prudentialcenter.com",
    tips:
      "Vista de 360° de Boston do 52º andar — Fenway Park, MIT, Charles River e o oceano visíveis. A 20 min de Silver Line do hotel. Contato para produções: prudentialcenter.com.",
  },
  {
    id: "bos-fogo-de-chao",
    name: "Fogo de Chão Boston",
    category: "brazilian",
    address: "200 Dartmouth St, Boston, MA 02116",
    area: "Back Bay",
    cidade: "boston",
    cidadeLabel: "Boston MA",
    periodo: "17–20 jun",
    rating: 4.6,
    reviewCount: "5.500+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Em Back Bay — a 20 min de Silver Line do hotel. Ambiente elegante e boa iluminação para gravações internas. Negociar com a gerência.",
  },
  {
    id: "bos-the-fours",
    name: "The Fours",
    category: "sports_bar",
    address: "166 Canal St, Boston, MA 02114",
    area: "North Station",
    cidade: "boston",
    cidadeLabel: "Boston MA",
    periodo: "17–20 jun",
    rating: 4.3,
    reviewCount: "3.500+",
    hours: "11h–2h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "O mais tradicional sports bar de Boston, desde 1976. Paredes cobertas de memorabilia esportivo. Perto do TD Garden e da North Station. A 25 min do hotel de Silver Line + Orange Line.",
  },

  // ── Dallas · 21–22 · 27–29 jun ────────────────────────────────
  {
    id: "dal-klyde-warren",
    name: "Klyde Warren Park",
    category: "park",
    address: "2012 Woodall Rodgers Fwy, Dallas, TX 75201",
    area: "Arts District / Uptown",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "21–22 · 27–29 jun",
    rating: 4.8,
    reviewCount: "22.000+",
    hours: "6h–23h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "Dallas Film Commission — filmdallas.com",
    tips:
      "Parque linear sobre a rodovia que conecta Downtown ao Uptown. Palco para eventos gratuitos, food trucks e espaço gramado amplo. A 5 min a pé do hotel. Permit via Dallas Film Commission.",
  },
  {
    id: "dal-monarch",
    name: "Monarch Restaurant (Virgin Hotels Dallas)",
    category: "rooftop",
    address: "158 Routh St, Dallas, TX 75201",
    area: "Arts District",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "21–22 · 27–29 jun",
    rating: 4.5,
    reviewCount: "1.500+",
    hours: "17h–23h (Seg–Qui) · 17h–1h (Sex–Sáb) · 12h–22h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Virgin Hotels Dallas",
    tips:
      "Restaurante panorâmico nos andares superiores do Virgin Hotels com vista para o skyline de Dallas. A 8 min a pé do hotel. Ambiente sofisticado — ideal para gravações ao entardecer.",
  },
  {
    id: "dal-reunion-tower",
    name: "Reunion Tower GeO-Deck",
    category: "observatory",
    address: "300 Reunion Blvd E, Dallas, TX 75207",
    area: "Downtown",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "21–22 · 27–29 jun",
    rating: 4.5,
    reviewCount: "14.000+",
    hours: "Diariamente 10h–22h (Sex–Sáb até 23h)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    costNote: "Ingresso ~$26 adulto",
    permit: "venue_specific",
    permitNote: "Contato: reuniontower.com",
    tips:
      "Ícone do skyline de Dallas — esfera de 171m com deck giratório de 360°. AT&T Stadium visível em dias de boa visibilidade. A 15 min a pé do hotel. Contato comercial: reuniontower.com.",
  },
  {
    id: "dal-texas-de-brazil",
    name: "Texas de Brazil",
    category: "brazilian",
    address: "3031 Knox St, Dallas, TX 75205",
    area: "Knox-Henderson",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "21–22 · 27–29 jun",
    rating: 4.6,
    reviewCount: "6.000+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria brasileira premium fundada em Dallas — a marca nasceu nesta cidade. A 15 min de Uber do hotel. Ambiente sofisticado, boa iluminação para gravações. Negociar com a gerência.",
  },
  {
    id: "dal-rustic",
    name: "The Rustic",
    category: "sports_bar",
    address: "3656 Howell St, Dallas, TX 75204",
    area: "Uptown",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "21–22 · 27–29 jun",
    rating: 4.4,
    reviewCount: "8.500+",
    hours: "11h–2h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Enorme venue outdoor no Uptown Dallas com área coberta, múltiplos bares e palco ao vivo. Energia alta em dias de Copa — muito frequentado por torcedores. A 12 min de Uber do hotel.",
  },

  // ── Houston · 22–24 jun ───────────────────────────────────────
  {
    id: "hou-discovery-green",
    name: "Discovery Green",
    category: "park",
    address: "1500 McKinney St, Houston, TX 77010",
    area: "Downtown",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "22–24 jun",
    rating: 4.7,
    reviewCount: "25.000+",
    hours: "6h–23h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "Houston Film Commission — filmhouston.org",
    tips:
      "Parque urbano com lago, palco ao ar livre e múltiplas áreas para gravação. A 12 min a pé do hotel. Permit via Houston Film Commission (filmhouston.org) — processar com antecedência.",
  },
  {
    id: "hou-the-laura",
    name: "The Laura (Marriott Marquis Houston)",
    category: "rooftop",
    address: "1777 Walker St, Houston, TX 77010",
    area: "Downtown",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "22–24 jun",
    rating: 4.6,
    reviewCount: "2.000+",
    hours: "16h–0h (Seg–Qui) · 16h–2h (Sex–Sáb) · 14h–23h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Marriott Marquis",
    tips:
      "Pool deck e bar panorâmico do Marriott Marquis Houston com vista para o skyline de Downtown. A 15 min a pé do hotel. Negociar janela exclusiva com a gerência.",
  },
  {
    id: "hou-post-houston",
    name: "POST Houston Skylawn",
    category: "observatory",
    address: "401 Franklin St, Houston, TX 77002",
    area: "Downtown",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "22–24 jun",
    rating: 4.5,
    reviewCount: "3.500+",
    hours: "12h–22h (Ter–Dom — fechado seg)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "venue_specific",
    permitNote: "Contato: posthtx.com",
    tips:
      "Rooftop terrace na antiga central de correios de Houston com vista panorâmica de 360° do Downtown. Espaço cultural com horta, jardim e área de eventos. A 12 min a pé do hotel. Contato: posthtx.com.",
  },
  {
    id: "hou-texas-de-brazil",
    name: "Texas de Brazil Houston",
    category: "brazilian",
    address: "1821 Post Oak Blvd, Houston, TX 77056",
    area: "Galleria / Uptown",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "22–24 jun",
    rating: 4.6,
    reviewCount: "5.000+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Localizado na área da Galleria — a 20 min de METRORail + Uber do hotel. Ambiente elegante para gravações internas. Negociar com a gerência.",
  },
  {
    id: "hou-pitch25",
    name: "Pitch 25 Beer Garden & Sports Bar",
    category: "sports_bar",
    address: "2120 Walker St, Houston, TX 77003",
    area: "EaDo / Downtown East",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "22–24 jun",
    rating: 4.4,
    reviewCount: "4.200+",
    hours: "11h–2h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Beer garden voltado para futebol e Copa — telões externos, campo de futebol society e ambiente de torcida. A 15 min de METRORail do hotel. Ótimo para gravações ao vivo durante jogos.",
  },

  // ── Guadalajara · 24–27 jun ───────────────────────────────────
  {
    id: "gdl-colomos",
    name: "Bosque Los Colomos",
    category: "park",
    address: "Av. Naciones Unidas, Providencia, 44680 Guadalajara, Jal.",
    area: "Providencia / Chapalita",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara Jal.",
    periodo: "24–27 jun",
    rating: 4.7,
    reviewCount: "18.000+",
    hours: "6h–18h (Ter–Dom — fechado seg)",
    goodDay: "yes",
    goodNight: "no",
    cost: "free",
    permit: "gov_mx",
    permitNote: "SIOP Jalisco — secretaria de infraestrutura",
    tips:
      "Parque ecológico próximo ao hotel Becquer em Chapalita — a apenas 2 km. Trilhas, lagos e área de meditação. Ótimo para gravações externas em ambiente natural. Permit via SIOP Jalisco.",
  },
  {
    id: "gdl-casa-fayette",
    name: "Casa Fayette Rooftop Bar",
    category: "rooftop",
    address: "Av. México 2833, Vallarta Norte, 44690 Guadalajara, Jal.",
    area: "Vallarta Norte / Chapalita",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara Jal.",
    periodo: "24–27 jun",
    rating: 4.6,
    reviewCount: "900+",
    hours: "18h–1h (Seg–Qui) · 18h–2h (Sex–Sáb) · 14h–22h (Dom)",
    goodDay: "no",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Casa Fayette",
    tips:
      "Rooftop do hotel boutique Casa Fayette — ambiente sofisticado e íntimo, próximo ao hotel em Chapalita. Vista para o bairro residencial arborizado. Ideal para gravações noturnas. Negociar com antecedência.",
  },
  {
    id: "gdl-churrasco-gaucho",
    name: "Churrasco Gaucho",
    category: "brazilian",
    address: "Av. López Mateos Nte. 780, Ladron de Guevara, 44650 Guadalajara, Jal.",
    area: "López Mateos / Centro",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara Jal.",
    periodo: "24–27 jun",
    rating: 4.4,
    reviewCount: "1.200+",
    hours: "13h–23h (Seg–Sáb) · 13h–22h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha / brasileira em Guadalajara — uma das poucas referências brasileiras autênticas da cidade. A 15 min de Uber do hotel. Boa opção para conteúdo cultural.",
  },
  {
    id: "gdl-chapultepec-bar",
    name: "Avenida Chapultepec (bares e restaurantes)",
    category: "sports_bar",
    address: "Av. Chapultepec, Col. Americana, 44190 Guadalajara, Jal.",
    area: "Colonia Americana",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara Jal.",
    periodo: "24–27 jun",
    rating: 4.5,
    reviewCount: "—",
    hours: "Estabelecimentos individuais: 12h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Corredor gastronômico e bar da Colonia Americana — a mais vibrante de Guadalajara. Vários bares transmitem jogos da Copa. A 20 min de Uber do hotel. Verificar estabelecimento específico para negociar uso comercial.",
  },
];
