import type { CityConfig } from "./types-deslocamentos";

export const RIOPRETO_CONFIG: CityConfig = {
  id: "riopreto",
  emoji: "🐎",
  cidade: "São José do Rio Preto / Mirassol",
  periodo: "Brasileirão",
  origins: [
    {
      id: "hotel",
      name: "Hilton Garden Inn São José do Rio Preto",
      addr: "Av. Anísio Haddad, 8001, São José do Rio Preto - SP, 15090-365",
      lat: -20.7891,
      lng: -49.4029,
    },
  ],
  destinations: [
    {
      id: "estadio-mirassol",
      name: "Estádio José Maria de Campos Maia (Mirassol FC)",
      addr: "Av. Lauro Luchese, 2650, Centro, Mirassol - SP, 15130-000",
      lat: -20.818,
      lng: -49.5195,
      category: "estadio",
    },
    {
      id: "aeroporto-sjp",
      name: "Aeroporto Estadual de São José do Rio Preto (SJP)",
      addr: "Av. dos Estudantes, 3505, Vila Aeroporto, São José do Rio Preto - SP, 15035-010",
      lat: -20.8017,
      lng: -49.4032,
      category: "aeroporto",
    },
    {
      id: "represa-municipal",
      name: "Parque da Represa Municipal",
      addr: "Av. Lino José de Seixas, 1000, Jardim dos Seixas, São José do Rio Preto - SP, 15061-000",
      lat: -20.7847,
      lng: -49.3565,
      category: "ponto_turistico",
    },
    {
      id: "centro-catedral",
      name: "Centro / Catedral de São José",
      addr: "Av. Alberto Andaló, Centro, São José do Rio Preto - SP",
      lat: -20.8113,
      lng: -49.3758,
      category: "ponto_turistico",
    },
  ],
  routes: [
    {
      from: "hotel",
      to: "estadio-mirassol",
      carN: "20–25 min",
      carH: "35–50 min",
      tp: "Sem linha direta — ônibus intermunicipal ou app",
      dist: "17 km",
      diff: "dificil",
      costCar: "~R$26",
      costTp: "~R$12",
      note: "Rio Preto e Mirassol são cidades vizinhas mas distintas — é a rota mais longa e mais importante do roteiro",
    },
    {
      from: "hotel",
      to: "aeroporto-sjp",
      carN: "12–16 min",
      carH: "20–30 min",
      tp: "Sem linha direta — táxi/app",
      dist: "8 km",
      diff: "moderado",
      costCar: "~R$16",
      costTp: "Não disponível",
    },
    {
      from: "hotel",
      to: "represa-municipal",
      carN: "14–18 min",
      carH: "22–30 min",
      tp: "Ônibus municipal com baldeação",
      dist: "9 km",
      diff: "moderado",
      costCar: "~R$17",
      costTp: "~R$5",
    },
    {
      from: "hotel",
      to: "centro-catedral",
      carN: "13–17 min",
      carH: "20–28 min",
      tp: "Ônibus municipal direto",
      dist: "9 km",
      diff: "moderado",
      costCar: "~R$16",
      costTp: "~R$5",
    },
  ],
  alerts: [
    {
      category: "estadio",
      text: "O Estádio José Maria de Campos Maia fica em Mirassol, cidade vizinha a ~17 km/22 min de Rio Preto — não é no mesmo município do hotel. Planeje o trajeto com folga.",
    },
    {
      category: "aeroporto",
      text: "O Aeroporto Estadual Eribelto Manoel Reino (SJP) tem poucos voos comerciais regulares. Confirme a operação da rota antes de contar com ele.",
    },
    {
      category: "transito",
      text: "Rio Preto é uma cidade espalhada e depende de carro — poucas linhas de ônibus atendem bem o trajeto até Mirassol.",
    },
    {
      category: "geral",
      text: "Mirassol e Rio Preto têm prefeituras e numeração de endereço distintas mesmo estando conurbadas — sempre confirme 'Mirassol' explicitamente no Maps.",
    },
  ],
};
