export type Difficulty = "facil" | "moderado" | "dificil";

export interface DefanteRoute {
  destino: string;
  endereco: string;
  carN: string;
  carH: string;
  tp: string;
  dist: string;
  diff: Difficulty;
  mapsUrl: string;
}

export interface DefanteBase {
  id: string;
  emoji: string;
  cidade: string;
  periodo: string;
  hotel: string;
  hotelAddr: string;
  nota?: string;
  fuso?: string;
  referenciaLabel?: string;
  referenciaAddr?: string;
  routes: DefanteRoute[];
  transitoInfo?: string[];
  insights: string[];
}

export const DEFANTE_BASES: DefanteBase[] = [

  // ── BASE PRINCIPAL — Nova York, NY ───────────────────────────
  {
    id: "nova-york",
    emoji: "🗽",
    cidade: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    hotel: "Hampton Inn Manhattan/Times Square South",
    hotelAddr: "337 W 39th St, New York, NY 10018",
    nota: "Cobre 3 períodos. Holiday Inn Chelsea/NoMad (232 W 29th St) em uso em 12–14 jun — a 1,5 km, deslocamentos praticamente idênticos.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: MetLife Stadium",
    referenciaAddr: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
    routes: [
      {
        destino: "MetLife Stadium",
        endereco: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
        carN: "20 min",
        carH: "30–50 min",
        tp: "NJ Transit de Penn Station ~20 min / $8",
        dist: "18 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=1+MetLife+Stadium+Dr,+East+Rutherford,+NJ",
      },
      {
        destino: "JFK International",
        endereco: "Queens, NY 11430",
        carN: "40 min",
        carH: "60–90 min",
        tp: "Metrô E → AirTrain ~55 min / $9,50",
        dist: "28 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=JFK+International+Airport,+Queens,+NY",
      },
      {
        destino: "LaGuardia (LGA)",
        endereco: "Queens, NY 11371",
        carN: "30 min",
        carH: "50–70 min",
        tp: "Metrô + M60 ~45 min / $2,90",
        dist: "16 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=LaGuardia+Airport,+Queens,+NY",
      },
      {
        destino: "Newark EWR",
        endereco: "3 Brewster Rd, Newark, NJ 07114",
        carN: "30 min",
        carH: "40–60 min",
        tp: "NJT de Penn Station ~30 min / $14 + AirTrain $5,50",
        dist: "22 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=Newark+Liberty+International+Airport,+NJ",
      },
      {
        destino: "Penn Station",
        endereco: "4 Pennsylvania Plaza, New York, NY 10001",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 10 min / $0",
        dist: "0,7 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "Times Square",
        endereco: "Times Square, New York, NY 10036",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 8 min / $0",
        dist: "0,6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=Times+Square,+New+York,+NY",
      },
      {
        destino: "Port Authority Bus Terminal",
        endereco: "625 8th Ave, New York, NY 10018",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 10 min / $0",
        dist: "0,8 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=625+8th+Ave,+New+York,+NY",
      },
      {
        destino: "Central Park",
        endereco: "Central Park, New York, NY",
        carN: "15 min",
        carH: "20 min",
        tp: "Metrô A/C/E ~15 min / $2,90",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=Central+Park,+New+York,+NY",
      },
      {
        destino: "Hoboken Terminal",
        endereco: "1 Hudson Pl, Hoboken, NJ 07030",
        carN: "25 min",
        carH: "35 min",
        tp: "PATH de 33rd St ~15 min / $2,10",
        dist: "8 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=337+W+39th+St,+New+York,+NY&daddr=Hoboken+Terminal,+Hoboken,+NJ",
      },
    ],
    transitoInfo: [
      "Estações próximas ao Hampton Times Square: 34th St–Penn Station (A/C/E e 1/2/3).",
      "Estações próximas ao Holiday Inn Chelsea (12–14 jun): 28th St (1 e N/R/W).",
      "Tarifa metrô NYC: $2,90 por viagem / $34 semanal. OMNY (cartão ou celular) recomendado. Metrô 24h.",
      "NJ Transit para MetLife: Penn Station, plataforma inferior → Meadowlands / Secaucus. Bilhete em máquinas.",
      "PATH: liga 33rd St (Midtown) ao Hoboken Terminal e Jersey City. $2,10 / 15 min.",
      "⚠️ Dias de Copa: Perímetro FIFA fecha às 14h — sair de NYC antes das 12h30 para jogos às 16h.",
    ],
    insights: [
      "MetLife em dias de Copa: NJ Transit obrigatório. Não dirigir — sem estacionamento viável.",
      "EWR é preferido para voos domésticos curtos — mais fácil de acessar do Midtown que JFK.",
      "Penn Station é o hub central — Amtrak (Philly), NJ Transit (MetLife), PATH (Hoboken/JC).",
      "JFK via metrô: rota E → Howard Beach → AirTrain ~15 min → terminal. Simples mas demorado.",
      "Fuso: Nova York é EDT (UTC -4h) — BRT = EDT +1h.",
    ],
  },

  // ── BASE 2 — Cidade do México · 06–12 jun ────────────────────
  {
    id: "cdmx",
    emoji: "🌮",
    cidade: "Cidade do México",
    periodo: "06–12 jun",
    hotel: "Hotel Galeria Plaza Reforma",
    hotelAddr: "Hamburgo 195, Colonia Juárez, 06600 Cidade do México, CDMX",
    nota: "Altitude ~2.240m — primeiros dias podem causar leve cansaço. Uber e Didi funcionam bem. Evitar táxis de rua.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h | EDT (NYC) = CDT +1h",
    referenciaLabel: "Estádio Copa: Estadio Azteca",
    referenciaAddr: "Calz. de Tlalpan 3465, Coyoacán, CDMX",
    routes: [
      {
        destino: "Estadio Azteca",
        endereco: "Calz. de Tlalpan 3465, Coyoacán, CDMX",
        carN: "40 min",
        carH: "50–70 min",
        tp: "Metrô L2 → Tasqueña + Tren Ligero ~55 min / $10 MXN",
        dist: "22 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Calz+de+Tlalpan+3465,+Santa+Ursula+Coapa,+CDMX",
      },
      {
        destino: "Aeroporto AICM (MEX)",
        endereco: "Av. Capitán Carlos León, Peñón de los Baños, CDMX",
        carN: "25 min",
        carH: "35–50 min",
        tp: "Metrô L1 → Terminal Aérea ~30 min / $6 MXN",
        dist: "15 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Av+Capitan+Carlos+Leon,+Penon+de+los+Banos,+CDMX",
      },
      {
        destino: "Aeroporto AIFA (NLU)",
        endereco: "Circuito Exterior Mexiquense km 33, Santa Lucía",
        carN: "55 min",
        carH: "1h15",
        tp: "Ônibus AIFA Bus ~1h / $100 MXN",
        dist: "49 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Circuito+Exterior+Mexiquense+km+33,+Santa+Lucia",
      },
      {
        destino: "Metrô Insurgentes (L1)",
        endereco: "Av. Insurgentes Sur, Colonia Roma Norte, CDMX",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 3 min / $0",
        dist: "0,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Metro+Insurgentes,+CDMX",
      },
      {
        destino: "Zócalo / Centro Histórico",
        endereco: "Plaza de la Constitución, Centro Histórico, CDMX",
        carN: "20 min",
        carH: "30 min",
        tp: "Metrô L1 ~15 min / $6 MXN",
        dist: "7 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Zocalo,+Centro+Historico,+CDMX",
      },
      {
        destino: "Paseo de la Reforma",
        endereco: "Paseo de la Reforma, CDMX",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 5 min / $0",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Paseo+de+la+Reforma,+CDMX",
      },
      {
        destino: "Chapultepec / Museu de Arte",
        endereco: "Bosque de Chapultepec, Miguel Hidalgo, CDMX",
        carN: "10 min",
        carH: "15 min",
        tp: "A pé 20 min / Metrô L1 Chapultepec $6 MXN",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Bosque+de+Chapultepec,+CDMX",
      },
      {
        destino: "Nova York (próxima base)",
        endereco: "Nova York — voo MEX → JFK",
        carN: "—",
        carH: "—",
        tp: "Voo MEX → JFK ~5h / $200–600",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hamburgo+195,+Juarez,+CDMX&daddr=Aeropuerto+Internacional+Benito+Juarez,+CDMX",
      },
    ],
    transitoInfo: [
      "Estação mais próxima: Insurgentes (Linha 1 — Rosa) — a 3 min a pé do hotel.",
      "Até AICM (MEX): L1 → Pantitlán → L5 → Terminal Aérea — ~30 min / $6 MXN.",
      "Até Azteca: L1 → Pino Suárez → L2 → Tasqueña + Tren Ligero até Estadio Azteca.",
      "Tarifa metrô CDMX: $6 MXN (~$0,35 USD) por viagem. Cartão de recarga recomendado.",
      "Horário metrô: 5h–0h (Seg–Sex) / 6h–0h (Sáb) / 7h–0h (Dom).",
      "Uber e Didi: amplamente disponíveis e mais baratos que táxi. Evitar táxis de rua — risco de golpe.",
    ],
    insights: [
      "Estadio Azteca em dias de Copa: trânsito caótico no eixo Tlalpan–Periférico. Sair 2h30 antes.",
      "AICM (MEX): aeroporto grande e movimentado. Chegar 3h antes para voos internacionais.",
      "Uber e Didi funcionam muito bem em CDMX. Evitar táxis de rua — risco de golpe.",
      "Moeda: MXN (~$17–18 MXN = $1 USD / ~$3,30 MXN = $1 BRL). ATMs no hotel e no aeroporto.",
      "Altitude: CDMX a ~2.240m. Primeiros dias podem causar leve cansaço — hidratação essencial.",
      "Fuso: CDMX é CDT (UTC -5h). BRT = CDT +2h | NYC (EDT) = CDT +1h.",
    ],
  },

  // ── BASE 3 — Atlanta, GA · 14–16 jun ─────────────────────────
  {
    id: "atlanta",
    emoji: "🍑",
    cidade: "Atlanta GA",
    periodo: "14–16 jun",
    hotel: "Hotel Indigo Atlanta Downtown",
    hotelAddr: "230 Peachtree Rd NE, Atlanta, GA 30303",
    nota: "MARTA Peachtree Center a 2 min a pé — conexão direta com estádio e aeroporto.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Mercedes-Benz Stadium",
    referenciaAddr: "1 AMB Dr NW, Atlanta, GA 30313",
    routes: [
      {
        destino: "Mercedes-Benz Stadium",
        endereco: "1 AMB Dr NW, Atlanta, GA 30313",
        carN: "8 min",
        carH: "12–20 min",
        tp: "MARTA Red/Gold → GWCC/CNN Center ~15 min / $2,50",
        dist: "3,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=1+AMB+Dr+NW,+Atlanta,+GA",
      },
      {
        destino: "Hartsfield-Jackson ATL",
        endereco: "6000 N Terminal Pkwy, Atlanta, GA 30320",
        carN: "20 min",
        carH: "30–50 min",
        tp: "MARTA Red/Gold direto ~20 min / $2,50",
        dist: "18 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=6000+N+Terminal+Pkwy,+Atlanta,+GA",
      },
      {
        destino: "Amtrak — Peachtree Station",
        endereco: "1688 Peachtree Rd NW, Atlanta, GA 30309",
        carN: "10 min",
        carH: "15 min",
        tp: "MARTA ~10 min / $2,50",
        dist: "3,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=1688+Peachtree+Rd+NW,+Atlanta,+GA",
      },
      {
        destino: "MARTA Peachtree Center",
        endereco: "Peachtree Center Station, Atlanta, GA 30303",
        carN: "2 min",
        carH: "3 min",
        tp: "A pé 2 min / $0",
        dist: "0,1 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=Peachtree+Center+Station,+Atlanta,+GA",
      },
      {
        destino: "Georgia Aquarium / CNN Center",
        endereco: "225 Baker St NW, Atlanta, GA 30313",
        carN: "8 min",
        carH: "10 min",
        tp: "MARTA ~10 min / A pé 15 min",
        dist: "1,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=225+Baker+St+NW,+Atlanta,+GA",
      },
      {
        destino: "Kansas City (próxima base)",
        endereco: "Kansas City, MO — voo ATL → MCI",
        carN: "—",
        carH: "—",
        tp: "Voo ATL → MCI ~2h15 / $100–350",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=230+Peachtree+Rd+NE,+Atlanta,+GA&daddr=6000+N+Terminal+Pkwy,+Atlanta,+GA",
      },
    ],
    transitoInfo: [
      "MARTA Peachtree Center a 2 min a pé — melhor conexão hotel-metrô de toda a Copa para esta equipe.",
      "Até Mercedes-Benz Stadium: Red/Gold Line → GWCC/CNN Center Station — ~12 min / $2,50.",
      "Até ATL Airport: Red ou Gold Line direto → Airport Station — ~20 min / $2,50.",
      "Tarifa MARTA: $2,50 por viagem com Breeze Card. Máquinas em todas as estações.",
    ],
    insights: [
      "MARTA a 2 min do hotel — conexão direta com estádio (~15 min) e aeroporto (~20 min).",
      "Trânsito intenso em Atlanta: 7h–10h e 16h–20h no Downtown Connector. MARTA sempre mais rápido.",
      "Dias de Copa no Mercedes-Benz: MARTA obrigatório. Estacionamento inexistente. Ir 1h30 antes.",
      "Fuso: Atlanta é EDT (UTC -4h) — mesmo fuso que NYC. BRT = EDT +1h.",
    ],
  },

  // ── BASE 4 — Kansas City, MO · 15–17 jun ─────────────────────
  {
    id: "kansas-city",
    emoji: "🏈",
    cidade: "Kansas City MO",
    periodo: "15–17 jun",
    hotel: "Hotel Phillips Kansas City Curio Collection by Hilton",
    hotelAddr: "106 W 12th St, Kansas City, MO 64105",
    nota: "Hotel histórico de 1931 no Downtown Kansas City. RideKC Streetcar gratuito a 5 min a pé.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h | EDT (NYC/Philly) = CDT +1h",
    referenciaLabel: "Estádio Copa: GEHA Field at Arrowhead Stadium",
    referenciaAddr: "1 Arrowhead Dr, Kansas City, MO 64129",
    routes: [
      {
        destino: "GEHA Field at Arrowhead Stadium",
        endereco: "1 Arrowhead Dr, Kansas City, MO 64129",
        carN: "18 min",
        carH: "25–40 min",
        tp: "Uber ~$25–40 / shuttle Copa (confirmar)",
        dist: "17 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Arrowhead+Dr,+Kansas+City,+MO",
      },
      {
        destino: "Kansas City Intl (MCI)",
        endereco: "1 Kansas City Blvd, Kansas City, MO 64153",
        carN: "25 min",
        carH: "35 min",
        tp: "Uber ~$35–55 / KCI Express ~$30",
        dist: "27 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Kansas+City+Blvd,+Kansas+City,+MO",
      },
      {
        destino: "Union Station (Amtrak)",
        endereco: "30 W Pershing Rd, Kansas City, MO 64108",
        carN: "10 min",
        carH: "15 min",
        tp: "A pé 15 min / Uber $8",
        dist: "1,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=30+W+Pershing+Rd,+Kansas+City,+MO",
      },
      {
        destino: "RideKC Streetcar",
        endereco: "12th & Main St Station, Kansas City, MO",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 5 min / $0 — gratuito",
        dist: "0,3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=12th+%26+Main+St,+Kansas+City,+MO",
      },
      {
        destino: "Power & Light District",
        endereco: "1323 Walnut St, Kansas City, MO 64106",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 8 min / $0",
        dist: "0,6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1323+Walnut+St,+Kansas+City,+MO",
      },
      {
        destino: "Country Club Plaza",
        endereco: "4745 Central St, Kansas City, MO 64112",
        carN: "12 min",
        carH: "20 min",
        tp: "RideKC Streetcar estendido ~20 min / $0",
        dist: "6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=4745+Central+St,+Kansas+City,+MO",
      },
      {
        destino: "Philadelphia (próxima base)",
        endereco: "Philadelphia, PA — voo MCI → PHL",
        carN: "—",
        carH: "—",
        tp: "Voo MCI → PHL ~2h45 / $100–350",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Kansas+City+Blvd,+Kansas+City,+MO",
      },
    ],
    transitoInfo: [
      "RideKC Streetcar: gratuito — estação a 5 min a pé. Rota Union Station → Power & Light → River Market.",
      "Frequência Streetcar: a cada 10–15 min / Seg–Dom 5h–0h (Sex–Sáb até 1h).",
      "GEHA Field (Arrowhead): sem transporte público direto. Uber ~$25–40 de ida.",
      "Amtrak: Southwest Chief (KC → Chicago ~7h / → LA ~28h). Missouri River Runner (KC → St. Louis ~5h30).",
      "⚠️ Arrowhead em dias de jogo: pedir Uber com 30 min de antecedência — surge pricing é alto.",
    ],
    insights: [
      "Arrowhead Stadium: sem transporte público direto. Uber obrigatório. Pedir 30 min antes.",
      "RideKC Streetcar gratuito — ideal para explorar o Downtown Kansas City sem Uber.",
      "MCI Airport: eficiente e compacto, terminal único. Chegar 1h30–2h antes.",
      "Amtrak: baixa frequência e tempos longos para Costa Leste. Voo é sempre a melhor opção.",
      "Fuso: Kansas City é CDT (UTC -5h). BRT = CDT +2h | EDT (NYC/Philly) = CDT +1h.",
    ],
  },

  // ── BASE 5 — Philadelphia, PA · 17–19 e 22–23 jun ────────────
  {
    id: "philadelphia",
    emoji: "🏛",
    cidade: "Philadelphia PA",
    periodo: "17–19 · 22–23 jun",
    hotel: "Hilton Garden Inn Philadelphia Center City",
    hotelAddr: "1100 Arch St, Philadelphia, PA 19107",
    nota: "Dois períodos pontuais. Deslocamentos completos disponíveis na Equipe França.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Lincoln Financial Field",
    referenciaAddr: "One Lincoln Financial Field Way, Philadelphia, PA 19148",
    routes: [
      {
        destino: "Lincoln Financial Field",
        endereco: "1 Lincoln Financial Field Way, Philadelphia, PA 19148",
        carN: "15 min",
        carH: "20 min",
        tp: "SEPTA Broad St Line ~20 min / $2,50",
        dist: "8 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=1+Lincoln+Financial+Field+Way,+Philadelphia,+PA",
      },
      {
        destino: "Philadelphia Intl (PHL)",
        endereco: "8000 Essington Ave, Philadelphia, PA 19153",
        carN: "20 min",
        carH: "30 min",
        tp: "SEPTA Regional Rail ~25 min / $6,50",
        dist: "14 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=Philadelphia+International+Airport,+PA",
      },
      {
        destino: "30th Street Station (Amtrak)",
        endereco: "2955 Market St, Philadelphia, PA 19104",
        carN: "8 min",
        carH: "12 min",
        tp: "SEPTA Market-Frankford ~15 min / $2,50",
        dist: "3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=30th+Street+Station,+Philadelphia,+PA",
      },
      {
        destino: "Penn Station NYC",
        endereco: "4 Pennsylvania Plaza, New York, NY 10001",
        carN: "—",
        carH: "—",
        tp: "Amtrak Acela ~1h10 / $60–150 | NE Regional ~1h30 / $30–80",
        dist: "145 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "Miami (próxima base)",
        endereco: "Miami, FL — voo PHL → MIA",
        carN: "—",
        carH: "—",
        tp: "Voo PHL → MIA ~2h45 / $100–350",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=Philadelphia+International+Airport,+PA",
      },
    ],
    transitoInfo: [
      "SEPTA Broad St Line: Downtown ↔ Lincoln Financial Field em ~20 min / $2,50.",
      "SEPTA Regional Rail: Center City ↔ PHL Airport em ~25 min / $6,50.",
      "SEPTA Market-Frankford Line: Center City ↔ 30th Street Station em ~15 min / $2,50.",
      "Amtrak Acela: Philly 30th St → NYC Penn em ~1h10 / $60–150. NE Regional ~1h30 / $30–80.",
    ],
    insights: [
      "Lincoln Financial Field a ~20 min de SEPTA — transporte público simples e direto.",
      "Retorno a NYC (19 e 22 jun): Amtrak Acela ~1h10 ou NE Regional ~1h30.",
      "Miami (23 jun): voo PHL → MIA direto ~2h45. Chegar 2h antes ao PHL Airport.",
      "PHL Airport: SEPTA Regional Rail direto do Center City em ~25 min.",
      "Fuso: Philadelphia é EDT (UTC -4h) — mesmo fuso que NYC. BRT = EDT +1h.",
    ],
  },

  // ── BASE 6 — Miami, FL · 23–28 jun ───────────────────────────
  {
    id: "miami",
    emoji: "🌴",
    cidade: "Miami FL",
    periodo: "23–28 jun",
    hotel: "Hampton Inn & Suites Miami Wynwood Design District",
    hotelAddr: "3450 Biscayne Blvd, Miami, FL 33137",
    nota: "Mesmo hotel da Equipe Brasil Belt Moedas. Deslocamentos completos disponíveis no portal daquela equipe.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Hard Rock Stadium",
    referenciaAddr: "347 Don Shula Dr, Miami Gardens, FL 33056",
    routes: [
      {
        destino: "Hard Rock Stadium",
        endereco: "347 Don Shula Dr, Miami Gardens, FL 33056",
        carN: "30 min",
        carH: "45 min",
        tp: "Metrorail + shuttle ~45 min / $2,25",
        dist: "22 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=3450+Biscayne+Blvd,+Miami,+FL&daddr=347+Don+Shula+Dr,+Miami+Gardens,+FL",
      },
      {
        destino: "Miami Intl Airport (MIA)",
        endereco: "2100 NW 42nd Ave, Miami, FL 33142",
        carN: "20 min",
        carH: "30 min",
        tp: "Metrorail Orange Line ~25 min / $2,25",
        dist: "11 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=3450+Biscayne+Blvd,+Miami,+FL&daddr=2100+NW+42nd+Ave,+Miami,+FL",
      },
      {
        destino: "Fort Lauderdale Airport (FLL)",
        endereco: "100 Terminal Dr, Fort Lauderdale, FL 33315",
        carN: "40 min",
        carH: "55 min",
        tp: "Tri-Rail ~55 min / $5,25",
        dist: "40 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=3450+Biscayne+Blvd,+Miami,+FL&daddr=100+Terminal+Dr,+Fort+Lauderdale,+FL",
      },
      {
        destino: "Brightline Miami Central",
        endereco: "600 NW 1st Ave, Miami, FL 33136",
        carN: "12 min",
        carH: "18 min",
        tp: "Metrorail ~15 min / $2,25",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=3450+Biscayne+Blvd,+Miami,+FL&daddr=600+NW+1st+Ave,+Miami,+FL",
      },
      {
        destino: "Wynwood Walls",
        endereco: "2520 NW 2nd Ave, Miami, FL 33127",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 8 min / $0",
        dist: "0,6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=3450+Biscayne+Blvd,+Miami,+FL&daddr=2520+NW+2nd+Ave,+Miami,+FL",
      },
      {
        destino: "South Beach",
        endereco: "South Beach, Miami Beach, FL 33139",
        carN: "20 min",
        carH: "30 min",
        tp: "Metrobus ~30 min / $2,25",
        dist: "10 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=3450+Biscayne+Blvd,+Miami,+FL&daddr=South+Beach,+Miami+Beach,+FL",
      },
      {
        destino: "Brickell / Downtown",
        endereco: "Brickell, Miami, FL 33131",
        carN: "12 min",
        carH: "18 min",
        tp: "Metrorail ~15 min / $2,25",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=3450+Biscayne+Blvd,+Miami,+FL&daddr=Brickell,+Miami,+FL",
      },
    ],
    transitoInfo: [
      "Metrorail Orange Line: liga MIA Airport ao Downtown em ~25 min / $2,25.",
      "Brightline: trem de alta velocidade Miami → Fort Lauderdale (~30 min / $10–20).",
      "Tri-Rail: Miami → Fort Lauderdale → West Palm Beach. Conecta com Metrorail no Government Center.",
      "Uber/Lyft amplamente disponíveis — principal modal para Hard Rock Stadium em dias de Copa.",
      "Hard Rock Stadium: sem transporte público direto adequado. Uber obrigatório. Pedir 30 min antes.",
      "Wynwood Walls a 8 min a pé do hotel — bairro seguro e caminhável.",
    ],
    insights: [
      "Hard Rock Stadium: Uber obrigatório em dias de Copa. Pedir com 30 min de antecedência.",
      "MIA Airport: chegar 2h30 antes para voos domésticos / 3h para internacionais.",
      "FLL: alternativa mais tranquila e geralmente mais barata que MIA para voos domésticos.",
      "Wynwood é bairro seguro e ativo à noite — hotel bem localizado para a estadia.",
      "Fuso: Miami é EDT (UTC -4h) — mesmo fuso que NYC/Atlanta/Philly. BRT = EDT +1h.",
    ],
  },
];
