import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type BeltChicoPermit = "none" | "film_office" | "city_permit" | "venue_specific";

export const BELT_CHICO_PERMIT_LABEL: Record<
  BeltChicoPermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",           tone: "green" },
  film_office:    { label: "Film Office local",    tone: "amber" },
  city_permit:    { label: "Prefeitura local",     tone: "amber" },
  venue_specific: { label: "Negociar com o local", tone: "orange" },
};

export interface BeltChicoVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade: "morristown" | "cleveland" | "philadelphia" | "miami";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: BeltChicoPermit;
  permitNote?: string;
  tips: string;
}

export const BELT_CHICO_VENUES: BeltChicoVenueItem[] = [

  // ── Morristown, NJ · 01–05 · 07–23 · 25–28 jun ───────────────
  {
    id: "mor-green",
    name: "Morristown Green",
    category: "park",
    address: "Morristown Green, Morristown, NJ 07960",
    area: "Downtown",
    cidade: "morristown",
    cidadeLabel: "Morristown NJ",
    periodo: "01–05 · 07–23 · 25–28 jun",
    rating: 4.5,
    reviewCount: "2.500+",
    hours: "Diariamente 24h (área externa)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Morris County Office of Tourism and Film",
    tips:
      "Praça histórica de 1715 no coração do Downtown de Morristown — edifícios coloniais e o Tribunal do Condado ao fundo. A 2 min do hotel a pé. Backdrop autêntico do interior histórico americano, ideal para gravações externas durante o dia.",
  },
  {
    id: "mor-lewis",
    name: "Lewis Morris County Park",
    category: "park",
    address: "270 Mendham Rd, Morris Township, NJ 07960",
    area: "Morris Township",
    cidade: "morristown",
    cidadeLabel: "Morristown NJ",
    periodo: "01–05 · 07–23 · 25–28 jun",
    rating: 4.7,
    reviewCount: "4.000+",
    hours: "Diariamente 7h–anoitecer",
    goodDay: "yes",
    goodNight: "no",
    cost: "free",
    permit: "city_permit",
    permitNote: "Morris County Park Commission (morrisparks.net)",
    tips:
      "Maior parque do condado de Morris — trilhas, lago, floresta e natureza aberta. A 10 min do hotel de Uber (~$15). Excelente luz natural para gravações externas em ambiente de natureza americana.",
  },
  {
    id: "mor-jockey",
    name: "Jockey Hollow Bar & Kitchen",
    category: "rooftop",
    address: "110 South St, Morristown, NJ 07960",
    area: "Downtown",
    cidade: "morristown",
    cidadeLabel: "Morristown NJ",
    periodo: "01–05 · 07–23 · 25–28 jun",
    rating: 4.4,
    reviewCount: "1.800+",
    hours: "Ter–Dom 17h–22h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Jockey Hollow Bar & Kitchen",
    tips:
      "Restaurante sofisticado em mansão histórica com jardim e terraço externo em pleno Downtown de Morristown. A 5 min do hotel a pé. Uma das referências gastronômicas da região — ambiente elegante ideal para conteúdo diferenciado.",
  },
  {
    id: "mor-kilkenny",
    name: "Kilkenny Alehouse",
    category: "sports_bar",
    address: "16 Schuyler Pl, Morristown, NJ 07960",
    area: "Downtown",
    cidade: "morristown",
    cidadeLabel: "Morristown NJ",
    periodo: "01–05 · 07–23 · 25–28 jun",
    rating: 4.2,
    reviewCount: "1.200+",
    hours: "Seg–Qui 11h30–1h · Sex–Sáb 11h30–2h · Dom 11h–1h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Sports bar de referência no Downtown de Morristown — múltiplas TVs e cerveja artesanal local. A 5 min do hotel a pé. Alta energia em dias de Copa com torcida local diversa.",
  },

  // ── Cleveland, OH · 05–07 jun ─────────────────────────────────
  {
    id: "cle-edgewater",
    name: "Edgewater Park",
    category: "park",
    address: "6700 Memorial Shoreway, Cleveland, OH 44102",
    area: "Lakefront / West Side",
    cidade: "cleveland",
    cidadeLabel: "Cleveland",
    periodo: "05–07 jun",
    rating: 4.7,
    reviewCount: "8.000+",
    hours: "Diariamente 6h–23h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "Greater Cleveland Film Commission (clevelandfilm.com)",
    tips:
      "Parque à beira do Lago Erie com praia, skyline de Cleveland ao fundo e pores do sol únicos. A 15 min do hotel de Uber (~$15). Um dos melhores backdrops naturais de Cleveland para gravações externas.",
  },
  {
    id: "cle-platform",
    name: "Platform Beer Co. — Rooftop Terrace",
    category: "rooftop",
    address: "4125 Lorain Ave, Cleveland, OH 44113",
    area: "Ohio City",
    cidade: "cleveland",
    cidadeLabel: "Cleveland",
    periodo: "05–07 jun",
    rating: 4.3,
    reviewCount: "2.500+",
    hours: "Seg–Qui 15h–23h · Sex–Sáb 12h–0h · Dom 12h–22h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$",
    permit: "venue_specific",
    permitNote: "Direto com Platform Beer Co.",
    tips:
      "Cervejaria artesanal com terraço rooftop em Ohio City — vista do skyline de Cleveland. A 12 min do hotel de Uber (~$12). Ambiente descontraído e autêntico, referência da cena craft beer de Cleveland.",
  },
  {
    id: "cle-science",
    name: "Great Lakes Science Center",
    category: "observatory",
    address: "601 Erieside Ave, Cleveland, OH 44114",
    area: "North Coast / Lakefront",
    cidade: "cleveland",
    cidadeLabel: "Cleveland",
    periodo: "05–07 jun",
    rating: 4.5,
    reviewCount: "5.000+",
    hours: "Seg–Sáb 10h–17h · Dom 12h–17h",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "~$20/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Great Lakes Science Center",
    tips:
      "Museu de ciências à beira do Lago Erie com o único NASA Glenn Visitor Center do mundo. A 10 min do hotel de Uber (~$10). Terraço externo com vista da orla e do Rock and Roll Hall of Fame ao lado.",
  },
  {
    id: "cle-barley",
    name: "Barley House Cleveland",
    category: "sports_bar",
    address: "1261 W 6th St, Cleveland, OH 44113",
    area: "Warehouse District",
    cidade: "cleveland",
    cidadeLabel: "Cleveland",
    periodo: "05–07 jun",
    rating: 4.3,
    reviewCount: "3.500+",
    hours: "Seg–Sex 11h–2h · Sáb–Dom 10h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Lendário sports bar no Warehouse District — múltiplas TVs, espaço amplo e altíssima energia em dias de Copa. A 12 min do hotel a pé ou 8 min de Uber. Ponto de referência dos fãs de esportes em Cleveland.",
  },

  // ── Philadelphia, PA · 18–19 jun ─────────────────────────────
  {
    id: "phi-love",
    name: "Love Park — JFK Plaza",
    category: "park",
    address: "1 N 15th St, Philadelphia, PA 19102",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "18–19 jun",
    rating: 4.6,
    reviewCount: "15.000+",
    hours: "Diariamente 6h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Philadelphia Film Office (film.org)",
    tips:
      "Praça icônica com a escultura LOVE e a Philadelphia City Hall ao fundo — uma das imagens mais reconhecíveis dos EUA. A 10 min do hotel de SEPTA / 10 min de Uber (~$12). Backdrop obrigatório para conteúdo em Philadelphia.",
  },
  {
    id: "phi-assembly",
    name: "Assembly Rooftop Lounge — Logan Hotel",
    category: "rooftop",
    address: "1 Logan Square, Philadelphia, PA 19103",
    area: "Logan Square / Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "18–19 jun",
    rating: 4.4,
    reviewCount: "2.200+",
    hours: "Qui–Sex 17h–0h · Sáb 12h–0h · Dom 12h–20h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Logan Hotel Philadelphia",
    tips:
      "Um dos melhores rooftops de Philadelphia — vista panorâmica da Logan Square, Benjamin Franklin Parkway e Philadelphia Museum of Art. A 10 min do hotel de SEPTA / 10 min de Uber (~$12). Reservar com antecedência em período de Copa.",
  },
  {
    id: "phi-liberty",
    name: "One Liberty Observation Deck",
    category: "observatory",
    address: "1650 Market St, Philadelphia, PA 19103",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "18–19 jun",
    rating: 4.5,
    reviewCount: "3.800+",
    hours: "Seg–Dom 10h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "~$25/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com One Liberty Place",
    tips:
      "Deck de observação no 57º andar — vista 360° de Philadelphia, incluindo Lincoln Financial Field, o Rio Delaware e a skyline completa. A 10 min do hotel de SEPTA / 8 min de Uber (~$10). Ideal para conteúdo noturno com cidade iluminada.",
  },
  {
    id: "phi-xfinity",
    name: "Xfinity Live! Philadelphia",
    category: "sports_bar",
    address: "1100 Pattison Ave, Philadelphia, PA 19148",
    area: "South Philly / Sports Complex",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "18–19 jun",
    rating: 4.2,
    reviewCount: "7.000+",
    hours: "Seg–Qui 11h–2h · Sex–Dom 9h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Complexo de entretenimento esportivo ao lado de Lincoln Financial Field — múltiplas TVs gigantes, restaurantes e bares integrados. A 3 min a pé do estádio. Epicentro da torcida de Philadelphia em dias de Copa.",
  },
  {
    id: "phi-fogo",
    name: "Fogo de Chão Philadelphia",
    category: "brazilian",
    address: "1337 Chestnut St, Philadelphia, PA 19107",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "18–19 jun",
    rating: 4.6,
    reviewCount: "2.800+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha de referência em Philadelphia, no coração do Center City. A 10 min do hotel a pé. Ambiente sofisticado — ideal para conteúdo de brasilidade e hospitalidade durante a Copa.",
  },

  // ── Miami, FL · 23–25 jun ─────────────────────────────────────
  {
    id: "mia-margaret",
    name: "Margaret Pace Park",
    category: "park",
    address: "1745 N Bayshore Dr, Miami, FL 33132",
    area: "Edgewater / Bayfront",
    cidade: "miami",
    cidadeLabel: "Miami",
    periodo: "23–25 jun",
    rating: 4.5,
    reviewCount: "4.000+",
    hours: "Diariamente 6h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Miami-Dade Film Office (filmiami.org)",
    tips:
      "Parque à beira da Baía Biscayne em Edgewater — vista do Downtown Miami e das ilhas. A 10 min do hotel a pé. Opção mais tranquila e próxima que o Bayfront Park, com ótima luz natural no início da manhã.",
  },
  {
    id: "mia-shaker",
    name: "The Broken Shaker — Freehand Miami",
    category: "rooftop",
    address: "2727 Indian Creek Dr, Miami Beach, FL 33140",
    area: "Mid-Beach / Indian Creek",
    cidade: "miami",
    cidadeLabel: "Miami",
    periodo: "23–25 jun",
    rating: 4.4,
    reviewCount: "3.500+",
    hours: "Seg–Qui 15h–1h · Sex–Dom 13h–1h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Freehand Miami",
    tips:
      "Um dos bares de coquetéis mais premiados dos EUA — rooftop pool bar com plantas, arte e clima único. A 25 min do hotel de Uber (~$20). Referência mundial de hospitalidade criativa, muito filmado em campanhas publicitárias.",
  },
  {
    id: "mia-skyviews",
    name: "Skyviews Miami Observation Wheel",
    category: "observatory",
    address: "401 Biscayne Blvd, Miami, FL 33132",
    area: "Bayside / Downtown",
    cidade: "miami",
    cidadeLabel: "Miami",
    periodo: "23–25 jun",
    rating: 4.2,
    reviewCount: "3.200+",
    hours: "Seg–Qui 12h–22h · Sex–Sáb 12h–23h · Dom 12h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "~$20/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Bayside Marketplace",
    tips:
      "Roda-gigante de observação no Bayside Marketplace — vista da Baía Biscayne, do Downtown e da Zona Sul. A 12 min do hotel de Uber (~$12). Visual único tanto de dia (Porto de Miami) quanto à noite (skyline iluminado).",
  },
  {
    id: "mia-wharf",
    name: "The Wharf Miami",
    category: "sports_bar",
    address: "114 SW North River Dr, Miami, FL 33130",
    area: "Miami River",
    cidade: "miami",
    cidadeLabel: "Miami",
    periodo: "23–25 jun",
    rating: 4.3,
    reviewCount: "5.500+",
    hours: "Seg–Qui 17h–2h · Sex 15h–2h · Sáb–Dom 12h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Bar ao ar livre às margens do Rio Miami — múltiplas TVs e atmosfera festiva. A 15 min do hotel de Uber (~$15). Alta energia em dias de Copa com torcida diversa e internacional.",
  },
  {
    id: "mia-boteco",
    name: "Boteco Miami",
    category: "brazilian",
    address: "916 NE 79th St, Miami, FL 33138",
    area: "Upper Eastside / MiMo",
    cidade: "miami",
    cidadeLabel: "Miami",
    periodo: "23–25 jun",
    rating: 4.3,
    reviewCount: "900+",
    hours: "Ter–Dom 17h–0h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "none",
    tips:
      "Bar e restaurante brasileiro no Upper Eastside de Miami — petiscos, chope gelado e ambiente descontraído. A 10 min do hotel de Uber (~$10). Referência da comunidade brasileira em Miami para acompanhar a Copa.",
  },
];
