export type Difficulty = "facil" | "moderado" | "dificil";

export interface InglaterraRoute {
  destino: string;
  endereco: string;
  carN: string;
  carH: string;
  tp: string;
  dist: string;
  diff: Difficulty;
  mapsUrl: string;
}

export interface InglaterraBase {
  id: string;
  emoji: string;
  cidade: string;
  periodo: string;
  hotel: string;
  hotelAddr: string;
  nota?: string;
  fuso?: string;
  referenciaLabel?: string;
  referenciaAddr?: string;
  routes: InglaterraRoute[];
  transitoInfo?: string[];
  insights: string[];
}

export const INGLATERRA_BASES: InglaterraBase[] = [

  // ── BASE 1 — Dallas, TX · base recorrente · 11–18 jun ────────────
  {
    id: "dallas",
    emoji: "🤠",
    cidade: "Dallas TX",
    periodo: "base recorrente · 11–18 jun",
    hotel: "Airbnb (endereço a confirmar)",
    hotelAddr: "Referência: Downtown Dallas, TX — será atualizado com endereço exato",
    nota: "Distâncias calculadas a partir do Downtown Dallas como referência. Serão ajustadas com o endereço exato do Airbnb após confirmação.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h",
    referenciaLabel: "Estádio Copa: AT&T Stadium",
    referenciaAddr: "1 AT&T Way, Arlington, TX 76011",
    routes: [
      {
        destino: "AT&T Stadium",
        endereco: "1 AT&T Way, Arlington, TX 76011",
        carN: "25 min",
        carH: "35–55 min",
        tp: "DART + TRE ~50 min / $2,50",
        dist: "28 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Downtown+Dallas,+TX&daddr=1+ATT+Way,+Arlington,+TX",
      },
      {
        destino: "Dallas Love Field (DAL)",
        endereco: "8008 Herb Kelleher Way, Dallas, TX 75235",
        carN: "15 min",
        carH: "20–30 min",
        tp: "DART Green Line ~20 min / $2,50",
        dist: "11 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Downtown+Dallas,+TX&daddr=8008+Herb+Kelleher+Way,+Dallas,+TX",
      },
      {
        destino: "Dallas Fort Worth (DFW)",
        endereco: "2400 Aviation Dr, DFW Airport, TX 75261",
        carN: "30 min",
        carH: "45–60 min",
        tp: "DART Orange Line ~45 min / $2,50",
        dist: "32 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Downtown+Dallas,+TX&daddr=2400+Aviation+Dr,+DFW+Airport,+TX",
      },
      {
        destino: "Amtrak Union Station",
        endereco: "400 S Houston St, Dallas, TX 75202",
        carN: "8 min",
        carH: "10 min",
        tp: "A pé 12 min / $0",
        dist: "0,9 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Downtown+Dallas,+TX&daddr=400+S+Houston+St,+Dallas,+TX",
      },
      {
        destino: "DART Pearl/Arts District",
        endereco: "1800 N Pearl St, Dallas, TX 75201",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 3 min / $0",
        dist: "0,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Downtown+Dallas,+TX&daddr=1800+N+Pearl+St,+Dallas,+TX",
      },
      {
        destino: "Deep Ellum",
        endereco: "Deep Ellum, Dallas, TX 75226",
        carN: "8 min",
        carH: "12 min",
        tp: "DART Green Line / A pé 15 min",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Downtown+Dallas,+TX&daddr=Deep+Ellum,+Dallas,+TX",
      },
      {
        destino: "Houston (próxima base)",
        endereco: "1540 Leeland St, Houston, TX 77002",
        carN: "N/A",
        carH: "N/A",
        tp: "Voo DAL → HOU Hobby ~1h · Carro I-45 Sul ~3h30",
        dist: "—",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Downtown+Dallas,+TX&daddr=1540+Leeland+St,+Houston,+TX",
      },
    ],
    transitoInfo: [
      "DART Pearl/Arts District Station: hub central com 4 linhas (Red, Blue, Orange, Green). Referência para todo transporte público no Downtown.",
      "Love Field (DAL): DART Green Line ~20 min / $2,50. Preferencial para voos domésticos.",
      "DFW Airport: DART Orange Line ~45 min / $2,50. Para internacionais e conexões.",
      "AT&T Stadium em Arlington: sem metrô direto. DART + TRE (Trinity Railway Express) — descer em CentrePort e pegar Uber/ônibus de game day. Surge pricing alto em dias de Copa.",
      "Tarifa DART: $2,50 / viagem · $5 diário · $15 semanal.",
    ],
    insights: [
      "⚠️ Endereço Airbnb a confirmar — distâncias e links serão ajustados com o endereço exato.",
      "AT&T Stadium em Arlington: sem metrô direto. Uber ou TRE obrigatório em dias de Copa.",
      "⚠️ Surge pricing nos dias de jogo — pedir Uber com 30 min de antecedência.",
      "DART Pearl/Arts District é o hub de transporte mais conveniente do Downtown.",
      "Fuso CDT (UTC -5h) · BRT = CDT +2h · EDT (NJ) = CDT +1h.",
      "Love Field (DAL) preferível ao DFW para voos domésticos — 11 km vs 32 km do Downtown.",
    ],
  },

  // ── BASE 2 — Houston, TX · 18–20 jun ─────────────────────────────
  {
    id: "houston",
    emoji: "🛢️",
    cidade: "Houston TX",
    periodo: "18–20 jun",
    hotel: "Home2 Suites by Hilton Houston Downtown Convention Center",
    hotelAddr: "1540 Leeland St, Houston, TX 77002",
    nota: "Hotel 4.5★ no Downtown Houston, a 3 min a pé da estação METRORail Convention District. Café da manhã incluído. Bar/restaurante no local.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h · mesmo fuso que Dallas ✅",
    referenciaLabel: "Estádio Copa: NRG Stadium",
    referenciaAddr: "1 NRG Pkwy, Houston, TX 77054",
    routes: [
      {
        destino: "NRG Stadium",
        endereco: "1 NRG Pkwy, Houston, TX 77054",
        carN: "10 min",
        carH: "15–25 min",
        tp: "METRORail Red Line ~15 min / $1,25",
        dist: "7 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1540+Leeland+St,+Houston,+TX&daddr=1+NRG+Pkwy,+Houston,+TX",
      },
      {
        destino: "Houston IAH (Bush)",
        endereco: "2800 N Terminal Rd, Houston, TX 77032",
        carN: "35 min",
        carH: "50–70 min",
        tp: "Metro + ônibus ~1h20 / $3,50",
        dist: "45 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1540+Leeland+St,+Houston,+TX&daddr=2800+N+Terminal+Rd,+Houston,+TX",
      },
      {
        destino: "Hobby Airport (HOU)",
        endereco: "7800 Airport Blvd, Houston, TX 77061",
        carN: "20 min",
        carH: "30 min",
        tp: "METRORail + ônibus ~40 min / $2,50",
        dist: "17 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1540+Leeland+St,+Houston,+TX&daddr=7800+Airport+Blvd,+Houston,+TX",
      },
      {
        destino: "Houston Amtrak (Union Station)",
        endereco: "902 Washington Ave, Houston, TX 77002",
        carN: "8 min",
        carH: "10 min",
        tp: "METRORail ~10 min / $1,25",
        dist: "4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1540+Leeland+St,+Houston,+TX&daddr=902+Washington+Ave,+Houston,+TX",
      },
      {
        destino: "METRORail Convention District",
        endereco: "1600 Leeland St, Houston, TX 77002",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 3 min / $0",
        dist: "0,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1540+Leeland+St,+Houston,+TX&daddr=1600+Leeland+St,+Houston,+TX",
      },
      {
        destino: "George R. Brown Convention Center",
        endereco: "1001 Avenida De Las Americas, Houston, TX 77010",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 5 min / $0",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1540+Leeland+St,+Houston,+TX&daddr=1001+Avenida+De+Las+Americas,+Houston,+TX",
      },
      {
        destino: "New Jersey (próxima base)",
        endereco: "Newark Liberty International Airport, NJ",
        carN: "N/A",
        carH: "N/A",
        tp: "Voo IAH → EWR ~3h30 / $150–400",
        dist: "—",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1540+Leeland+St,+Houston,+TX&daddr=Newark+Liberty+International+Airport,+NJ",
      },
    ],
    transitoInfo: [
      "METRORail Red Line: estação Convention District a 3 min a pé do hotel. Linha direta ao NRG Stadium (Reliant Park) em ~15 min / $1,25.",
      "Tarifa METRORail: $1,25 por viagem.",
      "IAH (Bush): preferível para o voo a Newark (EWR). Acesso via Uber (~35 min / $35–55). Metro + ônibus ~1h20.",
      "Hobby Airport (HOU): mais perto, mas sem voos diretos frequentes para EWR. Use HOU para domésticos Southwest.",
    ],
    insights: [
      "✅ METRORail Convention District a 3 min a pé — acesso direto ao NRG Stadium sem Uber.",
      "NRG Stadium em dias de Copa: METRORail obrigatório. Ir pelo menos 1h30 antes dos portões.",
      "⚠️ Valet no hotel: cobranças confirmadas via terceirizado — verificar antes de usar.",
      "IAH para o voo a Newark (EWR) — preferir IAH sobre HOU para este trecho.",
      "Fuso: Houston é CDT (UTC -5h) · BRT = CDT +2h · mesmo fuso que Dallas ✅",
      "⚠️ Ao partir para NJ (20 jun): fuso avança 1h — CDT → EDT. Ajustar alarmes.",
    ],
  },

  // ── BASE 3 — New Jersey · base recorrente · 20–24 jun + 26–28 jun
  {
    id: "new-jersey",
    emoji: "🗽",
    cidade: "New Jersey",
    periodo: "base recorrente · 20–24 jun · 26–28 jun",
    hotel: "Harmony Suites Secaucus (26–28 jun) · Airbnb a confirmar (20–24 jun)",
    hotelAddr: "455 Plaza Dr, Secaucus, NJ 07094 (Harmony Suites) · Airbnb: a confirmar",
    nota: "Harmony Suites 3.8★ — 2 min de carro do MetLife Stadium. Café da manhã, estacionamento gratuito, omeleteira e waffles. Pool a confirmar. Airbnb 20–24 jun: usar Hoboken como referência para distâncias até confirmação do endereço.",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h · CDT (Dallas/Houston/KC) = EDT -1h",
    referenciaLabel: "Estádio Copa: MetLife Stadium",
    referenciaAddr: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
    routes: [
      {
        destino: "MetLife Stadium",
        endereco: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 15 min / shuttle $0",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=1+MetLife+Stadium+Dr,+East+Rutherford,+NJ",
      },
      {
        destino: "Newark Intl (EWR)",
        endereco: "Newark Liberty International Airport, NJ",
        carN: "12 min",
        carH: "18 min",
        tp: "NJ Transit ~20 min / $5,50",
        dist: "10 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=Newark+Liberty+International+Airport,+NJ",
      },
      {
        destino: "New York Penn Station",
        endereco: "Penn Station, New York, NY 10001",
        carN: "20 min",
        carH: "30–45 min",
        tp: "NJ Transit ~25 min / $8",
        dist: "14 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "JFK International",
        endereco: "John F. Kennedy International Airport, NY",
        carN: "40 min",
        carH: "60–90 min",
        tp: "NJT + metrô ~70 min",
        dist: "30 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=John+F+Kennedy+International+Airport,+NY",
      },
      {
        destino: "LaGuardia (LGA)",
        endereco: "LaGuardia Airport, Queens, NY",
        carN: "30 min",
        carH: "50–70 min",
        tp: "NJT + bus ~55 min",
        dist: "22 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=LaGuardia+Airport,+Queens,+NY",
      },
      {
        destino: "Hoboken Terminal (PATH)",
        endereco: "Hoboken Terminal, Hoboken, NJ 07030",
        carN: "10 min",
        carH: "15 min",
        tp: "NJ Transit ~12 min / $3,50",
        dist: "6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=Hoboken+Terminal,+Hoboken,+NJ",
      },
      {
        destino: "Times Square",
        endereco: "Times Square, New York, NY",
        carN: "22 min",
        carH: "35–50 min",
        tp: "NJ Transit → Penn + metrô ~35 min",
        dist: "16 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=Times+Square,+New+York,+NY",
      },
      {
        destino: "American Dream Mall",
        endereco: "1 American Dream Way, East Rutherford, NJ 07073",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 15 min / $0",
        dist: "1,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=1+American+Dream+Way,+East+Rutherford,+NJ",
      },
      {
        destino: "Kansas City (próxima base)",
        endereco: "Kansas City International Airport, MO",
        carN: "N/A",
        carH: "N/A",
        tp: "Voo EWR → MCI ~2h45 / $150–400",
        dist: "—",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=455+Plaza+Dr,+Secaucus,+NJ&daddr=Kansas+City+International+Airport,+MO",
      },
    ],
    transitoInfo: [
      "NJ Transit (NJT): principal modal em NJ. Liga Secaucus Junction a Penn Station NYC (~25 min / $8) e EWR (~20 min / $5,50).",
      "Secaucus Junction: hub NJ Transit com trens para Penn Station NYC, EWR e demais cidades NJ.",
      "PATH de Hoboken: alternativa ao NJT para Manhattan — 6 km de Secaucus. Conecta WTC e 33rd St / $2,10.",
      "MetLife Stadium: a 2 km de Harmony Suites — hospedagem mais próxima do estádio de todas as equipes mapeadas.",
      "EWR: aeroporto mais prático desta base. AirTrain conecta ao terminal a partir da estação Newark Liberty International.",
    ],
    insights: [
      "✅ Harmony Suites: hotel mais próximo do MetLife Stadium — 3 min de carro. Base ideal para os jogos da Copa.",
      "⚠️ Airbnb NJ (20–24 jun): endereço a confirmar — distâncias serão ajustadas.",
      "MetLife em dias de Copa: perímetro FIFA fecha às 14h. Sair com antecedência — NJ Transit preferível ao Uber.",
      "⚠️ Harmony Suites 3.8★ — pool pode estar fora de operação. Confirmar antes da chegada.",
      "EWR é o aeroporto preferido desta base — mais próximo e mais simples que JFK/LGA.",
      "American Dream Mall: 1,2 km de Harmony Suites — maior complexo de entretenimento dos EUA. 15 min a pé.",
      "Fuso: EDT (UTC -4h) · BRT = EDT +1h · Ao chegar de KC (26 jun): fuso avança 1h.",
    ],
  },

  // ── BASE 4 — Kansas City, MO · 24–26 jun ─────────────────────────
  {
    id: "kansas-city",
    emoji: "🏈",
    cidade: "Kansas City MO",
    periodo: "24–26 jun",
    hotel: "Hotel Phillips Kansas City Curio Collection by Hilton",
    hotelAddr: "106 W 12th St, Kansas City, MO 64105",
    nota: "Mesmo hotel das Equipes Argentina, Brasil (Defante) e Host (Bárbara Coelho). Centro histórico de KC, valet disponível. RideKC Streetcar gratuito saindo do hotel.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h",
    referenciaLabel: "Estádio Copa: GEHA Field at Arrowhead",
    referenciaAddr: "1 Arrowhead Dr, Kansas City, MO 64129",
    routes: [
      {
        destino: "GEHA Field at Arrowhead",
        endereco: "1 Arrowhead Dr, Kansas City, MO 64129",
        carN: "18–25 min",
        carH: "30–45 min",
        tp: "Sem TP direto — Uber / shuttle Copa",
        dist: "18 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Arrowhead+Dr,+Kansas+City,+MO",
      },
      {
        destino: "MCI Airport",
        endereco: "1 Kansas City Blvd, Kansas City, MO 64153",
        carN: "25 min",
        carH: "35–40 min",
        tp: "Uber ~25 min / $35–55",
        dist: "26 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=1+Kansas+City+Blvd,+Kansas+City,+MO",
      },
      {
        destino: "Union Station KC",
        endereco: "30 W Pershing Rd, Kansas City, MO 64108",
        carN: "4 min",
        carH: "8 min",
        tp: "RideKC Streetcar ~10 min / $0 · A pé 15 min",
        dist: "1,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=30+W+Pershing+Rd,+Kansas+City,+MO",
      },
      {
        destino: "RideKC Streetcar",
        endereco: "Main St & 12th St, Kansas City, MO 64105",
        carN: "1 min",
        carH: "2 min",
        tp: "Gratuito · Para na porta do hotel",
        dist: "200 m",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=106+W+12th+St,+Kansas+City,+MO&daddr=Main+St+%26+12th+St,+Kansas+City,+MO",
      },
      {
        destino: "New Jersey (retorno)",
        endereco: "Newark Liberty International Airport, NJ",
        carN: "N/A",
        carH: "N/A",
        tp: "Voo MCI → EWR ~2h45 / $150–400",
        dist: "—",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Kansas+City+International+Airport,+MO&daddr=Newark+Liberty+International+Airport,+NJ",
      },
    ],
    transitoInfo: [
      "RideKC Streetcar: gratuito, percorre Main St de Union Station até Country Club Plaza. Para na porta do Hotel Phillips.",
      "GEHA Field at Arrowhead: sem ônibus regular. Shuttle FIFA Copa a confirmar — checar copa2026.com. Pedir Uber com 30 min de antecedência.",
      "MCI Airport: sem metrô. Uber preferencial (~$35–55). Sem trânsito: ~25 min.",
    ],
    insights: [
      "⚠️ GEHA Field sem transporte público. Uber obrigatório — pedir com 30 min de antecedência em dia de jogo.",
      "⚠️ Surge pricing ao final dos jogos em Arrowhead — pedir Uber antes de sair do estádio.",
      "RideKC Streetcar gratuito para Downtown KC — para na porta do hotel.",
      "⚠️ Mudança de fuso ao voltar para NJ (26 jun): KC é CDT → NJ é EDT. Ao chegar em NJ o horário avança 1h.",
      "Fuso: Kansas City é CDT (UTC -5h) · BRT = CDT +2h.",
      "Mesmo hotel das Equipes Argentina e Brasil (Defante) — referências operacionais adicionais disponíveis nesses portais.",
    ],
  },
];
