import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type UruguaiPermit = "none" | "film_office" | "city_permit" | "venue_specific";

export const URUGUAI_PERMIT_LABEL: Record<
  UruguaiPermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",           tone: "green" },
  film_office:    { label: "Film Office local",    tone: "amber" },
  city_permit:    { label: "Prefeitura local",     tone: "amber" },
  venue_specific: { label: "Negociar com o local", tone: "orange" },
};

export interface UruguaiVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade: "cancun" | "miami-1" | "boston" | "miami-2" | "guadalajara";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: UruguaiPermit;
  permitNote?: string;
  tips: string;
}

export const URUGUAI_VENUES: UruguaiVenueItem[] = [
  // ── Cancún 10–13 jun ──────────────────────────────────────────
  {
    id: "can-palapas",
    name: "Parque Las Palapas",
    category: "park",
    address: "Av. Tulum s/n, Centro, 77500 Cancún, Q.R.",
    area: "Centro",
    cidade: "cancun",
    cidadeLabel: "Cancún",
    periodo: "10–13 jun",
    rating: 4.5,
    reviewCount: "8.000+",
    hours: "Diariamente 6h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "SEMA Quintana Roo (sema.qroo.gob.mx)",
    tips:
      "Principal praça pública do Centro de Cancún — ambiente local autêntico, distante da Zona Hoteleira. A 5 min do hotel a pé. Ótima luz natural para gravações externas durante o dia.",
  },
  {
    id: "can-nomads",
    name: "Nomads Hotel Cancún — Rooftop Bar",
    category: "rooftop",
    address: "Av. Uxmal 46, Centro, 77500 Cancún, Q.R.",
    area: "Centro",
    cidade: "cancun",
    cidadeLabel: "Cancún",
    periodo: "10–13 jun",
    rating: 4.3,
    reviewCount: "700+",
    hours: "Seg–Dom 18h–1h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Nomads Hotel Cancún",
    tips:
      "Rooftop bar no coração do Downtown de Cancún com piscina e vista da cidade. A 8 min do hotel a pé. Ambiente descontraído e moderno — referência entre jovens e viajantes na cidade.",
  },
  {
    id: "can-elrey",
    name: "Zona Arqueológica El Rey",
    category: "observatory",
    address: "Blvd. Kukulcán km 18, Zona Hotelera, 77500 Cancún, Q.R.",
    area: "Zona Hotelera",
    cidade: "cancun",
    cidadeLabel: "Cancún",
    periodo: "10–13 jun",
    rating: 4.3,
    reviewCount: "5.000+",
    hours: "Diariamente 8h–17h",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "~$70 MXN/pessoa",
    permit: "venue_specific",
    permitNote: "INAH (inah.gob.mx)",
    tips:
      "Ruínas maias na Zona Hoteleira com iguanas e natureza exuberante — visual único para conteúdo temático. A 20 min do hotel de Uber (~$80 MXN). Filmagem comercial exige autorização prévia do INAH.",
  },
  {
    id: "can-senorfrog",
    name: "Señor Frog's Cancún",
    category: "sports_bar",
    address: "Blvd. Kukulcán km 9.5, Zona Hotelera, 77500 Cancún, Q.R.",
    area: "Zona Hotelera",
    cidade: "cancun",
    cidadeLabel: "Cancún",
    periodo: "10–13 jun",
    rating: 4.0,
    reviewCount: "18.000+",
    hours: "Diariamente 9h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Ícone do entretenimento em Cancún — múltiplas TVs, energia altíssima em dias de Copa. A 20 min do hotel de Uber. Referência para torcida internacional na Zona Hoteleira.",
  },

  // ── Miami 1ª 13–16 jun ────────────────────────────────────────
  {
    id: "mia1-bayfront",
    name: "Bayfront Park",
    category: "park",
    address: "301 Biscayne Blvd, Miami, FL 33132",
    area: "Downtown",
    cidade: "miami-1",
    cidadeLabel: "Miami 1ª",
    periodo: "13–16 jun",
    rating: 4.6,
    reviewCount: "22.000+",
    hours: "Diariamente 6h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Miami-Dade Film Office (filmiami.org)",
    tips:
      "Parque central de Miami com vista panorâmica da Baía Biscayne e do skyline. A 15 min do Airbnb de Uber. Backdrop reconhecível — muito filmado em eventos como a Copa. Permit via Miami-Dade Film Office.",
  },
  {
    id: "mia1-sugar",
    name: "Sugar — EAST Miami",
    category: "rooftop",
    address: "788 Brickell Plaza, Miami, FL 33131",
    area: "Brickell",
    cidade: "miami-1",
    cidadeLabel: "Miami 1ª",
    periodo: "13–16 jun",
    rating: 4.4,
    reviewCount: "5.500+",
    hours: "Seg–Qui 17h–23h · Sex 15h–0h · Sáb 12h–0h · Dom 12h–22h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com EAST Miami Hotel",
    tips:
      "Rooftop mais badalado de Brickell — vista 360° do skyline de Miami e da Baía Biscayne. A 10 min do Airbnb de Uber. Uma das locações mais filmadas da cidade — reservar com antecedência.",
  },
  {
    id: "mia1-pamm",
    name: "Pérez Art Museum Miami (PAMM)",
    category: "observatory",
    address: "1103 Biscayne Blvd, Miami, FL 33132",
    area: "Edgewater / Downtown",
    cidade: "miami-1",
    cidadeLabel: "Miami 1ª",
    periodo: "13–16 jun",
    rating: 4.6,
    reviewCount: "9.000+",
    hours: "Ter–Dom 10h–18h · Qui 10h–21h",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "~$16/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com PAMM",
    tips:
      "Museu de arte contemporânea com terraço suspenso sobre a Baía Biscayne — arquitetura icônica e visual único. A 15 min do Airbnb de Uber. Agendamento antecipado obrigatório para filmagens comerciais.",
  },
  {
    id: "mia1-fogo",
    name: "Fogo de Chão Miami Beach",
    category: "brazilian",
    address: "836 1st St, Miami Beach, FL 33139",
    area: "Miami Beach",
    cidade: "miami-1",
    cidadeLabel: "Miami 1ª",
    periodo: "13–16 jun",
    rating: 4.5,
    reviewCount: "3.500+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha de referência em Miami, no coração de South Beach. A 20 min do Airbnb de Uber. Ambiente sofisticado — ideal para conteúdo de brasilidade durante a Copa.",
  },
  {
    id: "mia1-wharf",
    name: "The Wharf Miami",
    category: "sports_bar",
    address: "114 SW North River Dr, Miami, FL 33130",
    area: "Miami River",
    cidade: "miami-1",
    cidadeLabel: "Miami 1ª",
    periodo: "13–16 jun",
    rating: 4.3,
    reviewCount: "5.500+",
    hours: "Seg–Qui 17h–2h · Sex 15h–2h · Sáb–Dom 12h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Bar ao ar livre às margens do Rio Miami — múltiplas TVs e atmosfera festiva. A 10 min do Airbnb de Uber. Alta energia em dias de Copa com torcida diversa e internacional.",
  },

  // ── Boston 16–20 jun ──────────────────────────────────────────
  {
    id: "bos-common",
    name: "Boston Common & Public Garden",
    category: "park",
    address: "139 Tremont St, Boston, MA 02111",
    area: "Downtown",
    cidade: "boston",
    cidadeLabel: "Boston",
    periodo: "16–20 jun",
    rating: 4.8,
    reviewCount: "50.000+",
    hours: "Diariamente 24h (áreas externas)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Mayor's Office of Special Events (boston.gov)",
    tips:
      "Parques históricos mais famosos dos EUA — Boston Common (1634) e Public Garden lado a lado. A 20 min do hotel de T. Backdrop icônico com lago e cisnes — reconhecível mundialmente.",
  },
  {
    id: "bos-lookout",
    name: "Lookout Rooftop & Bar — Envoy Hotel",
    category: "rooftop",
    address: "70 Sleeper St, Boston, MA 02210",
    area: "Seaport District",
    cidade: "boston",
    cidadeLabel: "Boston",
    periodo: "16–20 jun",
    rating: 4.4,
    reviewCount: "4.200+",
    hours: "Seg–Qui 17h–23h · Sex 15h–0h · Sáb 12h–0h · Dom 12h–22h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Envoy Hotel",
    tips:
      "Melhor rooftop de Boston — vista do Seaport District e da ponte Fort Point Channel. A 25 min do hotel de Uber. Reservar com antecedência em período de Copa.",
  },
  {
    id: "bos-skywalk",
    name: "Skywalk Observatory — Prudential Center",
    category: "observatory",
    address: "800 Boylston St, Boston, MA 02199",
    area: "Back Bay",
    cidade: "boston",
    cidadeLabel: "Boston",
    periodo: "16–20 jun",
    rating: 4.5,
    reviewCount: "6.500+",
    hours: "Diariamente 10h–20h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "~$21/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Prudential Center",
    tips:
      "Vista 360° de Boston a 229m de altitude — a 5 min do hotel a pé. Dá pra ver o Fenway Park, o Rio Charles e o skyline de Back Bay. Piso de vidro e exposição permanente. Referência obrigatória para conteúdo de Boston.",
  },
  {
    id: "bos-gameon",
    name: "Game On! Fenway",
    category: "sports_bar",
    address: "82 Lansdowne St, Boston, MA 02215",
    area: "Fenway",
    cidade: "boston",
    cidadeLabel: "Boston",
    periodo: "16–20 jun",
    rating: 4.3,
    reviewCount: "5.000+",
    hours: "Seg–Sex 11h–2h · Sáb–Dom 10h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Sports bar mais famoso de Boston, ao lado do Fenway Park — múltiplas TVs gigantes, torcida intensa em dias de Copa. A 5 min do hotel a pé. Alta energia garantida para transmissão de jogos.",
  },
  {
    id: "bos-fogo",
    name: "Fogo de Chão Boston",
    category: "brazilian",
    address: "200 State St, Boston, MA 02109",
    area: "Downtown / Financial District",
    cidade: "boston",
    cidadeLabel: "Boston",
    periodo: "16–20 jun",
    rating: 4.6,
    reviewCount: "3.800+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha de referência em Boston, no Financial District. A 25 min do hotel de T. Ambiente sofisticado — ideal para conteúdo de brasilidade e hospitalidade durante a Copa.",
  },

  // ── Miami 2ª 20–24 jun ────────────────────────────────────────
  {
    id: "mia2-southpointe",
    name: "South Pointe Park Pier",
    category: "park",
    address: "1 Washington Ave, Miami Beach, FL 33139",
    area: "South Beach / South Pointe",
    cidade: "miami-2",
    cidadeLabel: "Miami 2ª",
    periodo: "20–24 jun",
    rating: 4.7,
    reviewCount: "12.000+",
    hours: "Diariamente 6h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "Miami Beach Film & Print Office",
    tips:
      "Parque no extremo sul de Miami Beach com vista do porto, dos cruzeiros e do oceano. A 20 min do Airbnb de Uber. Visual diferente do Bayfront Park — skyline do Downtown ao fundo em posição privilegiada.",
  },
  {
    id: "mia2-1hotel",
    name: "Rooftop at 1 Hotel South Beach",
    category: "rooftop",
    address: "2341 Collins Ave, Miami Beach, FL 33139",
    area: "Miami Beach / Collins Ave",
    cidade: "miami-2",
    cidadeLabel: "Miami 2ª",
    periodo: "20–24 jun",
    rating: 4.4,
    reviewCount: "3.000+",
    hours: "Seg–Dom 18h–1h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com 1 Hotel South Beach",
    tips:
      "Rooftop do icônico 1 Hotel South Beach — vista do oceano e do Art Deco Historic District. A 25 min do Airbnb de Uber. Um dos rooftops mais fotografados de Miami Beach.",
  },
  {
    id: "mia2-skyviews",
    name: "Skyviews Miami Observation Wheel",
    category: "observatory",
    address: "401 Biscayne Blvd, Miami, FL 33132",
    area: "Bayside / Downtown",
    cidade: "miami-2",
    cidadeLabel: "Miami 2ª",
    periodo: "20–24 jun",
    rating: 4.2,
    reviewCount: "3.200+",
    hours: "Seg–Qui 12h–22h · Sex–Sáb 12h–23h · Dom 12h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "~$20/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Bayside Marketplace",
    tips:
      "Roda-gigante de observação no Bayside Marketplace — vista da Baía Biscayne, do Downtown e da Zona Sul. A 15 min do Airbnb de Uber. Visual único tanto de dia (Porto de Miami) quanto à noite (skyline iluminado).",
  },
  {
    id: "mia2-ballandchain",
    name: "Ball & Chain — Little Havana",
    category: "sports_bar",
    address: "1513 SW 8th St, Miami, FL 33135",
    area: "Little Havana / Calle Ocho",
    cidade: "miami-2",
    cidadeLabel: "Miami 2ª",
    periodo: "20–24 jun",
    rating: 4.3,
    reviewCount: "7.000+",
    hours: "Seg–Qui 12h–23h · Sex–Sáb 12h–2h · Dom 12h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Ícone histórico da Calle Ocho desde 1935 — bar com música ao vivo, TVs para jogos e energia cultural única de Little Havana. A 15 min do Airbnb de Uber. Perfeito para conteúdo sobre Miami multicultural durante a Copa.",
  },

  // ── Guadalajara 24–28 jun ─────────────────────────────────────
  {
    id: "gdlury-colomos",
    name: "Parque Los Colomos",
    category: "park",
    address: "Av. Niños Héroes 2880, Providencia, Guadalajara, Jal.",
    area: "Providencia",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara",
    periodo: "24–28 jun",
    rating: 4.8,
    reviewCount: "16.000+",
    hours: "Diariamente 6h–18h",
    goodDay: "yes",
    goodNight: "no",
    cost: "free",
    permit: "city_permit",
    permitNote: "SIOP Jalisco (siop.jalisco.gob.mx)",
    tips:
      "Parque urbano com lago, trilhas e bosque. Bairro Providencia — seguro e próximo a Chapalita. A 10 min do hotel de Uber. Excelente luz natural para gravações externas.",
  },
  {
    id: "gdlury-demetria",
    name: "Hotel Demetria — Rooftop Bar",
    category: "rooftop",
    address: "Av. de la Paz 2349, Col. Americana, Guadalajara, Jal.",
    area: "Colonia Americana",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara",
    periodo: "24–28 jun",
    rating: 4.6,
    reviewCount: "1.200+",
    hours: "Seg–Dom 18h–1h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima (~$200 MXN)",
    permit: "venue_specific",
    permitNote: "Direto com Hotel Demetria",
    tips:
      "Melhor rooftop de Guadalajara, no bairro Americana. Vista do skyline de GDL. A 15 min do hotel de Uber. Ambiente sofisticado com coquetéis artesanais.",
  },
  {
    id: "gdlury-cabanas",
    name: "Instituto Cultural Cabañas",
    category: "observatory",
    address: "Cabañas 8, Centro Histórico, Guadalajara, Jal.",
    area: "Centro Histórico",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara",
    periodo: "24–28 jun",
    rating: 4.8,
    reviewCount: "10.000+",
    hours: "Ter–Dom 10h–17h45",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "~$80 MXN/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Instituto Cabañas",
    tips:
      "Patrimônio da Humanidade UNESCO. Afrescos de José Clemente Orozco no teto da cúpula central — visual único mundialmente. A 20 min do hotel de Uber. Autorização institucional prévia obrigatória para filmagem comercial.",
  },
  {
    id: "gdlury-dublin",
    name: "The Dublin Pub Guadalajara",
    category: "sports_bar",
    address: "Av. México 3070, Guadalajara, Jal.",
    area: "Colonia Monraz",
    cidade: "guadalajara",
    cidadeLabel: "Guadalajara",
    periodo: "24–28 jun",
    rating: 4.2,
    reviewCount: "2.000+",
    hours: "Seg–Dom 13h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Pub de referência em Guadalajara para transmissão de jogos internacionais. Copa do Mundo transmitida em múltiplas telas. A 10 min do hotel de Uber. Alta energia em dias de jogo.",
  },
];
