export type Difficulty = "facil" | "moderado" | "dificil";

export interface FrancaRoute {
  destino: string;
  endereco: string;
  carN: string;
  carH: string;
  tp: string;
  dist: string;
  diff: Difficulty;
  mapsUrl: string;
}

export interface FrancaBase {
  id: string;
  emoji: string;
  cidade: string;
  periodo: string;
  hotel: string;
  hotelAddr: string;
  nota?: string;
  fuso?: string;
  referenciaLabel?: string;
  referenciaAddr?: string;
  routes: FrancaRoute[];
  transitoInfo?: string[];
  insights: string[];
}

export const FRANCA_BASES: FrancaBase[] = [
  // ── BASE 1 — Los Angeles ───────────────────────────────────
  {
    id: "los-angeles",
    emoji: "🎬",
    cidade: "Los Angeles",
    periodo: "09–13 jun",
    hotel: "The O Hotel, Trademark Collection by Wyndham",
    hotelAddr: "819 Flower St, Los Angeles, CA 90017",
    fuso: "PDT (UTC -7h) · BRT = PDT +4h",
    referenciaLabel: "Estádio Copa: SoFi Stadium",
    referenciaAddr: "1001 S Stadium Dr, Inglewood, CA 90301",
    routes: [
      {
        destino: "SoFi Stadium (Copa)",
        endereco: "1001 S Stadium Dr, Inglewood, CA 90301",
        carN: "20 min",
        carH: "30–60 min",
        tp: "Metro C Line ~35 min / $1,75",
        dist: "20 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=1001+S+Stadium+Dr,+Inglewood,+CA",
      },
      {
        destino: "LAX — Los Angeles Intl",
        endereco: "1 World Way, Los Angeles, CA 90045",
        carN: "25 min",
        carH: "40–75 min",
        tp: "FlyAway Bus de Union Station ~45 min / $9,75",
        dist: "26 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=1+World+Way,+Los+Angeles,+CA+90045",
      },
      {
        destino: "Burbank Airport (BUR / Hollywood Burbank)",
        endereco: "2627 N Hollywood Way, Burbank, CA 91505",
        carN: "30 min",
        carH: "45–70 min",
        tp: "Uber recomendado — sem metro direto",
        dist: "30 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=2627+N+Hollywood+Way,+Burbank,+CA",
      },
      {
        destino: "Long Beach Airport (LGB)",
        endereco: "4100 Donald Douglas Dr, Long Beach, CA 90808",
        carN: "30 min",
        carH: "50–80 min",
        tp: "Uber recomendado — sem metro direto",
        dist: "36 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=4100+Donald+Douglas+Dr,+Long+Beach,+CA",
      },
      {
        destino: "Union Station LA (Amtrak / hub)",
        endereco: "800 N Alameda St, Los Angeles, CA 90012",
        carN: "8 min",
        carH: "12 min",
        tp: "Metro B/D Line ~10 min / $1,75",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=800+N+Alameda+St,+Los+Angeles,+CA",
      },
      {
        destino: "7th St / Metro Center",
        endereco: "701 S Flower St, Los Angeles, CA 90017",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé ~5 min / $0",
        dist: "0,3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=701+S+Flower+St,+Los+Angeles,+CA",
      },
      {
        destino: "Greyhound Los Angeles",
        endereco: "1716 E 7th St, Los Angeles, CA 90021",
        carN: "10 min",
        carH: "12 min",
        tp: "Metro ~8 min / $1,75",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=1716+E+7th+St,+Los+Angeles,+CA",
      },
      {
        destino: "Downtown LA — Grand Park",
        endereco: "200 N Grand Ave, Los Angeles, CA 90012",
        carN: "5 min",
        carH: "7 min",
        tp: "A pé ~10 min / $0",
        dist: "0,8 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=200+N+Grand+Ave,+Los+Angeles,+CA",
      },
      {
        destino: "Hollywood / Walk of Fame",
        endereco: "6925 Hollywood Blvd, Los Angeles, CA 90028",
        carN: "15 min",
        carH: "25 min",
        tp: "Metro B Line (Red) 7th/Metro → Hollywood/Highland ~20 min / $1,75",
        dist: "14 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=6925+Hollywood+Blvd,+Los+Angeles,+CA",
      },
      {
        destino: "Santa Monica",
        endereco: "200 Santa Monica Pier, Santa Monica, CA 90401",
        carN: "25 min",
        carH: "40–60 min",
        tp: "Metro Expo Line (E) 7th/Metro → Downtown Santa Monica ~50 min / $1,75",
        dist: "24 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+Flower+St,+Los+Angeles,+CA&daddr=200+Santa+Monica+Pier,+Santa+Monica,+CA",
      },
    ],
    transitoInfo: [
      "Estação mais próxima do hotel: 7th St / Metro Center (5 min a pé) — conecta linhas A, B, D, E.",
      "Até SoFi Stadium: Metro C Line (Green) — transferência em Rosa Parks ou Expo/La Cienega. Em dia de jogo: shuttle FIFA na saída da estação.",
      "Até LAX: FlyAway Bus de Union Station (~45 min / $9,75) é mais confiável que Uber. Metro C até Lot C + LAX shuttle gratuito (mais barato, ~35 min extra).",
      "Tarifa Metro LA: $1,75 por viagem / $7 diário / $25 semanal (TAP Card recomendado).",
      "BUR e LGB: sem metrô direto — Uber ou carro recomendado.",
    ],
    insights: [
      "SoFi Stadium em dias de jogo: perímetro FIFA fecha 3h antes. Metro C Line obrigatório — sair do hotel ANTES das 13h em jogos de 16h.",
      "Trânsito LA é o pior dos EUA. Nunca planejar 7h–10h e 16h–20h para deslocamentos críticos.",
      "LAX: FlyAway Bus de Union Station é mais confiável que Uber em horário de pico. Recomendado para chegadas/saídas da equipe.",
      "Segurança no Downtown: manter-se nas áreas comerciais ao redor do hotel. Evitar caminhar à noite além do Grand Park.",
      "Fuso: Los Angeles é PDT (UTC -7h). Horário do Brasil: BRT = PDT +4h.",
      "Uber/Lyft amplamente disponíveis — média $25–55 para SoFi, $35–55 para LAX.",
    ],
  },

  // ── BASE 2 — Boston Seaport I ──────────────────────────────
  {
    id: "boston-seaport-1",
    emoji: "🦞",
    cidade: "Boston Seaport",
    periodo: "13–14 jun",
    hotel: "Aloft by Marriott, Boston Seaport District",
    hotelAddr: "401-403 D St, Boston, MA 02210",
    nota: "Escala de 1 noite — trânsito entre LA e NJ",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      {
        destino: "Gillette Stadium (Copa)",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "40 min",
        carH: "55–80 min",
        tp: "Commuter Rail de South Station + shuttle ~75 min / $15",
        dist: "55 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      {
        destino: "Boston Logan (BOS)",
        endereco: "Logan International Airport, East Boston, MA 02128",
        carN: "10 min",
        carH: "15 min",
        tp: "Silver Line SL1 gratuito do aeroporto / $2,40 ao aeroporto — ~20 min",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=Logan+International+Airport,+East+Boston,+MA",
      },
      {
        destino: "South Station (Amtrak + T + ônibus)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "8 min",
        carH: "10 min",
        tp: "Silver Line SL2 ~12 min / $2,40",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Convention Center / BCEC",
        endereco: "415 Summer St, Boston, MA 02210",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé ~5 min / $0",
        dist: "0,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=415+Summer+St,+Boston,+MA",
      },
      {
        destino: "Downtown Boston",
        endereco: "Downtown Boston, MA",
        carN: "10 min",
        carH: "15 min",
        tp: "Silver Line + Red Line ~20 min / $2,40",
        dist: "4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=Downtown+Boston,+MA",
      },
      {
        destino: "Back Bay Station (Amtrak)",
        endereco: "145 Dartmouth St, Boston, MA 02116",
        carN: "15 min",
        carH: "20 min",
        tp: "Uber ou Silver Line + Orange Line ~20 min / $2,40",
        dist: "6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=145+Dartmouth+St,+Boston,+MA",
      },
    ],
    transitoInfo: [
      "Silver Line SL1: Logan Airport ↔ South Station direto. Gratuita saindo do aeroporto. Embarcar no hotel: Silver Line Way (~0,4 km a pé).",
      "Silver Line SL2: hotel (Seaport) ↔ South Station em ~12 min. Tarifa: $2,40.",
      "South Station: hub de Amtrak (NEC, Acela), ônibus (Greyhound, FlixBus, Peter Pan) e MBTA Red Line.",
      "MBTA (The T): $2,40 por viagem. CharlieCard recomendada.",
    ],
    insights: [
      "Logan Airport: um dos mais próximos de hotel em toda a Copa — Silver Line SL1 gratuita do aeroporto direto para o Seaport.",
      "Gillette Stadium fica em Foxborough (55 km ao sul). Commuter Rail de South Station + shuttle FIFA. Verificar serviço especial Copa.",
      "Escala estratégica de 1 noite — prioridade: descanso pós-voo transcontinental de LA.",
      "Fuso: Boston é EDT (UTC -4h). Horário do Brasil: BRT = EDT +1h.",
    ],
  },

  // ── BASE 3 — New Jersey ────────────────────────────────────
  {
    id: "new-jersey",
    emoji: "🗽",
    cidade: "New Jersey",
    periodo: "14–17 jun",
    hotel: "Airbnb (endereço a confirmar)",
    hotelAddr: "New Jersey — endereço a confirmar",
    nota: "Endereço do Airbnb pendente — distâncias são referências a partir de Hoboken Terminal. Consultar deslocamentos da Equipe Alemanha (Hoboken NJ).",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: MetLife Stadium",
    referenciaAddr: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
    routes: [
      {
        destino: "MetLife Stadium (Copa)",
        endereco: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
        carN: "20 min",
        carH: "30–50 min",
        tp: "NJ Transit de Hoboken Terminal ~20 min / $8",
        dist: "~18 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=1+MetLife+Stadium+Dr,+East+Rutherford,+NJ",
      },
      {
        destino: "Newark Intl (EWR)",
        endereco: "Newark Liberty International Airport, NJ",
        carN: "20 min",
        carH: "30–40 min",
        tp: "NJ Transit + AirTrain ~35 min / $14",
        dist: "~15 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Newark+Liberty+International+Airport,+NJ",
      },
      {
        destino: "JFK International",
        endereco: "JFK Airport, Queens, NY",
        carN: "45 min",
        carH: "60–90 min",
        tp: "PATH + LIRR/AirTrain ~70 min / $15",
        dist: "~35 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=JFK+International+Airport,+Queens,+NY",
      },
      {
        destino: "LaGuardia (LGA)",
        endereco: "LaGuardia Airport, East Elmhurst, NY",
        carN: "35 min",
        carH: "50–75 min",
        tp: "PATH + Q70 ônibus ~60 min / $5",
        dist: "~22 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=LaGuardia+Airport,+East+Elmhurst,+NY",
      },
      {
        destino: "Penn Station NYC (Amtrak/NJT)",
        endereco: "Penn Station, New York, NY",
        carN: "20 min",
        carH: "30–50 min",
        tp: "PATH Hoboken → 33rd St ~20 min / $2,10",
        dist: "~8 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "Times Square / Midtown NYC",
        endereco: "Times Square, New York, NY",
        carN: "20 min",
        carH: "35–55 min",
        tp: "PATH Hoboken → 33rd St ~20 min / $2,10",
        dist: "~8 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Times+Square,+New+York,+NY",
      },
      {
        destino: "Hoboken Terminal (PATH/NJT)",
        endereco: "Hudson Pl, Hoboken, NJ 07030",
        carN: "5 min",
        carH: "5 min",
        tp: "A pé ~5 min / $0 (referência)",
        dist: "~0,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Hoboken+Terminal,+Hoboken,+NJ",
      },
    ],
    transitoInfo: [
      "PATH (Port Authority Trans-Hudson): opera 24h. Hoboken Terminal → 33rd St (Midtown): ~20 min / $2,10.",
      "NJ Transit de Hoboken Terminal → MetLife: linha especial em dias de Copa (~20 min / ~$8).",
      "EWR: NJ Transit de Hoboken Terminal → Newark Penn Station (~20 min) + AirTrain (~8 min) = ~30 min / ~$14.",
      "Referência completa: ver deslocamentos Equipe Alemanha (Hoboken NJ) — mesmo modelo.",
    ],
    insights: [
      "Endereço do Airbnb a confirmar — todas as distâncias são aproximações a partir de Hoboken Terminal.",
      "Dias de jogo MetLife: perímetro de segurança FIFA fecha cedo. Sair ANTES das 13h30 em jogos de 16h.",
      "EWR é o aeroporto mais conveniente da área — preferir para voos. JFK e LGA têm Uber mais caro.",
      "PATH opera 24h — frequência de 3–15 min. Sempre mais rápido que carro para NYC no pico.",
      "Fuso: New Jersey é EDT (UTC -4h). Horário do Brasil: BRT = EDT +1h.",
    ],
  },

  // ── BASE 4 — Boston Midtown ────────────────────────────────
  {
    id: "boston-midtown",
    emoji: "🎓",
    cidade: "Boston Midtown",
    periodo: "16–20 jun",
    hotel: "The Midtown Hotel MOD Collection by Sonesta",
    hotelAddr: "220 Huntington Ave, Boston, MA 02115",
    nota: "Isabela Pagliari: check-in 17/06 · Lais Amorim, Dayana Natale, Weverson da Silva, João Pedro Rodrigues: check-in 16/06",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      {
        destino: "Gillette Stadium (Copa)",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "40 min",
        carH: "55–80 min",
        tp: "Commuter Rail Back Bay → Canton Jct + shuttle ~80 min / $15",
        dist: "56 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      {
        destino: "Boston Logan (BOS)",
        endereco: "Logan International Airport, East Boston, MA 02128",
        carN: "20 min",
        carH: "30–45 min",
        tp: "Green E → Orange → Blue Line Airport ~45 min / $2,40",
        dist: "10 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Logan+International+Airport,+East+Boston,+MA",
      },
      {
        destino: "South Station (Amtrak + T)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "15 min",
        carH: "20 min",
        tp: "Green E → Orange Line ~20 min / $2,40",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Back Bay Station (Amtrak)",
        endereco: "145 Dartmouth St, Boston, MA 02116",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé ~8 min / $0",
        dist: "0,6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=145+Dartmouth+St,+Boston,+MA",
      },
      {
        destino: "Symphony Station (T)",
        endereco: "Huntington Ave & Symphony Rd, Boston, MA",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé ~5 min / $0",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Symphony+Station,+Boston,+MA",
      },
      {
        destino: "Fenway Park",
        endereco: "4 Jersey St, Boston, MA 02215",
        carN: "5 min",
        carH: "8 min",
        tp: "MBTA Green D ~8 min / $2,40 ou walk ~20 min",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=4+Jersey+St,+Boston,+MA",
      },
      {
        destino: "Newbury Street",
        endereco: "Newbury St, Boston, MA 02116",
        carN: "8 min",
        carH: "10 min",
        tp: "A pé ~15 min / $0",
        dist: "1,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Newbury+St,+Boston,+MA",
      },
      {
        destino: "Harvard Square",
        endereco: "Harvard Square, Cambridge, MA 02138",
        carN: "15 min",
        carH: "20 min",
        tp: "MBTA Green B/C + Red Line ~25 min / $2,40",
        dist: "7 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Harvard+Square,+Cambridge,+MA",
      },
    ],
    transitoInfo: [
      "Estação mais próxima do hotel: Symphony (Green Line E) — 5 min a pé.",
      "Back Bay Station (Amtrak + Orange Line): 8 min a pé — melhor opção para Gillette (Commuter Rail) e Acela para NYC/Philly.",
      "Até Gillette: Back Bay Station → Commuter Rail Providence/Stoughton Line → Canton Junction → shuttle Copa (~80 min / ~$15). Sair 2h30 antes do jogo.",
      "Até Logan: Green E → Park St → Orange → State → Blue Line Airport. ~45 min / $2,40. Uber ~$25–35.",
      "Tarifa MBTA: $2,40 por viagem. CharlieCard recomendada.",
    ],
    insights: [
      "Back Bay Station está a 8 min a pé — opção mais prática para Amtrak (Acela NYC em ~1h10, Acela Philadelphia em ~1h30).",
      "Gillette em dia de jogo: Commuter Rail Providence/Stoughton Line até Canton Junction + shuttle. Sair pelo menos 2h30 antes.",
      "Acela para Philadelphia de Back Bay: ~1h30. Recomendar reservar com antecedência durante a Copa.",
      "Check-ins divididos: Lais, Dayana, Weverson e João Pedro chegam 16/06; Isa chega 17/06.",
      "Fuso: Boston é EDT (UTC -4h). Horário do Brasil: BRT = EDT +1h.",
    ],
  },

  // ── BASE 5 — Philadelphia ──────────────────────────────────
  {
    id: "philadelphia",
    emoji: "🏛",
    cidade: "Philadelphia",
    periodo: "20–23 jun",
    hotel: "Hilton Garden Inn Philadelphia Center City",
    hotelAddr: "1100 Arch St, Philadelphia, PA 19107",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Lincoln Financial Field",
    referenciaAddr: "One Lincoln Financial Field Way, Philadelphia, PA 19148",
    routes: [
      {
        destino: "Lincoln Financial Field (Copa)",
        endereco: "One Lincoln Financial Field Way, Philadelphia, PA 19148",
        carN: "15 min",
        carH: "20–35 min",
        tp: "SEPTA Broad Street Line City Hall → Pattison ~20 min / $2,50",
        dist: "9 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=One+Lincoln+Financial+Field+Way,+Philadelphia,+PA",
      },
      {
        destino: "Philadelphia Intl (PHL)",
        endereco: "8500 Essington Ave, Philadelphia, PA 19153",
        carN: "20 min",
        carH: "30–45 min",
        tp: "SEPTA Regional Rail R1 de 30th Street Station ~25 min / $6,50",
        dist: "16 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=8500+Essington+Ave,+Philadelphia,+PA",
      },
      {
        destino: "30th Street Station (Amtrak)",
        endereco: "2955 Market St, Philadelphia, PA 19104",
        carN: "10 min",
        carH: "15 min",
        tp: "SEPTA Market-Frankford Line ~15 min / $2,50",
        dist: "4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=2955+Market+St,+Philadelphia,+PA",
      },
      {
        destino: "Penn Station NYC (Amtrak)",
        endereco: "Penn Station, New York, NY 10001",
        carN: "1h10",
        carH: "—",
        tp: "Amtrak Acela ~1h10 / $60–150 | NE Regional ~1h30 / $30–80",
        dist: "155 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "South Station Boston (Amtrak)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "5h30",
        carH: "—",
        tp: "Amtrak NE Regional ~5h30 / $40–120 | Acela ~4h / $80–200",
        dist: "450 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Center City / Reading Terminal Market",
        endereco: "51 N 12th St, Philadelphia, PA 19107",
        carN: "5 min",
        carH: "7 min",
        tp: "A pé ~5 min / $0",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=51+N+12th+St,+Philadelphia,+PA",
      },
      {
        destino: "Independence Hall",
        endereco: "520 Chestnut St, Philadelphia, PA 19106",
        carN: "10 min",
        carH: "12 min",
        tp: "A pé ~15 min / $0",
        dist: "1,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=520+Chestnut+St,+Philadelphia,+PA",
      },
      {
        destino: "Greyhound Philadelphia",
        endereco: "1001 Filbert St, Philadelphia, PA 19107",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé ~10 min / $0",
        dist: "0,7 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=1001+Filbert+St,+Philadelphia,+PA",
      },
    ],
    transitoInfo: [
      "SEPTA Broad Street Line (BSL): estação City Hall a ~5 min a pé do hotel. Até Lincoln Financial: Pattison Station. ~20 min / $2,50. Em dia de jogo: SEPTA opera trens extras.",
      "SEPTA Market-Frankford Line (MFL): passa na Market St — conecta a 30th Street Station e ao aeroporto via R1.",
      "30th Street Station (Amtrak): hub principal do NE Corridor (NYC, BOS, DC, NJ) — a 10 min do hotel.",
      "PHL Airport: SEPTA Regional Rail R1 de 30th Street Station a cada 30 min / $6,50.",
      "Tarifa SEPTA: $2,50 por viagem. SEPTA Key Card recomendada.",
    ],
    insights: [
      "Lincoln Financial Field é o destino mais fácil de toda a Copa para a equipe — SEPTA BSL direta do hotel.",
      "Acela NYC ↔ Philly: conexão rápida (~1h10). Ótima para day-trip ou transferência de equipe para NJ.",
      "Acela Philly → Boston: ~4h. Recomendar reservar antecipado — especialmente durante a Copa.",
      "Segurança: Center City é seguro. Evitar zonas ao sul do estádio à noite em dias de jogo.",
      "Fuso: Philadelphia é EDT (UTC -4h). Horário do Brasil: BRT = EDT +1h.",
    ],
  },

  // ── BASE 6 — Boston Seaport II ─────────────────────────────
  {
    id: "boston-seaport-2",
    emoji: "🐟",
    cidade: "Boston Seaport",
    periodo: "23–28 jun",
    hotel: "Homewood Suites by Hilton Boston Seaport District",
    hotelAddr: "670 Summer St, Boston, MA 02210",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      {
        destino: "Gillette Stadium (Copa)",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "40 min",
        carH: "55–80 min",
        tp: "Commuter Rail de South Station + shuttle ~80 min / $15",
        dist: "55 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      {
        destino: "Boston Logan (BOS) — internacional + doméstico",
        endereco: "Logan International Airport, East Boston, MA 02128",
        carN: "10 min",
        carH: "15 min",
        tp: "Silver Line SL1 gratuito do aeroporto / $2,40 ao aeroporto — ~20 min",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=Logan+International+Airport,+East+Boston,+MA",
      },
      {
        destino: "South Station (Amtrak + Commuter Rail + bus)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "8 min",
        carH: "10 min",
        tp: "Silver Line SL2 ~12 min / $2,40 ou walk ~15 min",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Back Bay Station (Amtrak regional)",
        endereco: "145 Dartmouth St, Boston, MA 02116",
        carN: "15 min",
        carH: "20 min",
        tp: "MBTA Orange Line South Station → Back Bay ~8 min / $2,40",
        dist: "6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=145+Dartmouth+St,+Boston,+MA",
      },
      {
        destino: "Philadelphia (Amtrak)",
        endereco: "30th Street Station, Philadelphia, PA 19104",
        carN: "4h30–6h",
        carH: "—",
        tp: "Amtrak NE Regional de South Station ~5h30 / $40–120 | Acela ~4h / $80–200",
        dist: "450 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=30th+Street+Station,+Philadelphia,+PA",
      },
      {
        destino: "NYC Penn Station (Amtrak)",
        endereco: "Penn Station, New York, NY 10001",
        carN: "3h30",
        carH: "—",
        tp: "Amtrak Acela de South Station ~3h30 / $50–130 | NE Regional ~4h30 / $30–80",
        dist: "340 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "Newark Intl (EWR)",
        endereco: "Newark Liberty International Airport, NJ",
        carN: "3h30",
        carH: "4h30–5h",
        tp: "Amtrak South Station → NYC Penn (~3h30) + NJT + AirTrain / ~$70–160",
        dist: "340 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=Newark+Liberty+International+Airport,+NJ",
      },
      {
        destino: "Convention Center BCEC",
        endereco: "415 Summer St, Boston, MA 02210",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé ~5 min / $0",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=415+Summer+St,+Boston,+MA",
      },
      {
        destino: "Greyhound / FlixBus / Peter Pan Boston",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "8 min",
        carH: "10 min",
        tp: "Silver Line SL2 ~12 min / $2,40 (mesmo terminal que South Station)",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Nova York — I-95 S (carro)",
        endereco: "New York, NY via I-95 S",
        carN: "3h30",
        carH: "4h30–5h30",
        tp: "Amtrak Acela ~3h30 / $50–130 (mais confortável que carro)",
        dist: "345 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=670+Summer+St,+Boston,+MA&daddr=New+York,+NY",
      },
    ],
    transitoInfo: [
      "Silver Line SL1: Logan Airport ↔ South Station direto. Gratuita saindo do aeroporto. Do hotel: Silver Line SL2 até South Station (~12 min) + SL1 para o aeroporto.",
      "South Station: hub central de Boston — Amtrak NEC/Acela, Commuter Rail, Greyhound, FlixBus, Peter Pan e MBTA Red Line.",
      "Commuter Rail para Gillette: serviço especial Foxboro/Copa de South Station em dias de jogo (~80 min / ~$15). Comprar no app MBTA com antecedência.",
      "Homewood Suites fica a 1 quarteirão do Aloft (Base 2) — mesmas referências de distância para o bairro Seaport.",
      "Tarifa MBTA: $2,40 por viagem. CharlieCard recomendada.",
    ],
    insights: [
      "Logan é o melhor aeroporto para voos de Boston — Silver Line gratuita do aeroporto. Opção mais barata e confiável.",
      "Commuter Rail Copa para Gillette: comprar bilhetes antecipados — esgota em dias de jogo do Brasil.",
      "Acela para NYC (~3h30) e Philadelphia (~4h): de South Station. Reservar antecipado durante a Copa.",
      "EWR e JFK: somente se necessário por conexão específica. Amtrak é a melhor opção de acesso a partir de Boston.",
      "Estrada I-95 S para NYC: pedágios estimados $20–30 (E-ZPass recomendado). Evitar sexta-feira 15h–21h.",
      "Fuso: Boston é EDT (UTC -4h). Horário do Brasil: BRT = EDT +1h.",
    ],
  },
];
