import type { CityConfig } from "./types-deslocamentos";

export const POA_CONFIG: CityConfig = {
  id: "poa",
  emoji: "🧉",
  cidade: "Porto Alegre",
  periodo: "Brasileirão",
  contatoLocal: {
    nome: "Douglas Demoliner",
    telefone: "+55 51 8610-2209",
  },
  origins: [
    {
      id: "hotel",
      name: "Hotel Intercity Praia de Belas",
      addr: "Av. Borges de Medeiros, 2145, Praia de Belas, Porto Alegre - RS, 90110-150",
      lat: -30.0453,
      lng: -51.2292,
    },
  ],
  destinations: [
    {
      id: "beira-rio",
      name: "Beira-Rio",
      addr: "Av. Padre Cacique, 891, Praia de Belas, Porto Alegre - RS, 90810-240",
      lat: -30.0656,
      lng: -51.2361,
      category: "estadio",
    },
    {
      id: "salgado-filho",
      name: "Aeroporto Salgado Filho (POA)",
      addr: "Av. Severo Dullius, 90010, Anchieta, Porto Alegre - RS, 90200-310",
      lat: -29.9939,
      lng: -51.1711,
      category: "aeroporto",
    },
    {
      id: "mercado-publico",
      name: "Mercado Público",
      addr: "Largo Jornalista Glênio Peres, 1, Centro, Porto Alegre - RS, 90020-050",
      lat: -30.0275,
      lng: -51.2279,
      category: "ponto_turistico",
    },
    {
      id: "usina-gasometro",
      name: "Usina do Gasômetro",
      addr: "Av. Pres. João Goulart, 551, Marcílio Dias, Porto Alegre - RS, 90010-120",
      lat: -30.0341,
      lng: -51.2411,
      category: "outro",
    },
    {
      id: "parque-farroupilha",
      name: "Parque Farroupilha (Redenção)",
      addr: "Av. João Pessoa, s/n, Porto Alegre - RS, 90040-000",
      lat: -30.0367,
      lng: -51.2158,
      category: "outro",
    },
    {
      id: "parque-marinha",
      name: "Parque Marinha do Brasil",
      addr: "Av. Borges de Medeiros, 2035, Porto Alegre - RS, 90110-150",
      lat: -30.0569,
      lng: -51.2322,
      category: "outro",
    },
  ],
  routes: [
    {
      from: "hotel",
      to: "beira-rio",
      carN: "5–8 min",
      carH: "20–40 min",
      tp: "Ônibus municipais; sem metrô/Trensurb próximo",
      dist: "2,5 km",
      diff: "dificil",
      costCar: "~R$3",
      costTp: "~R$5,50",
      note: "Av. Edvaldo Pereira Paiva vira mão única em dia de jogo — chegar 2–3h antes",
    },
    {
      from: "hotel",
      to: "salgado-filho",
      carN: "15–20 min",
      carH: "30–40 min",
      tp: "Trensurb via Estação Mercado ~35–45 min",
      dist: "9–10 km",
      diff: "moderado",
      costCar: "~R$14",
      costTp: "~R$5,50",
      note: "Aeromóvel do aeroporto inoperante desde as enchentes de 2024",
    },
    {
      from: "hotel",
      to: "mercado-publico",
      carN: "10–15 min",
      carH: "20–30 min",
      tp: "Estação Mercado do Trensurb bem ao lado",
      dist: "4–5 km",
      diff: "facil",
      costCar: "~R$6",
      costTp: "~R$5,50",
    },
    {
      from: "hotel",
      to: "usina-gasometro",
      carN: "10–15 min",
      carH: "20–30 min",
      tp: "Ônibus; sem metrô próximo",
      dist: "3,5–4 km",
      diff: "facil",
      costCar: "~R$5",
      costTp: "~R$5,50",
    },
    {
      from: "hotel",
      to: "parque-farroupilha",
      carN: "10–15 min",
      carH: "20–25 min",
      tp: "Ônibus",
      dist: "3,5 km",
      diff: "facil",
      costCar: "~R$5",
      costTp: "~R$5,50",
    },
    {
      from: "hotel",
      to: "parque-marinha",
      carN: "3–5 min",
      carH: "3–5 min",
      tp: "Caminhável",
      dist: "1,3 km",
      diff: "facil",
      costCar: "~R$3",
      costTp: "Caminhável",
    },
  ],
  alerts: [
    {
      category: "estadio",
      text: "Av. Edvaldo Pereira Paiva vira mão única em dia de jogo no Beira-Rio — a EPTC recomenda chegar 2–3h antes.",
    },
    {
      category: "aeroporto",
      text: "Aeromóvel do aeroporto está inoperante desde as enchentes de maio/2024 — usar Trensurb via Estação Mercado.",
    },
    {
      category: "transito",
      text: "Poucas pontes concentram o tráfego entre os bairros — a cidade tem topografia de quase-ilha entre o Guaíba e seus canais.",
    },
    {
      category: "geral",
      text: "A enchente histórica de maio/2024 ainda deixa sequelas em parte da infraestrutura de transporte.",
    },
    {
      category: "seguranca",
      text: "Centro Histórico esvazia à noite fora de dias de evento — evite caminhar sozinho após o horário comercial, priorize app/carro para deslocamentos noturnos.",
    },
  ],
};
