export type Difficulty = "facil" | "moderado" | "dificil";

export interface FrancaRoute {
  destino: string;
  endereco: string;
  carN: string;
  carH: string;
  tp: string;
  dist: string;
  diff: Difficulty;
  mapsUrl: string;
}

export interface FrancaBase {
  id: string;
  emoji: string;
  cidade: string;
  periodo: string;
  hotel: string;
  hotelAddr: string;
  nota?: string;
  referenciaLabel?: string;
  referenciaAddr?: string;
  routes: FrancaRoute[];
  transitoInfo?: string[];
  insights: string[];
}

export const FRANCA_BASES: FrancaBase[] = [
  // ── Los Angeles ────────────────────────────────────────────
  {
    id: "los-angeles",
    emoji: "🌴",
    cidade: "Los Angeles",
    periodo: "09–13 jun",
    hotel: "The O Hotel, Trademark Collection by Wyndham",
    hotelAddr: "819 S Flower St, Los Angeles, CA 90017",
    referenciaLabel: "Estádio Copa: SoFi Stadium",
    referenciaAddr: "1001 Stadium Dr, Inglewood, CA 90305",
    routes: [
      {
        destino: "SoFi Stadium (Copa)",
        endereco: "1001 Stadium Dr, Inglewood, CA 90305",
        carN: "25 min",
        carH: "40–55 min",
        tp: "Metro A Line → Hawthorne/Lennox + shuttle ~35 min / $2,50",
        dist: "16 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+S+Flower+St,+Los+Angeles,+CA&daddr=1001+Stadium+Dr,+Inglewood,+CA",
      },
      {
        destino: "LAX Airport",
        endereco: "1 World Way, Los Angeles, CA 90045",
        carN: "25 min",
        carH: "45–70 min",
        tp: "Metro A Line → Aviation/LAX + shuttle grátis ~35 min / $2,50",
        dist: "23 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+S+Flower+St,+Los+Angeles,+CA&daddr=1+World+Way,+Los+Angeles,+CA",
      },
      {
        destino: "Union Station (Amtrak/hub)",
        endereco: "800 N Alameda St, Los Angeles, CA 90012",
        carN: "8 min",
        carH: "12 min",
        tp: "Metro B Line ou walk ~25 min / $2,50",
        dist: "3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+S+Flower+St,+Los+Angeles,+CA&daddr=800+N+Alameda+St,+Los+Angeles,+CA",
      },
      {
        destino: "Hollywood / Walk of Fame",
        endereco: "6925 Hollywood Blvd, Los Angeles, CA 90028",
        carN: "20 min",
        carH: "35–60 min",
        tp: "Metro B Line (Red) 7th/Metro → Hollywood/Highland ~20 min / $2,50",
        dist: "15 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+S+Flower+St,+Los+Angeles,+CA&daddr=6925+Hollywood+Blvd,+Los+Angeles,+CA",
      },
      {
        destino: "Crypto.com Arena",
        endereco: "1111 S Figueroa St, Los Angeles, CA 90015",
        carN: "5 min",
        carH: "8 min",
        tp: "Walk ~20 min / $0",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+S+Flower+St,+Los+Angeles,+CA&daddr=1111+S+Figueroa+St,+Los+Angeles,+CA",
      },
      {
        destino: "Santa Monica Pier",
        endereco: "200 Santa Monica Pier, Santa Monica, CA 90401",
        carN: "30 min",
        carH: "60–90 min",
        tp: "Metro E Line (Expo) 7th/Metro → Downtown Santa Monica ~55 min / $2,50",
        dist: "25 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=819+S+Flower+St,+Los+Angeles,+CA&daddr=200+Santa+Monica+Pier,+Santa+Monica,+CA",
      },
      {
        destino: "Griffith Observatory",
        endereco: "2800 E Observatory Rd, Los Angeles, CA 90027",
        carN: "20 min",
        carH: "35–50 min",
        tp: "Metro B Line → Vermont/Sunset + ônibus 204 ~40 min / $2,50",
        dist: "14 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=819+S+Flower+St,+Los+Angeles,+CA&daddr=2800+E+Observatory+Rd,+Los+Angeles,+CA",
      },
    ],
    transitoInfo: [
      "Hub de metrô mais próximo do hotel: 7th Street/Metro Center (3 min a pé) — conecta linhas A, B, D, E.",
      "SoFi Stadium: Metro A Line até Hawthorne/Lennox + shuttle FIFA em dias de jogo (~5 min). Sem carro recomendado em dia de jogo.",
      "LAX: Metro A Line até Aviation/LAX Station + LAX-it Shuttle gratuito. Tempo total ~35 min. Uber: ~25 min sem trânsito (~$35–55).",
      "Tarifa Metro LA: $2,50 por viagem (TAP card recomendado). Day pass: $7.",
      "Trânsito LA: I-10 e I-405 são os maiores gargalos. Pico: 7h–10h e 16h–19h. SoFi em dias de jogo: adicionar 30–60 min.",
    ],
    insights: [
      "SoFi Stadium em dias de jogo: perímetro FIFA fecha 3h antes. Sair do hotel ANTES das 13h em jogos de 16h.",
      "LAX é o aeroporto principal — internacional e doméstico. Sem alternativa regional próxima.",
      "Uber/Lyft amplamente disponíveis em LA. Média $25–55 para SoFi, $35–55 para LAX.",
      "Trânsito LA é imprevisível. Sempre calcular 1h extra em horário de pico.",
      "Hollywood e Griffith: ótimas locações para gravações — agendar com 2h de folga para deslocamento em dia de trânsito.",
      "Estacionamento em Downtown LA: ~$20–40/dia. Recomendado usar Metro ou Uber.",
    ],
  },

  // ── Boston I — Seaport (escala) ────────────────────────────
  {
    id: "boston-seaport-1",
    emoji: "🦞",
    cidade: "Boston I",
    periodo: "13–14 jun",
    hotel: "Aloft Boston Seaport District by Marriott",
    hotelAddr: "401 D St, Boston, MA 02210",
    nota: "Escala de 1 noite — trânsito entre LA e NJ",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      {
        destino: "Logan Airport (BOS)",
        endereco: "1 Harborside Dr, East Boston, MA 02128",
        carN: "12 min",
        carH: "25–35 min",
        tp: "Silver Line SL1 → South Station → walk ~25 min / $2,90 (grátis do aeroporto)",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=1+Harborside+Dr,+East+Boston,+MA",
      },
      {
        destino: "South Station (Amtrak/bus)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "8 min",
        carH: "12 min",
        tp: "Silver Line SL2 ~5 min / $2,90 ou walk ~20 min",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "New Jersey (próximo destino — I-95 S)",
        endereco: "New Jersey via I-95 S",
        carN: "3h30",
        carH: "4h30–5h",
        tp: "Amtrak South Station → Penn Station NYC ~4h / $50–120; depois NJ Transit",
        dist: "350 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=New+Jersey,+USA",
      },
      {
        destino: "Gillette Stadium (Copa)",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "45 min",
        carH: "70–90 min",
        tp: "Trem especial Foxboro de South Station em dias de jogo ~45 min / ~$15",
        dist: "50 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      {
        destino: "Downtown Boston",
        endereco: "Downtown Boston, MA",
        carN: "8 min",
        carH: "15 min",
        tp: "Silver Line SL2 ~8 min / $2,90",
        dist: "3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=401+D+St,+Boston,+MA&daddr=Downtown+Boston,+MA",
      },
    ],
    transitoInfo: [
      "Silver Line SL1: conecta Logan Airport → South Station diretamente. Gratuita partindo do aeroporto.",
      "Silver Line SL2: Seaport District ↔ South Station (~5 min). Tarifa: $2,90.",
      "South Station: hub de Amtrak (NEC, Acela), ônibus (Greyhound, FlixBus, Peter Pan) e MBTA.",
      "MBTA (The T): tarifa única $2,90 por viagem. CharlieCard recomendado.",
    ],
    insights: [
      "Escala estratégica — 1 noite. Prioridade: descanso pós-voo transcontinental de LA.",
      "Logan Airport: serviço Silver Line gratuito do aeroporto. Sem Uber necessário para check-in.",
      "Amtrak Acela (South Station → NYC Penn): $80–150, ~3h30. Opção mais confortável para NJ.",
      "Táxi/Uber do hotel a South Station: ~$12–15, 8 min sem trânsito.",
    ],
  },

  // ── New Jersey ─────────────────────────────────────────────
  {
    id: "new-jersey",
    emoji: "🗽",
    cidade: "New Jersey",
    periodo: "14–17 jun",
    hotel: "Airbnb (endereço a confirmar)",
    hotelAddr: "New Jersey (a confirmar)",
    nota: "Endereço do Airbnb pendente — links Maps calculados a partir de Hoboken Terminal",
    referenciaLabel: "Estádio Copa: MetLife Stadium",
    referenciaAddr: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
    routes: [
      {
        destino: "MetLife Stadium (Copa)",
        endereco: "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
        carN: "20 min",
        carH: "30–50 min",
        tp: "NJ Transit de Hoboken Terminal ~25 min / $8",
        dist: "18 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=1+MetLife+Stadium+Dr,+East+Rutherford,+NJ",
      },
      {
        destino: "Times Square / Midtown NYC",
        endereco: "Times Square, New York, NY 10036",
        carN: "20 min",
        carH: "35–55 min",
        tp: "PATH de Hoboken → 33rd St ~20 min / $2,10",
        dist: "8 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Times+Square,+New+York,+NY",
      },
      {
        destino: "Penn Station NYC (Amtrak/NJT)",
        endereco: "31 W 31st St, New York, NY 10001",
        carN: "20 min",
        carH: "30–50 min",
        tp: "PATH Hoboken → 33rd St ~20 min / $2,10",
        dist: "8 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "Newark Intl (EWR)",
        endereco: "3 Brewster Rd, Newark, NJ 07114",
        carN: "20 min",
        carH: "30–40 min",
        tp: "NJ Transit + AirTrain ~35 min / $14",
        dist: "15 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Newark+Liberty+International+Airport,+NJ",
      },
      {
        destino: "JFK International",
        endereco: "JFK Airport, Queens, NY",
        carN: "45 min",
        carH: "60–90 min",
        tp: "PATH + LIRR/AirTrain ~70 min / $15",
        dist: "35 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=JFK+International+Airport,+Queens,+NY",
      },
      {
        destino: "LaGuardia (LGA)",
        endereco: "LaGuardia Airport, East Elmhurst, NY",
        carN: "35 min",
        carH: "50–80 min",
        tp: "PATH + Q70 ônibus ~60 min / $5",
        dist: "22 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=LaGuardia+Airport,+East+Elmhurst,+NY",
      },
      {
        destino: "Hoboken Terminal (PATH/NJT)",
        endereco: "Hudson Pl, Hoboken, NJ 07030",
        carN: "5 min",
        carH: "5 min",
        tp: "A pé ~5 min / $0",
        dist: "0,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Hoboken+Terminal,+Hoboken,+NJ",
      },
      {
        destino: "Boston (próximo destino — I-95 N)",
        endereco: "Boston, MA via I-95 N",
        carN: "3h30",
        carH: "4h30–5h",
        tp: "Amtrak Penn Station NYC → South Station Boston ~4h / $50–130",
        dist: "350 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=Hoboken+Terminal,+Hoboken,+NJ&daddr=Boston,+MA",
      },
    ],
    transitoInfo: [
      "PATH (Port Authority Trans-Hudson): opera 24h. Hoboken Terminal → 33rd St (Midtown): ~20 min / $2,10.",
      "NJ Transit de Hoboken Terminal → MetLife: linha específica em dias de Copa (~25 min / ~$8).",
      "EWR: NJ Transit de Hoboken Terminal → Newark Penn Station (~20 min) + AirTrain (~8 min) = ~30 min total / ~$14.",
      "Uber de NJ para NYC: ~$25–45 dependendo do horário e travessia (Lincoln Tunnel).",
    ],
    insights: [
      "Endereço do Airbnb pendente — confirmar e atualizar links Maps. Rotas calculadas a partir de Hoboken Terminal.",
      "Dias de jogo MetLife: perímetro de segurança FIFA fecha às 14h. Sair ANTES das 13h30.",
      "EWR é o aeroporto mais conveniente da NJ — preferir para voos. JFK e LGA custam mais de Uber.",
      "PATH opera 24h, frequência de 3–15 min. É sempre mais rápido que carro para NYC no pico.",
      "Túnel Lincoln: gargalo para NYC de carro. Pico 7h–9h e 16h–19h — adicionar 30–60 min.",
    ],
  },

  // ── Boston II — Back Bay / Midtown ─────────────────────────
  {
    id: "boston-midtown",
    emoji: "🎭",
    cidade: "Boston II",
    periodo: "16–20 jun",
    hotel: "The Midtown Hotel MOD Collection by Sonesta",
    hotelAddr: "220 Huntington Ave, Boston, MA 02115",
    nota: "Isa Pagliari: check-in 17/06 · Lais Amorim, Dayana Natale, Weverson da Silva, João Pedro Rodrigues: check-in 16/06",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      {
        destino: "Gillette Stadium (Copa)",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "45 min",
        carH: "65–90 min",
        tp: "Trem Commuter Rail Back Bay → Foxboro ~45 min dia de jogo / ~$20",
        dist: "50 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      {
        destino: "Back Bay Station (Amtrak)",
        endereco: "145 Dartmouth St, Boston, MA 02116",
        carN: "5 min",
        carH: "5 min",
        tp: "Walk ~5 min / $0",
        dist: "0,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=145+Dartmouth+St,+Boston,+MA",
      },
      {
        destino: "Logan Airport (BOS)",
        endereco: "1 Harborside Dr, East Boston, MA 02128",
        carN: "20 min",
        carH: "35–50 min",
        tp: "MBTA Green Line → Park St → Blue Line → Airport ~35 min / $2,90",
        dist: "9 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=1+Harborside+Dr,+East+Boston,+MA",
      },
      {
        destino: "Fenway Park",
        endereco: "4 Jersey St, Boston, MA 02215",
        carN: "8 min",
        carH: "12 min",
        tp: "MBTA Green Line B/C/D de Hynes →Kenmore ~5 min / $2,90 ou walk ~20 min",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=4+Jersey+St,+Boston,+MA",
      },
      {
        destino: "TD Garden",
        endereco: "100 Legends Way, Boston, MA 02114",
        carN: "12 min",
        carH: "20 min",
        tp: "MBTA Green/Orange Line ~20 min / $2,90",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=100+Legends+Way,+Boston,+MA",
      },
      {
        destino: "South Station (Amtrak/bus)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "12 min",
        carH: "18 min",
        tp: "MBTA Green → Park St → Red Line → South Station ~15 min / $2,90",
        dist: "4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Harvard Square",
        endereco: "Harvard Square, Cambridge, MA 02138",
        carN: "15 min",
        carH: "25 min",
        tp: "Drive via Storrow Dr ou MBTA Red Line ~25 min / $2,90",
        dist: "8 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Harvard+Square,+Cambridge,+MA",
      },
    ],
    transitoInfo: [
      "MBTA Green Line: estação mais próxima do hotel é Hynes Convention Center (2 min a pé).",
      "Back Bay Station (Amtrak + Commuter Rail): a 5 min a pé — melhor opção para Gillette em dias de jogo.",
      "Gillette Stadium: Commuter Rail especial de Back Bay/South Station em dias de Copa. Comprar bilhete com antecedência.",
      "Tarifa MBTA (The T): $2,90 por viagem. CharlieCard recomendada. Diária não existe — considerar passe semanal.",
      "Hynes Convention Center → Airport: Green Line até Park Street, depois Orange Line até State, depois Blue Line até Airport. ~35–40 min.",
    ],
    insights: [
      "Back Bay é o bairro com melhor localização de Boston: próximo a Copley Square, Fenway Park e Back Bay Station.",
      "Gillette Stadium (Foxborough): em dias de Copa, usar Commuter Rail — estacionamento no venue é complexo e caro.",
      "Logan Airport: Silver Line de South Station é a opção mais simples. De Back Bay: trem até South Station + Silver Line SL1.",
      "Uber/Lyft em Boston: $20–35 para o aeroporto, ~$60–80 para Gillette. Preço sobe 2–3× em dias de jogo.",
      "Check-ins divididos: Lais, Dayana, Weverson e João Pedro chegam 16/06; Isa chega 17/06 (vindos de NJ).",
    ],
  },

  // ── Philadelphia ───────────────────────────────────────────
  {
    id: "philadelphia",
    emoji: "🔔",
    cidade: "Philadelphia",
    periodo: "20–23 jun",
    hotel: "Hilton Garden Inn Philadelphia Center City",
    hotelAddr: "1100 Arch St, Philadelphia, PA 19107",
    referenciaLabel: "Estádio Copa: Lincoln Financial Field",
    referenciaAddr: "1 Lincoln Financial Field Way, Philadelphia, PA 19148",
    routes: [
      {
        destino: "Lincoln Financial Field (Copa)",
        endereco: "1 Lincoln Financial Field Way, Philadelphia, PA 19148",
        carN: "20 min",
        carH: "35 min",
        tp: "SEPTA Broad Street Line (BSL) City Hall → Pattison ~20 min / $2,50",
        dist: "10 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=1+Lincoln+Financial+Field+Way,+Philadelphia,+PA",
      },
      {
        destino: "Philadelphia Intl Airport (PHL)",
        endereco: "8000 Essington Ave, Philadelphia, PA 19153",
        carN: "25 min",
        carH: "40 min",
        tp: "SEPTA Regional Rail R1 de 30th Street Station ~25 min / $7",
        dist: "18 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=8000+Essington+Ave,+Philadelphia,+PA",
      },
      {
        destino: "30th Street Station (Amtrak)",
        endereco: "2955 Market St, Philadelphia, PA 19104",
        carN: "10 min",
        carH: "15 min",
        tp: "SEPTA MFL Market St → 30th Street ~12 min / $2,50",
        dist: "4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=2955+Market+St,+Philadelphia,+PA",
      },
      {
        destino: "Liberty Bell / Old City",
        endereco: "526 Market St, Philadelphia, PA 19106",
        carN: "8 min",
        carH: "12 min",
        tp: "SEPTA MFL → 5th Street ~5 min ou walk ~25 min / $2,50",
        dist: "3 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=526+Market+St,+Philadelphia,+PA",
      },
      {
        destino: "Penn Station NYC (via Amtrak)",
        endereco: "Penn Station, New York, NY 10001",
        carN: "1h40",
        carH: "2h15",
        tp: "Amtrak Acela de 30th Street Station ~1h15 / $70–150",
        dist: "150 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=Penn+Station,+New+York,+NY",
      },
      {
        destino: "Newark Intl (EWR)",
        endereco: "3 Brewster Rd, Newark, NJ 07114",
        carN: "1h25",
        carH: "2h",
        tp: "Amtrak 30th St → Newark Penn (~55 min) + AirTrain (~8 min) / $40–80",
        dist: "120 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=Newark+Liberty+International+Airport,+NJ",
      },
      {
        destino: "Boston (próximo destino — I-95 N)",
        endereco: "Boston, MA via I-95 N",
        carN: "5h30",
        carH: "7h+",
        tp: "Amtrak Acela de 30th Street Station ~5h / $80–160",
        dist: "480 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=1100+Arch+St,+Philadelphia,+PA&daddr=Boston,+MA",
      },
    ],
    transitoInfo: [
      "SEPTA BSL (Broad Street Line): estação mais próxima City Hall (5 min a pé). Até Lincoln Financial: Pattison Station. ~20 min / $2,50.",
      "SEPTA MFL (Market-Frankford Line): passa na Arch St (estação 8th/Market). Conecta a 30th Street Station e aeroporto via R1.",
      "30th Street Station (Amtrak): hub principal — Northeast Corridor (NYC, BOS, DC). 10 min do hotel.",
      "PHL Airport: SEPTA R1 de 30th Street Station. Comprar bilhete antecipado — trens a cada 30 min.",
      "Tarifa SEPTA: $2,50 por viagem. Key Card recomendada. Diária: $9.",
    ],
    insights: [
      "Lincoln Financial Field em dias de Copa: perímetro de segurança FDA fecha cedo. Usar SEPTA BSL — evitar carro.",
      "Amtrak Acela: opção mais rápida e confortável para NYC ($70–150, ~1h15) e Boston (~5h).",
      "PHL é aeroporto internacional bem conectado. Alternativa: EWR (1h25 de carro) para mais voos internacionais.",
      "Philadelphia Center City: fácil de navegar a pé. Liberty Bell, Reading Terminal Market a menos de 10 min.",
      "Uber/Lyft em Philly: $20–30 para Lincoln Financial, $30–40 para aeroporto. Aumenta 2–3× em dias de jogo.",
    ],
  },

  // ── Boston III — Seaport (final) ───────────────────────────
  {
    id: "boston-seaport-2",
    emoji: "⚓",
    cidade: "Boston III",
    periodo: "23–28 jun",
    hotel: "Homewood Suites by Hilton Boston Seaport District",
    hotelAddr: "133 Seaport Blvd, Boston, MA 02210",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      // ── Estádio ──
      {
        destino: "Gillette Stadium (Copa)",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "45 min",
        carH: "70–90 min",
        tp: "Commuter Rail de South Station → Foxboro ~45 min dia de jogo / ~$15–20",
        dist: "50 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      // ── Aeroportos ──
      {
        destino: "Logan Airport (BOS) — internacional + doméstico",
        endereco: "1 Harborside Dr, East Boston, MA 02128",
        carN: "12 min",
        carH: "25–35 min",
        tp: "Silver Line SL1 de South Station → Logan ~20 min / $2,90 (grátis do aeroporto)",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=Logan+Airport,+East+Boston,+MA",
      },
      {
        destino: "Providence/TF Green Airport (PVD)",
        endereco: "2000 Post Rd, Warwick, RI 02886",
        carN: "1h",
        carH: "1h30",
        tp: "Amtrak South Station → Providence (~30 min) + Uber (~10 min) / ~$30 + $20",
        dist: "90 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=2000+Post+Rd,+Warwick,+RI",
      },
      {
        destino: "Manchester-Boston Regional (MHT)",
        endereco: "1 Airport Dr, Manchester, NH 03103",
        carN: "1h15",
        carH: "1h45",
        tp: "Sem trem direto — carro ou Uber ~$80–120",
        dist: "100 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=1+Airport+Dr,+Manchester,+NH",
      },
      {
        destino: "Newark Intl (EWR)",
        endereco: "3 Brewster Rd, Newark, NJ 07114",
        carN: "3h30",
        carH: "4h30–5h",
        tp: "Amtrak South Station → NYC Penn Station (~3h30) + NJT + AirTrain / $60–150",
        dist: "340 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=Newark+Liberty+International+Airport,+NJ",
      },
      {
        destino: "JFK International",
        endereco: "JFK Airport, Queens, NY",
        carN: "3h30",
        carH: "4h30–5h",
        tp: "Amtrak South Station → NYC Penn (~3h30) + LIRR + AirTrain / $60–150",
        dist: "335 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=JFK+International+Airport,+Queens,+NY",
      },
      // ── Estações de trem ──
      {
        destino: "South Station (Amtrak + Commuter Rail + bus)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "6 min",
        carH: "10 min",
        tp: "Silver Line SL2 ~5 min / $2,90 ou walk ~15 min",
        dist: "1,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Back Bay Station (Amtrak regional)",
        endereco: "145 Dartmouth St, Boston, MA 02116",
        carN: "12 min",
        carH: "20 min",
        tp: "MBTA Orange Line South Station → Back Bay ~8 min / $2,90",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=145+Dartmouth+St,+Boston,+MA",
      },
      {
        destino: "North Station (Amtrak + MBTA Commuter Rail)",
        endereco: "135 Causeway St, Boston, MA 02114",
        carN: "12 min",
        carH: "20 min",
        tp: "MBTA Orange Line South Station → North Station ~10 min / $2,90",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=135+Causeway+St,+Boston,+MA",
      },
      // ── Terminal de ônibus ──
      {
        destino: "South Station Bus Terminal (Greyhound / FlixBus / Peter Pan)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "6 min",
        carH: "10 min",
        tp: "Silver Line SL2 ~5 min / $2,90 ou walk ~15 min",
        dist: "1,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      // ── Carro / saída da cidade ──
      {
        destino: "Nova York — I-95 S (carro)",
        endereco: "New York, NY via I-95 S",
        carN: "3h30",
        carH: "4h30–5h30",
        tp: "Amtrak South Station → Penn Station NYC ~3h30–4h / $50–150",
        dist: "345 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=New+York,+NY",
      },
      {
        destino: "Philadelphia — I-95 S (carro)",
        endereco: "Philadelphia, PA via I-95 S",
        carN: "5h30",
        carH: "7h+",
        tp: "Amtrak South Station → 30th Street Philly ~5h / $70–160",
        dist: "480 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=133+Seaport+Blvd,+Boston,+MA&daddr=Philadelphia,+PA",
      },
    ],
    transitoInfo: [
      "Silver Line SL1: Logan Airport ↔ South Station direto. Grátis DO aeroporto. De volta: $2,90.",
      "Silver Line SL2: hotel (Seaport) ↔ South Station em ~5 min. Principal ligação do Seaport com o MBTA.",
      "South Station: hub central de Boston — Amtrak NEC/Acela, Commuter Rail, Greyhound, FlixBus, Peter Pan, MBTA Red Line.",
      "Commuter Rail para Gillette: serviço especial Foxboro Line saindo de South Station em dias de Copa (~45 min / ~$15–20). Bilhete no app MBTA.",
      "MBTA tarifas: metrô/Silver Line $2,90 / Commuter Rail Zona 3+ (Foxborough) ~$15–20 / CharlieCard recomendada.",
    ],
    insights: [
      "Logan é o melhor aeroporto para voos de Boston — internacional e doméstico. Silver Line é a opção mais rápida e barata.",
      "PVD (Providence): alternativa a BOS para voos internacionais. Uber do hotel direto: ~$70–90.",
      "MHT (Manchester NH): aeroporto mais tranquilo para voos domésticos nos EUA. Sem TP — carro ou Uber (~$80–110).",
      "EWR e JFK: somente se necessário por conexão específica. Amtrak NEC é a melhor opção de acesso.",
      "Commuter Rail Copa: comprar bilhetes antecipados — esgota em dias de jogo do Brasil.",
      "Uber/Lyft em Boston: $25–35 para aeroporto (sem trânsito), $60–90 para Gillette. Silver Line sempre mais barato.",
      "Estrada I-95 S para NYC: peaje estimado $20–30 (E-ZPass recomendado). Evitar sexta 15h–21h — engarrafamento histórico.",
    ],
  },
];
