import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type InglaterraLocPermit = "none" | "film_office" | "venue_specific";

export const INGLATERRA_LOC_PERMIT_LABEL: Record<
  InglaterraLocPermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",           tone: "green"  },
  film_office:    { label: "Film Office local",    tone: "amber"  },
  venue_specific: { label: "Negociar com o local", tone: "orange" },
};

export interface InglaterraVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade: "dallas" | "houston" | "new-jersey" | "kansas-city";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: InglaterraLocPermit;
  permitNote?: string;
  tips: string;
}

export const INGLATERRA_VENUES: InglaterraVenueItem[] = [

  // ── Dallas TX · 11–18 jun ─────────────────────────────────────
  {
    id: "dal-reunion-tower",
    name: "Reunion Tower GeO-Deck",
    category: "observatory",
    address: "300 Reunion Blvd E, Dallas, TX 75207",
    area: "West End / Downtown",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "11–18 jun",
    rating: 4.6,
    reviewCount: "32.000+",
    hours: "Dom–Qui 11h–21h · Sex–Sáb 11h–22h (última subida 1h antes do fechamento)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Adulto: ~$26. Desconto online. Verificar promoções Copa.",
    permit: "venue_specific",
    permitNote: "Contato com Hyatt/Reunion Tower Events para filmagem comercial.",
    tips:
      "O miradouro mais icônico de Dallas — vista 360° do skyline completo. A 5 min de carro da referência Downtown. Imprescindível para aberturas e créditos com skyline de Dallas. À noite, a esfera luminosa é um backdrop inconfundível. Reservar com antecedência em semanas de jogo.",
  },
  {
    id: "dal-klyde-warren",
    name: "Klyde Warren Park",
    category: "park",
    address: "2012 Woodall Rodgers Fwy, Dallas, TX 75201",
    area: "Arts District / Downtown",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "11–18 jun",
    rating: 4.7,
    reviewCount: "28.000+",
    hours: "Seg–Qui 06h–22h · Sex–Sáb 06h–23h · Dom 06h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Dallas Film Commission (filmdallas.com) para filmagem comercial no parque.",
    tips:
      "Parque suspenso sobre a freeway com gramado, food trucks e eventos frequentes — coração verde do Downtown Dallas. A 10 min a pé da referência Downtown. Espaço ideal para externas descontraídas e entrevistas ao ar livre. Durante a Copa, provável ponto de encontro de torcedores.",
  },
  {
    id: "dal-monarch-rooftop",
    name: "Monarch — Virgin Hotels Dallas",
    category: "rooftop",
    address: "1445 Turtle Creek Blvd, Dallas, TX 75207",
    area: "Turtle Creek / Uptown",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "11–18 jun",
    rating: 4.5,
    reviewCount: "4.100+",
    hours: "Ter–Qui 17h–00h · Sex 17h–01h · Sáb 14h–01h · Dom 14h–22h",
    goodDay: "no",
    goodNight: "yes",
    cost: "$$$",
    costNote: "Consumação mínima; reserva necessária. Tarifa editorial a negociar.",
    permit: "venue_specific",
    permitNote: "Negociar com gerência de eventos do Virgin Hotels Dallas.",
    tips:
      "Rooftop exclusivo com vista para o skyline de Dallas e piscina — referência de sofisticação no Uptown. A 10 min de carro da referência Downtown. Perfeito para entrevistas VIP ou entradas ao vivo noturnas com backdrop urbano de alta qualidade. Reservar com antecedência.",
  },
  {
    id: "dal-texas-de-brazil",
    name: "Texas de Brazil Dallas",
    category: "brazilian",
    address: "2727 Cedar Springs Rd, Dallas, TX 75201",
    area: "Cedar Springs / Uptown",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "11–18 jun",
    rating: 4.5,
    reviewCount: "9.400+",
    hours: "Seg–Sex 11h30–22h · Sáb 11h30–22h30 · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência do restaurante para autorização editorial.",
    tips:
      "Rodízio de churrasco brasileiro premium no Uptown — espaço amplo e decoração que remete ao Brasil. A 8 min de carro da referência Downtown. Ótimo para gravações gastronômicas e encontros com a torcida brasileira em Dallas. Reservar com antecedência para grupos.",
  },
  {
    id: "dal-the-rustic",
    name: "The Rustic Dallas",
    category: "sports_bar",
    address: "3656 Howell St, Dallas, TX 75204",
    area: "Uptown / Knox-Henderson",
    cidade: "dallas",
    cidadeLabel: "Dallas TX",
    periodo: "11–18 jun",
    rating: 4.4,
    reviewCount: "14.000+",
    hours: "Seg–Qui 11h–00h · Sex 11h–02h · Sáb 10h–02h · Dom 10h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    costNote: "Entrada gratuita; consumação à parte.",
    permit: "film_office",
    permitNote: "Dallas Film Commission para externas na área pública adjacente.",
    tips:
      "Bar e espaço ao ar livre com palco, telões e ambiente country-urbano — ponto de encontro de locais em dias de jogo. A 10 min de carro da referência Downtown. Telões e espaço externo amplo criam atmosfera de torcida. Verificar programação de Copa no site antes do dia de cobertura.",
  },

  // ── Houston TX · 18–20 jun ───────────────────────────────────
  {
    id: "hou-post-houston",
    name: "POST Houston — Skylawn Rooftop",
    category: "rooftop",
    address: "401 Franklin St, Houston, TX 77002",
    area: "Downtown Houston",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "18–20 jun",
    rating: 4.5,
    reviewCount: "5.000+",
    hours: "Qui–Sáb 17h–00h · Dom 12h–20h (verificar agenda de eventos)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$",
    costNote: "Acesso ao Skylawn gratuito em horários sem evento; taxa em dias de show.",
    permit: "film_office",
    permitNote: "Houston Film Commission (houstonfilmcommission.com) para filmagem comercial.",
    tips:
      "Antigo correio federal transformado em complexo cultural — Skylawn no topo com vista do skyline de Houston. A 8 min de carro do hotel. Alta versatilidade para entradas ao vivo. Confirmar programação antes: venue para eventos pode ter acesso restrito em fins de semana.",
  },
  {
    id: "hou-discovery-green",
    name: "Discovery Green",
    category: "park",
    address: "1500 McKinney St, Houston, TX 77010",
    area: "Downtown / Convention Center",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "18–20 jun",
    rating: 4.7,
    reviewCount: "20.000+",
    hours: "Seg–Dom 06h–23h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Houston Film Commission para filmagem comercial no parque.",
    tips:
      "Parque urbano a 5 min a pé do hotel — ponto de encontro da comunidade no Downtown Houston. Palco ao ar livre, lago artificial e alto tráfego de pedestres. Ideal para entrevistas externas e captação de atmosfera local. Transmissão dos jogos da Copa durante a Copa a confirmar.",
  },
  {
    id: "hou-fogo-de-chao",
    name: "Fogo de Chão Houston",
    category: "brazilian",
    address: "8250 Westheimer Rd, Houston, TX 77063",
    area: "Galleria / Upper Kirby",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "18–20 jun",
    rating: 4.6,
    reviewCount: "6.200+",
    hours: "Seg–Qui 11h30–21h30 · Sex–Sáb 11h30–22h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência para autorização de câmera no salão.",
    tips:
      "Churrascaria brasileira premium na região da Galleria — o mais espaçoso e com maior movimento turístico em Houston. A 20 min de carro do hotel (Uber ~$15). Espaço amplo para gravações de grupo. Reservar com antecedência em semana de Copa.",
  },
  {
    id: "hou-pitch-25",
    name: "Pitch 25 Beer Park",
    category: "sports_bar",
    address: "2120 Walker St, Houston, TX 77003",
    area: "East Downtown / EaDo",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "18–20 jun",
    rating: 4.4,
    reviewCount: "8.500+",
    hours: "Seg–Qui 14h–00h · Sex 14h–02h · Sáb 11h–02h · Dom 11h–00h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "free",
    costNote: "Entrada gratuita; consumação à parte. Estacionamento gratuito no local.",
    permit: "film_office",
    permitNote: "Houston Film Commission para filmagem comercial na área pública.",
    tips:
      "Complexo ao ar livre com beer garden, mesas de foosball e telões — o sports bar mais amplo do Downtown Houston. A 10 min de carro do hotel. Copa: ambiente garantido nos dias de jogo. Estacionamento gratuito — raro no Downtown de Houston.",
  },

  // ── New Jersey · 20–24 jun + 26–28 jun ──────────────────────
  {
    id: "nj-liberty-state-park",
    name: "Liberty State Park",
    category: "park",
    address: "200 Morris Peshine Ave, Jersey City, NJ 07305",
    area: "Jersey City / Hudson Waterfront",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "20–24 jun · 26–28 jun",
    rating: 4.7,
    reviewCount: "25.000+",
    hours: "Seg–Dom 06h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "NJ Motion Picture & Television Commission (njfilm.org) para filmagem comercial.",
    tips:
      "Parque estadual com vista privilegiada para a Estátua da Liberdade e o skyline de Manhattan — backdrop impossível de igualar. A 20 min de carro de Secaucus. O melhor ponto de filmagem gratuita da região tri-state. Imprescindível para abertura de cobertura da Copa em NJ.",
  },
  {
    id: "nj-sinatra-park",
    name: "Sinatra Park — Hoboken Waterfront",
    category: "park",
    address: "50 Sinatra Dr, Hoboken, NJ 07030",
    area: "Hoboken Waterfront",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "20–24 jun · 26–28 jun",
    rating: 4.6,
    reviewCount: "6.500+",
    hours: "24h (área pública)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "NJ Motion Picture & Television Commission (njfilm.org) para filmagem comercial.",
    tips:
      "Parque à beira do Hudson com vista panorâmica do skyline de Manhattan — um dos melhores pontos de filmagem gratuita em NJ. A 15 min de carro de Secaucus. Excelente para externas ao amanhecer ou entardecer. Copa: provável ponto de concentração de torcedores brasileiros em NJ.",
  },
  {
    id: "nj-top-of-rock",
    name: "Top of the Rock — Rockefeller Center",
    category: "observatory",
    address: "30 Rockefeller Plaza, New York, NY 10112",
    area: "Midtown Manhattan · NYC",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "20–24 jun · 26–28 jun",
    rating: 4.7,
    reviewCount: "95.000+",
    hours: "Seg–Dom 09h–23h (última subida 22h30)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    costNote: "Adulto: ~$40. Reservar online. Horário noturno esgota rápido em semana de Copa.",
    permit: "venue_specific",
    permitNote: "Contato com NBC Universal/30 Rock para filmagem comercial.",
    tips:
      "A vista mais icônica de Manhattan — Empire State Building de frente, Central Park ao fundo. A 30 min de NJ Transit de Secaucus (Penn Station). Imprescindível para entradas ao vivo com skyline de Nova York. Reservar horário noturno para ver a cidade iluminada durante a Copa.",
  },
  {
    id: "nj-230-fifth",
    name: "230 Fifth Rooftop Bar",
    category: "rooftop",
    address: "230 Fifth Ave, New York, NY 10001",
    area: "Midtown / Flatiron · NYC",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "20–24 jun · 26–28 jun",
    rating: 4.3,
    reviewCount: "28.000+",
    hours: "Seg–Sex 16h–04h · Sáb–Dom 10h–04h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    costNote: "Sem ingresso; consumação mínima. Acesso ao rooftop aberto com consumação.",
    permit: "venue_specific",
    permitNote: "Contato com eventos do 230 Fifth para filmagem comercial.",
    tips:
      "Rooftop mais popular de Midtown com vista direta para o Empire State Building — backdrop inconfundível para entradas ao vivo noturnas. A 35 min de NJ Transit de Secaucus. Cobertura aquecida disponível. Chegar antes das 20h em dias de jogo para garantir vaga.",
  },
  {
    id: "nj-fogo-de-chao-nyc",
    name: "Fogo de Chão — New York City",
    category: "brazilian",
    address: "40 W 53rd St, New York, NY 10019",
    area: "Midtown Manhattan · NYC",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "20–24 jun · 26–28 jun",
    rating: 4.5,
    reviewCount: "8.000+",
    hours: "Seg–Sex 11h30–22h · Sáb–Dom 11h30–22h30",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência NYC para autorização editorial.",
    tips:
      "Fogo de Chão no coração de Midtown — ambiente sofisticado frequentado por turistas do mundo inteiro durante eventos globais. A 35 min de NJ Transit de Secaucus. Reservar mesa com antecedência: lotação garantida em semanas de Copa. Ideal para almoços de delegação em Nova York.",
  },

  // ── Kansas City MO · 24–26 jun ───────────────────────────────
  {
    id: "kc-liberty-memorial",
    name: "National WWI Museum & Memorial",
    category: "observatory",
    address: "2 Memorial Dr, Kansas City, MO 64108",
    area: "Crown Center / Downtown",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "24–26 jun",
    rating: 4.8,
    reviewCount: "18.000+",
    hours: "Seg–Dom 10h–17h (torre encerra 16h30)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "$",
    costNote: "Entrada museu + torre: ~$18. Tower-only: ~$8.",
    permit: "film_office",
    permitNote: "Kansas City Film Office (filmkc.com) para filmagem comercial.",
    tips:
      "A Liberty Memorial oferece o melhor panorama do skyline de Kansas City — perfila o horizonte completo com o Union Station no primeiro plano. A 10 min de carro do Hotel Phillips. Visual inédito para entradas ao vivo da Copa. Evitar nos 30 min antes do fechamento.",
  },
  {
    id: "kc-crossroads",
    name: "Crossroads Arts District",
    category: "park",
    address: "18th & Wyandotte St, Kansas City, MO 64108",
    area: "Crossroads Arts District",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "24–26 jun",
    rating: 4.4,
    reviewCount: "9.000+",
    hours: "24h (área pública)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "Kansas City Film Office para filmagem comercial na via pública.",
    tips:
      "Bairro artístico com murais coloridos e ruas vibrantes — visual urbano autêntico de KC. A 5 min de carro do Hotel Phillips. Excelente para externas dinâmicas e gravações de passagem. Vida noturna ativa nos fins de semana durante a Copa.",
  },
  {
    id: "kc-one-hotel-rooftop",
    name: "1 Hotel Kansas City — Rooftop Pool Bar",
    category: "rooftop",
    address: "1515 Wyandotte St, Kansas City, MO 64108",
    area: "Crown Center / Downtown",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "24–26 jun",
    rating: 4.6,
    reviewCount: "3.200+",
    hours: "Ter–Qui 16h–22h · Sex–Sáb 12h–23h · Dom 12h–20h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$$",
    costNote: "Consumação mínima; acesso requer reserva. Contato comercial para uso editorial.",
    permit: "venue_specific",
    permitNote: "Negociar diretamente com o hotel — taxa de locação para gravação comercial.",
    tips:
      "Rooftop com piscina e vista panorâmica de KC — backdrop sofisticado para entradas ao vivo ou entrevistas. A 7 min a pé do Hotel Phillips. Acesso normalmente restrito a hóspedes; negociar com a gerência de eventos para uso editorial durante a Copa.",
  },
  {
    id: "kc-fogo-de-chao",
    name: "Fogo de Chão Kansas City",
    category: "brazilian",
    address: "4921 Main St, Kansas City, MO 64112",
    area: "Country Club Plaza",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "24–26 jun",
    rating: 4.5,
    reviewCount: "5.800+",
    hours: "Seg–Qui 11h30–21h · Sex–Sáb 11h30–22h · Dom 11h30–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência para autorização de câmera no salão.",
    tips:
      "Churrascaria brasileira premium no Country Club Plaza — ambiente reconhecível para o público do Brasil. A 10 min de carro do Hotel Phillips. Ótimo para almoços de delegação ou gravações gastronômicas. Reservar mesa com antecedência durante a Copa.",
  },
  {
    id: "kc-power-light",
    name: "Power & Light District",
    category: "sports_bar",
    address: "1336 Grand Blvd, Kansas City, MO 64106",
    area: "Downtown / Power & Light",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "24–26 jun",
    rating: 4.3,
    reviewCount: "12.000+",
    hours: "Seg–Qui 11h–00h · Sex–Sáb 11h–02h · Dom 11h–22h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "free",
    costNote: "Área pública gratuita; consumação nos bares e restaurantes à parte.",
    permit: "film_office",
    permitNote: "Kansas City Film Office para câmeras na via pública.",
    tips:
      "O hub de entretenimento de KC com telões gigantes e dezenas de bares temáticos — ambiente Copa garantido nos dias de jogo. A 5 min a pé do Hotel Phillips. Ideal para coberturas noturnas e reações do torcedor. Alta concentração de fans durante a Copa.",
  },
];
