import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type FrancaPermit = "none" | "film_office" | "city_permit" | "venue_specific";

export const FRANCA_PERMIT_LABEL: Record<
  FrancaPermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",           tone: "green" },
  film_office:    { label: "Film Office local",    tone: "amber" },
  city_permit:    { label: "Prefeitura local",     tone: "amber" },
  venue_specific: { label: "Negociar com o local", tone: "orange" },
};

export interface FrancaVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade:
    | "los-angeles"
    | "boston-seaport-1"
    | "new-jersey"
    | "boston-midtown"
    | "philadelphia"
    | "boston-seaport-2";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: FrancaPermit;
  permitNote?: string;
  tips: string;
}

export const FRANCA_VENUES: FrancaVenueItem[] = [
  // ── Los Angeles 09–13 jun ─────────────────────────────────────
  {
    id: "la-griffith",
    name: "Griffith Observatory",
    category: "observatory",
    address: "2800 E Observatory Rd, Los Angeles, CA 90027",
    area: "Los Feliz",
    cidade: "los-angeles",
    cidadeLabel: "Los Angeles",
    periodo: "09–13 jun",
    rating: 4.8,
    reviewCount: "55.000+",
    hours: "Ter–Sex 12h–22h · Sáb–Dom 10h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    permit: "film_office",
    permitNote: "FilmLA (filmla.com)",
    tips:
      "Ícone de LA com vista panorâmica do Hollywood Sign e da cidade inteira. Terraço externo é referência visual inconfundível. A 20 min do hotel de carro.",
  },
  {
    id: "la-grandpark",
    name: "Grand Park DTLA",
    category: "park",
    address: "200 N Grand Ave, Los Angeles, CA 90012",
    area: "Downtown LA",
    cidade: "los-angeles",
    cidadeLabel: "Los Angeles",
    periodo: "09–13 jun",
    rating: 4.7,
    reviewCount: "10.000+",
    hours: "Diariamente 5h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "FilmLA (filmla.com)",
    tips:
      "Parque público central a 5 min do hotel a pé. Vista do City Hall — símbolo de LA. Em dias de Copa recebe fan zones espontâneas no Downtown.",
  },
  {
    id: "la-standard-rooftop",
    name: "Rooftop at The Standard DTLA",
    category: "rooftop",
    address: "550 S Flower St, Los Angeles, CA 90071",
    area: "Downtown LA",
    cidade: "los-angeles",
    cidadeLabel: "Los Angeles",
    periodo: "09–13 jun",
    rating: 4.2,
    reviewCount: "2.400+",
    hours: "Seg–Qui 17h–2h · Sex 15h–2h · Sáb–Dom 12h–2h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima (~$25/pessoa)",
    permit: "venue_specific",
    permitNote: "Direto com The Standard Hotel",
    tips:
      "Rooftop com piscina e skyline de Los Angeles ao fundo. A 3 min do hotel a pé. Ambiente animado à noite — ideal para conteúdo noturno com a cidade.",
  },
  {
    id: "la-fogodechao",
    name: "Fogo de Chão Los Angeles",
    category: "brazilian",
    address: "800 S Figueroa St, Los Angeles, CA 90017",
    area: "Downtown LA",
    cidade: "los-angeles",
    cidadeLabel: "Los Angeles",
    periodo: "09–13 jun",
    rating: 4.6,
    reviewCount: "3.800+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha a 2 min do hotel a pé. Excelente para conteúdo de brasilidade em LA. Ambiente sofisticado frequentado por executivos e turistas.",
  },
  {
    id: "la-caseys",
    name: "Casey's Irish Pub & Restaurant",
    category: "sports_bar",
    address: "613 S Grand Ave, Los Angeles, CA 90017",
    area: "Downtown LA",
    cidade: "los-angeles",
    cidadeLabel: "Los Angeles",
    periodo: "09–13 jun",
    rating: 4.2,
    reviewCount: "2.000+",
    hours: "Diariamente 11h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Pub irlandês clássico no DTLA a 3 min do hotel. Transmite todos os jogos da Copa desde cedo. Alta energia da comunidade de futebol local em dias de jogo.",
  },

  // ── Boston Seaport I 13–14 jun ────────────────────────────────
  {
    id: "bos1-lookout",
    name: "Lookout Rooftop & Bar — Envoy Hotel",
    category: "rooftop",
    address: "70 Sleeper St, Boston, MA 02210",
    area: "Seaport",
    cidade: "boston-seaport-1",
    cidadeLabel: "Boston Seaport",
    periodo: "13–14 jun",
    rating: 4.4,
    reviewCount: "3.800+",
    hours: "Seg–Qui 16h–23h · Sex 16h–0h · Sáb 12h–0h · Dom 12h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Envoy Hotel",
    tips:
      "Melhor rooftop do Seaport com vista do porto de Boston e do skyline. A 5 min do Aloft a pé. Opção ideal para conteúdo rápido na escala de 1 noite.",
  },
  {
    id: "bos1-fanpier",
    name: "Fan Pier Park — Boston Harborwalk",
    category: "park",
    address: "1 Fan Pier Blvd, Boston, MA 02210",
    area: "Seaport",
    cidade: "boston-seaport-1",
    cidadeLabel: "Boston Seaport",
    periodo: "13–14 jun",
    rating: 4.7,
    reviewCount: "2.500+",
    hours: "Aberto ao público",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Boston Film Bureau",
    tips:
      "Orla do porto com vista do skyline de Boston. A 5 min do hotel. Boa luz natural o dia todo. Ideal para conteúdo de chegada/transição entre cidades.",
  },

  // ── New Jersey 14–17 jun ──────────────────────────────────────
  {
    id: "nj-hoboken-waterfront",
    name: "Hoboken Waterfront (Sinatra Drive)",
    category: "park",
    address: "Sinatra Dr, Hoboken, NJ 07030",
    area: "Hoboken NJ",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "14–17 jun",
    rating: 4.8,
    reviewCount: "800+",
    hours: "Aberto ao público (orla)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Cidade de Hoboken — uso comercial",
    tips:
      "Vista completa do skyline de Manhattan pelo lado de NJ. Pôr do sol privilegiado. Um dos backdrops mais reconhecidos da região para conteúdo ao ar livre.",
  },
  {
    id: "nj-nohu",
    name: "NoHu Rooftop Bar",
    category: "rooftop",
    address: "550 Ave at Port Imperial, Weehawken, NJ 07086",
    area: "Weehawken NJ",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "14–17 jun",
    rating: 4.0,
    reviewCount: "1.900+",
    hours: "Seg–Qui 17h–23h · Sex–Sáb 17h–0h · Dom 17h–23h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com o hotel",
    tips:
      "Rooftop com vista direta de Manhattan e do Hudson River. A 3 min da NJ Light Rail. Ambiente sofisticado para conteúdo noturno com o skyline de fundo.",
  },
  {
    id: "nj-230fifth",
    name: "230 Fifth Rooftop Bar",
    category: "rooftop",
    address: "230 5th Ave, New York, NY 10001",
    area: "Manhattan — Midtown",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "14–17 jun",
    rating: 4.3,
    reviewCount: "25.000+",
    hours: "Seg–Sex 12h–1h · Sáb 11h–4h · Dom 11h–1h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "film_office",
    permitNote: "NYC MOME (nyc.gov/film)",
    tips:
      "Vista direta do Empire State Building. PATH de Hoboken até 33rd St + 3 min a pé. Um dos rooftops mais filmados de NYC.",
  },
  {
    id: "nj-smithfield",
    name: "Smithfield Hall",
    category: "sports_bar",
    address: "138 W 25th St, New York, NY 10001",
    area: "Manhattan",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "14–17 jun",
    rating: 4.4,
    reviewCount: "1.800+",
    hours: "Seg–Sex 12h–0h · Sáb 9h–0h · Dom 10h–0h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Eventos podem cobrar ingresso",
    permit: "none",
    tips:
      "Popular para futebol e Copa em NYC. PATH de Hoboken até 23rd St + 5 min a pé. Alta energia em dias de jogo com torcida internacional.",
  },
  {
    id: "nj-weehawken-park",
    name: "Weehawken Waterfront Park",
    category: "park",
    address: "1 Port Imperial Blvd, Weehawken, NJ 07086",
    area: "Weehawken NJ",
    cidade: "new-jersey",
    cidadeLabel: "New Jersey",
    periodo: "14–17 jun",
    rating: 4.7,
    reviewCount: "1.400+",
    hours: "Seg–Dom 7h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Município de Weehawken",
    tips:
      "Vista privilegiada de Midtown Manhattan — ângulo diferente do Hoboken Waterfront. Trilhas e área aberta com ótima luz natural para externas.",
  },

  // ── Boston Midtown 16–20 jun ──────────────────────────────────
  {
    id: "bos2-prudential",
    name: "Prudential Center Skywalk Observatory",
    category: "observatory",
    address: "800 Boylston St, Boston, MA 02199",
    area: "Back Bay",
    cidade: "boston-midtown",
    cidadeLabel: "Boston Midtown",
    periodo: "16–20 jun",
    rating: 4.5,
    reviewCount: "9.500+",
    hours: "Diariamente 10h–20h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "~$24/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Prudential Center",
    tips:
      "Vista 360° de Boston do 50º andar do Prudential. A 10 min do hotel a pé. Melhor observatório da cidade — ótimo para conteúdo aéreo de Boston.",
  },
  {
    id: "bos2-fenway",
    name: "Fenway Park — Yawkey Way",
    category: "park",
    address: "4 Jersey St, Boston, MA 02215",
    area: "Fenway",
    cidade: "boston-midtown",
    cidadeLabel: "Boston Midtown",
    periodo: "16–20 jun",
    rating: 4.8,
    reviewCount: "28.000+",
    hours: "Área externa: livre — Tours: diariamente 9h–16h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    costNote: "Tour interno ~$25/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com Boston Red Sox",
    tips:
      "Estádio mais icônico dos EUA. Área externa (Yawkey Way) é pública. A 10 min do hotel a pé ou 2 paradas de MBTA Green. Conteúdo esportivo de alto impacto.",
  },
  {
    id: "bos2-verb-pool",
    name: "The Verb Hotel — Pool Deck",
    category: "rooftop",
    address: "1271 Boylston St, Boston, MA 02215",
    area: "Fenway",
    cidade: "boston-midtown",
    cidadeLabel: "Boston Midtown",
    periodo: "16–20 jun",
    rating: 4.4,
    reviewCount: "1.200+",
    hours: "Sáb–Dom 12h–22h (temporada de verão)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "paid",
    costNote: "Consumação mínima / hóspede",
    permit: "venue_specific",
    permitNote: "Direto com The Verb Hotel",
    tips:
      "Deck com piscina ao lado do Fenway Park. Vista do estádio e da área do Fenway. Vibe retrô e descolada — ótimo para conteúdo de lifestyle esportivo.",
  },
  {
    id: "bos2-fogodechao",
    name: "Fogo de Chão Boston",
    category: "brazilian",
    address: "200 Boylston St, Boston, MA 02116",
    area: "Theater District",
    cidade: "boston-midtown",
    cidadeLabel: "Boston Midtown",
    periodo: "16–20 jun",
    rating: 4.6,
    reviewCount: "3.200+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha referência em Boston. A 15 min do hotel de Uber. Ambiente verde-amarelo durante a Copa — perfeito para conteúdo com brasilidade.",
  },
  {
    id: "bos2-gameon",
    name: "Game On! Sports Bar & Grill",
    category: "sports_bar",
    address: "82 Lansdowne St, Boston, MA 02215",
    area: "Fenway",
    cidade: "boston-midtown",
    cidadeLabel: "Boston Midtown",
    periodo: "16–20 jun",
    rating: 4.3,
    reviewCount: "3.800+",
    hours: "Seg–Qui 11h30–1h · Sex–Sáb 11h30–2h · Dom 10h–1h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Sports bar dentro do complexo do Fenway Park com centenas de TVs. Popular entre torcedores de futebol durante a Copa. A 10 min do hotel a pé.",
  },

  // ── Philadelphia 20–23 jun ────────────────────────────────────
  {
    id: "phl-museum-art",
    name: "Philadelphia Museum of Art (Rocky Steps)",
    category: "park",
    address: "2600 Benjamin Franklin Pkwy, Philadelphia, PA 19130",
    area: "Fairmount",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "20–23 jun",
    rating: 4.8,
    reviewCount: "20.000+",
    hours: "Exterior: 24h — Museu: Ter–Dom 10h–17h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    costNote: "Museu ~$30/pessoa",
    permit: "city_permit",
    permitNote: "Philadelphia Film Office",
    tips:
      "Os degraus do Rocky são o símbolo de Philadelphia. Vista do Benjamin Franklin Pkwy. A 15 min do hotel de Uber. Conteúdo icônico e reconhecível mundialmente.",
  },
  {
    id: "phl-bok",
    name: "Bok Bar Rooftop",
    category: "rooftop",
    address: "800 Mifflin St, Philadelphia, PA 19148",
    area: "South Philadelphia",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "20–23 jun",
    rating: 4.4,
    reviewCount: "2.100+",
    hours: "Qui–Sáb 17h–0h (sazonal · verão)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$",
    permit: "venue_specific",
    permitNote: "Direto com BOK Building",
    tips:
      "Rooftop mais querido de Philly, em escola histórica convertida. Vista de toda a cidade incluindo o estádio. A 5 min do Lincoln Financial de carro.",
  },
  {
    id: "phl-fogodechao",
    name: "Fogo de Chão Philadelphia",
    category: "brazilian",
    address: "1337 Chestnut St, Philadelphia, PA 19107",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "20–23 jun",
    rating: 4.5,
    reviewCount: "2.800+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha a 5 min do hotel a pé. Excelente para conteúdo de brasilidade durante os jogos em Philadelphia.",
  },
  {
    id: "phl-fieldhouse",
    name: "Field House Philadelphia",
    category: "sports_bar",
    address: "1150 Filbert St, Philadelphia, PA 19107",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "20–23 jun",
    rating: 4.2,
    reviewCount: "3.500+",
    hours: "Seg–Sex 11h–2h · Sáb–Dom 10h–2h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Bar esportivo com 50+ TVs a 2 min do hotel a pé. Transmite todos os jogos da Copa com energia de arena. Fan zone natural da cidade.",
  },
  {
    id: "phl-franklin",
    name: "The Franklin Institute",
    category: "observatory",
    address: "222 N 20th St, Philadelphia, PA 19103",
    area: "Logan Square",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia",
    periodo: "20–23 jun",
    rating: 4.7,
    reviewCount: "15.000+",
    hours: "Seg–Dom 9h30–17h",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "~$25/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com The Franklin Institute",
    tips:
      "Museu de ciências histórico de Philadelphia com a estátua de Benjamin Franklin. A 15 min do hotel de Uber. Visual imponente e reconhecível — conteúdo de cultura americana.",
  },

  // ── Boston Seaport II 23–28 jun ───────────────────────────────
  {
    id: "bos3-lookout",
    name: "Lookout Rooftop & Bar — Envoy Hotel",
    category: "rooftop",
    address: "70 Sleeper St, Boston, MA 02210",
    area: "Seaport",
    cidade: "boston-seaport-2",
    cidadeLabel: "Boston Seaport",
    periodo: "23–28 jun",
    rating: 4.4,
    reviewCount: "3.800+",
    hours: "Seg–Qui 16h–23h · Sex 16h–0h · Sáb 12h–0h · Dom 12h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "paid",
    costNote: "Consumação mínima",
    permit: "venue_specific",
    permitNote: "Direto com Envoy Hotel",
    tips:
      "Melhor rooftop do Seaport com vista do porto e do skyline de Boston. A 5 min do Homewood Suites a pé. Base ideal para conteúdo da reta final da Copa.",
  },
  {
    id: "bos3-fanpier",
    name: "Fan Pier Park — Boston Harborwalk",
    category: "park",
    address: "1 Fan Pier Blvd, Boston, MA 02210",
    area: "Seaport",
    cidade: "boston-seaport-2",
    cidadeLabel: "Boston Seaport",
    periodo: "23–28 jun",
    rating: 4.7,
    reviewCount: "2.500+",
    hours: "Aberto ao público",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "city_permit",
    permitNote: "Boston Film Bureau",
    tips:
      "Orla do porto com skyline de Boston ao fundo. A 5 min do hotel. Excelente para transmissões ao vivo. Boa luz natural manhã e fim de tarde.",
  },
  {
    id: "bos3-ica",
    name: "Institute of Contemporary Art (ICA)",
    category: "observatory",
    address: "25 Harbor Shore Dr, Boston, MA 02210",
    area: "Seaport",
    cidade: "boston-seaport-2",
    cidadeLabel: "Boston Seaport",
    periodo: "23–28 jun",
    rating: 4.6,
    reviewCount: "7.200+",
    hours: "Ter–Dom 10h–17h (Qui até 21h)",
    goodDay: "yes",
    goodNight: "no",
    cost: "paid",
    costNote: "~$25/pessoa",
    permit: "venue_specific",
    permitNote: "Direto com o ICA",
    tips:
      "Museu com terraço suspenso sobre o porto de Boston. Visual arquitetônico único — a 10 min do hotel. Exige agendamento para filmagem comercial.",
  },
  {
    id: "bos3-fogodechao",
    name: "Fogo de Chão Boston",
    category: "brazilian",
    address: "200 Boylston St, Boston, MA 02116",
    area: "Theater District",
    cidade: "boston-seaport-2",
    cidadeLabel: "Boston Seaport",
    periodo: "23–28 jun",
    rating: 4.6,
    reviewCount: "3.200+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria gaúcha referência em Boston. A 15 min de Uber do Homewood Suites. Encerrar a Copa com jantar de comemoração em ambiente brasileiro.",
  },
  {
    id: "bos3-harpoon",
    name: "Harpoon Brewery & Beer Hall",
    category: "sports_bar",
    address: "306 Northern Ave, Boston, MA 02210",
    area: "Seaport",
    cidade: "boston-seaport-2",
    cidadeLabel: "Boston Seaport",
    periodo: "23–28 jun",
    rating: 4.5,
    reviewCount: "15.000+",
    hours: "Seg–Qui 11h–22h · Sex–Sáb 11h–23h · Dom 11h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Cervejaria com beer hall enorme e área externa. A 5 min do hotel a pé. Exibe Copa em múltiplas TVs. Ótima opção para confraternização da equipe nos últimos dias.",
  },
];
