import type { CityConfig } from "./types-deslocamentos";

export const CWB_CONFIG: CityConfig = {
  id: "cwb",
  emoji: "🌲",
  cidade: "Curitiba",
  periodo: "Brasileirão",
  contatoLocal: {
    nome: "Fernando Nóbrega",
    telefone: "+55 41 9911-9466",
  },
  origins: [
    {
      id: "hotel",
      name: "Novotel Curitiba Batel",
      addr: "R. Dr. Pedrosa, 288, Centro, Curitiba - PR, 80420-120",
      lat: -25.43811,
      lng: -49.27723,
    },
  ],
  destinations: [
    {
      id: "arena-baixada",
      name: "Arena da Baixada",
      addr: "Rua Buenos Aires, 1260, Água Verde, Curitiba - PR, 80250-070",
      lat: -25.44842,
      lng: -49.27618,
      category: "estadio",
    },
    {
      id: "couto-pereira",
      name: "Estádio Couto Pereira",
      addr: "Rua Ubaldino do Amaral, 37, Alto da Glória, Curitiba - PR, 80060-195",
      lat: -25.4183,
      lng: -49.2632,
      category: "estadio",
    },
    {
      id: "afonso-pena",
      name: "Aeroporto Afonso Pena (CWB)",
      addr: "Av. Rocha Pombo, s/n, São José dos Pinhais - PR, 83010-900",
      lat: -25.53559,
      lng: -49.17463,
      category: "aeroporto",
    },
    {
      id: "jardim-botanico",
      name: "Jardim Botânico",
      addr: "R. Eng. Ostoja Roguski, s/n, Curitiba - PR, 80210-390",
      lat: -25.44171,
      lng: -49.23866,
      category: "ponto_turistico",
    },
    {
      id: "opera-de-arame",
      name: "Ópera de Arame",
      addr: "Rua João Gava, 920, Abranches, Curitiba - PR, 82130-010",
      lat: -25.38524,
      lng: -49.27609,
      category: "ponto_turistico",
    },
    {
      id: "torre-panoramica",
      name: "Torre Panorâmica",
      addr: "R. Prof. Lycio Grein de Castro Vellozo, 191, Curitiba - PR, 80710-650",
      lat: -25.42389,
      lng: -49.29404,
      category: "outro",
    },
    {
      id: "parque-barigui",
      name: "Parque Barigui",
      addr: "Av. Cândido Hartmann, s/n, Curitiba - PR, 82025-160",
      lat: -25.41887,
      lng: -49.30542,
      category: "outro",
    },
  ],
  routes: [
    {
      from: "hotel",
      to: "arena-baixada",
      carN: "5–8 min",
      carH: "10–15 min",
      tp: "Linha Verde (BRT) a poucos quarteirões, trecho final a pé",
      dist: "1,8–2 km",
      diff: "moderado",
      costCar: "~R$3",
      costTp: "~R$5,50",
      note: "Bloqueio de ruas ao redor da arena em dias de jogo",
    },
    {
      from: "hotel",
      to: "couto-pereira",
      carN: "6–10 min",
      carH: "12–18 min",
      tp: "Linha Turismo/BRT nas proximidades, trecho final a pé",
      dist: "2,5–3 km",
      diff: "moderado",
      costCar: "~R$5",
      costTp: "~R$5,50",
      note: "Bloqueio de ruas no entorno do Alto da Glória em dias de jogo do Coritiba",
    },
    {
      from: "hotel",
      to: "afonso-pena",
      carN: "30–35 min",
      carH: "45–60 min",
      tp: "Aeroporto Executivo a cada 15 min, ~35–45 min até a Rodoferroviária",
      dist: "19–21 km",
      diff: "dificil",
      costCar: "~R$28",
      costTp: "~R$14",
      note: "Via BR-277, sensível a chuva e horário de pico",
    },
    {
      from: "hotel",
      to: "jardim-botanico",
      carN: "12–15 min",
      carH: "20–25 min",
      tp: "Linha Turismo",
      dist: "5 km",
      diff: "facil",
      costCar: "~R$7",
      costTp: "~R$5,50",
    },
    {
      from: "hotel",
      to: "opera-de-arame",
      carN: "15–20 min",
      carH: "25–35 min",
      tp: "Linha Turismo",
      dist: "7–8 km",
      diff: "moderado",
      costCar: "~R$9",
      costTp: "~R$5,50",
    },
    {
      from: "hotel",
      to: "torre-panoramica",
      carN: "8–10 min",
      carH: "15–18 min",
      tp: "Linha Turismo",
      dist: "3 km",
      diff: "facil",
      costCar: "~R$5",
      costTp: "~R$5,50",
    },
    {
      from: "hotel",
      to: "parque-barigui",
      carN: "10–15 min",
      carH: "20–25 min",
      tp: "Linha Turismo + BRT",
      dist: "4–5 km",
      diff: "facil",
      costCar: "~R$7",
      costTp: "~R$5,50",
    },
  ],
  alerts: [
    {
      category: "transito",
      text: "O BRT é referência mundial, mas só cobre os corredores estruturais — fora deles, considere app/carro.",
    },
    {
      category: "estadio",
      text: "Dias de jogo têm bloqueio nas ruas ao redor da Arena da Baixada (Athletico) e do Couto Pereira (Coritiba) — confirme qual time manda o jogo antes de fechar a rota.",
    },
    {
      category: "aeroporto",
      text: "O Afonso Pena fica relativamente longe do centro (~20 km via BR-277), sensível a chuva e horário de pico.",
    },
    {
      category: "geral",
      text: "Clima instável — 'quatro estações num dia'. Leve isso em conta ao planejar deslocamentos externos.",
    },
    {
      category: "seguranca",
      text: "Aglomeração de torcida se concentra nas ruas ao redor das arenas 1-2h antes/depois do jogo — evite atravessar o meio da concentração sozinho com equipamento à mostra.",
    },
  ],
};
