import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type DefantePermit = "none" | "film_office" | "venue_specific" | "gov_mx";

export const DEFANTE_PERMIT_LABEL: Record<
  DefantePermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",           tone: "green"  },
  film_office:    { label: "Film Office local",    tone: "amber"  },
  venue_specific: { label: "Negociar com o local", tone: "orange" },
  gov_mx:         { label: "Secretaria Cultura MX",tone: "amber"  },
};

export interface DefanteVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade: "nova-york" | "cdmx" | "atlanta" | "kansas-city" | "philadelphia" | "miami";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: DefantePermit;
  permitNote?: string;
  tips: string;
}

export const DEFANTE_VENUES: DefanteVenueItem[] = [

  // ── Nova York · 02–06 · 12–14 · 19–22 jun ────────────────────
  {
    id: "ny-central-park",
    name: "Central Park",
    category: "park",
    address: "Central Park, New York, NY 10024",
    area: "Midtown / Upper West Side",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.8,
    reviewCount: "1,2M+",
    hours: "6h–1h (todos os dias)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "NYC Mayor's Office of Media & Entertainment — film.nyc.gov",
    tips:
      "Bethesda Fountain, Bow Bridge e o Great Lawn são os spots mais icônicos. Permit via MOME — formulário online, prazo recomendado de 5–10 dias úteis. Gratuito para filmagens não comerciais; taxa para uso comercial.",
  },
  {
    id: "ny-230-fifth",
    name: "230 Fifth Rooftop Bar",
    category: "rooftop",
    address: "230 Fifth Ave, New York, NY 10001",
    area: "Flatiron / Midtown South",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.3,
    reviewCount: "25.000+",
    hours: "Seg–Sex 12h–1h · Sáb 11h–4h · Dom 11h–1h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    costNote: "Consumação mínima variável",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do 230 Fifth",
    tips:
      "Vista direta do Empire State Building — um dos rooftops mais filmados de NYC. A ~15 min a pé do hotel. Possui iglus aquecidos. Negociar uso comercial e janela exclusiva com antecedência.",
  },
  {
    id: "ny-one-world-obs",
    name: "One World Observatory",
    category: "observatory",
    address: "285 Fulton St, New York, NY 10006",
    area: "Lower Manhattan",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.7,
    reviewCount: "38.000+",
    hours: "9h–21h (último acesso 20h)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    costNote: "Ingresso ~$44 por pessoa",
    permit: "venue_specific",
    permitNote: "Contato comercial: oneworldobservatory.com",
    tips:
      "Vista de 360° do prédio mais alto das Américas (541m). Luz natural de dia; skyline noturno espetacular. Reservar com antecedência — contato para produções em oneworldobservatory.com.",
  },
  {
    id: "ny-fogo-de-chao",
    name: "Fogo de Chão Midtown",
    category: "brazilian",
    address: "40 W 53rd St, New York, NY 10019",
    area: "Midtown Manhattan",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.5,
    reviewCount: "9.900+",
    hours: "Seg–Qui 11h30–22h30 · Sex–Sáb 11h30–23h · Dom 11h30–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Churrascaria brasileira premium no Midtown — boa acústica e iluminação para gravações internas. Almoço de segunda com market table mais acessível. Negociar janela para produção com a gerência.",
  },
  {
    id: "ny-smithfield",
    name: "Smithfield Hall",
    category: "sports_bar",
    address: "138 W 25th St, New York, NY 10001",
    area: "Chelsea / Midtown South",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.4,
    reviewCount: "1.800+",
    hours: "Seg–Sex 12h–0h · Sáb 9h–0h · Dom 10h–0h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Popular entre torcedores de futebol/soccer e UFC — boa energia para gravações ao vivo. A 15 min a pé do hotel. Chegar cedo em dias de Copa para garantir boa posição.",
  },
  {
    id: "ny-vintage-green",
    name: "Vintage Green Rooftop Bar",
    category: "rooftop",
    address: "303 Lexington Ave, New York, NY 10016",
    area: "Murray Hill",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.9,
    reviewCount: "3.170+",
    hours: "18h–2h (Ter–Sáb) · Fechado Dom–Seg",
    goodDay: "no",
    goodNight: "yes",
    cost: "$$",
    costNote: "Consumação mínima variável em noites de evento",
    permit: "venue_specific",
    permitNote: "Negociar diretamente com a gerência",
    tips:
      "O rooftop mais bem avaliado de NYC para eventos — 4.9★ com mais de 3.100 avaliações. Vista panorâmica do Midtown skyline. A ~12 min a pé do hotel. Focado em eventos privados — contato com antecedência obrigatório para uso comercial.",
  },
  {
    id: "ny-rt60",
    name: "RT60 Rooftop Bar",
    category: "rooftop",
    address: "159 W 48th St, New York, NY 10036",
    area: "Midtown / Rockefeller Area",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.5,
    reviewCount: "1.900+",
    hours: "17h–0h (Seg–Qui) · 17h–2h (Sex–Sáb) · 16h–23h (Dom)",
    goodDay: "no",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do RT60",
    tips:
      "Rooftop no coração do Midtown a ~10 min a pé do hotel. Vista do skyline de Manhattan incluindo Empire State Building. Ambiente moderno com coquetéis autorais. Negociar janela para uso comercial com a gerência.",
  },
  {
    id: "ny-summit-vanderbilt",
    name: "SUMMIT One Vanderbilt",
    category: "observatory",
    address: "45 E 42nd St, New York, NY 10017",
    area: "Grand Central / Midtown East",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.7,
    reviewCount: "35.000+",
    hours: "9h–22h (Dom–Qui) · 9h–23h (Sex–Sáb) — último acesso 1h antes",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    costNote: "Ingresso ~$39–49 por pessoa",
    permit: "venue_specific",
    permitNote: "Contato comercial: summitov.com",
    tips:
      "Experiência imersiva no topo do One Vanderbilt — 4.7★ com mais de 35.000 avaliações. Vista de 360° com instalações artísticas e andares de vidro. A ~10 min a pé do hotel. Contato para uso comercial e produções via summitov.com.",
  },
  {
    id: "ny-yard-house",
    name: "Yard House Times Square",
    category: "sports_bar",
    address: "575 7th Ave, New York, NY 10018",
    area: "Times Square / Midtown",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.1,
    reviewCount: "4.500+",
    hours: "11h30–0h (Seg–Qui) · 11h30–1h (Sex–Sáb) · 11h–0h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    permit: "none",
    tips:
      "Sports bar mais próximo do hotel — a ~3 min a pé. Mais de 100 torneiras de chope, cardápio extenso e múltiplas TVs. Ótima energia em dias de Copa. Localizado em Times Square — possibilidade de gravações espontâneas na área.",
  },
  {
    id: "ny-stout",
    name: "Stout NYC",
    category: "sports_bar",
    address: "215 W 35th St, New York, NY 10001",
    area: "Chelsea / Midtown South",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.3,
    reviewCount: "2.400+",
    hours: "11h–4h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Sports bar a ~2 min a pé do hotel — mesma rua (W 35th). Ambiente descontraído, muitas TVs, cervejas artesanais e boa energia. Abre até às 4h — útil para jogos em horários tardios. Ponto de encontro de torcedores da região.",
  },
  {
    id: "ny-high-line",
    name: "High Line",
    category: "park",
    address: "High Line, New York, NY 10011",
    area: "Chelsea / Hudson Yards",
    cidade: "nova-york",
    cidadeLabel: "Nova York NY",
    periodo: "02–06 · 12–14 · 19–22 jun",
    rating: 4.7,
    reviewCount: "150.000+",
    hours: "7h–22h (temporada de verão, todos os dias)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "NYC Mayor's Office of Media & Entertainment — film.nyc.gov · Também contatar High Line: thehighline.org",
    tips:
      "Parque elevado sobre ferrovia desativada — um dos espaços mais fotogênicos de NYC. Entradas em 14th, 16th, 23rd e 30th St (esta ~15 min a pé do hotel). Gratuito para visitantes. Permit comercial via MOME + contato direto com a High Line.",
  },

  // ── Cidade do México · 06–12 jun ─────────────────────────────
  {
    id: "cdmx-chapultepec",
    name: "Bosque de Chapultepec",
    category: "park",
    address: "Bosque de Chapultepec, Miguel Hidalgo, CDMX 11580",
    area: "Miguel Hidalgo",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "06–12 jun",
    rating: 4.7,
    reviewCount: "200.000+",
    hours: "5h–18h (Ter–Dom — fechado seg)",
    goodDay: "yes",
    goodNight: "no",
    cost: "free",
    permit: "gov_mx",
    permitNote: "Secretaría de Cultura CDMX — cultural.cdmx.gob.mx",
    tips:
      "Maior parque urbano da CDMX. Área junto ao Lago de Chapultepec e Paseo de los Poetas para gravações externas icônicas. Permit via Secretaría de Cultura CDMX — prazo mínimo 10 dias úteis. A 10 min do hotel de Uber.",
  },
  {
    id: "cdmx-cha-cha-cha",
    name: "Terraza Cha Cha Chá",
    category: "rooftop",
    address: "Isabel la Católica 30, Centro Histórico, CDMX 06000",
    area: "Centro Histórico",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "06–12 jun",
    rating: 4.5,
    reviewCount: "3.500+",
    hours: "13h–1h (Seg–Sáb) · 13h–23h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar diretamente com o restaurante",
    tips:
      "Rooftop com vista privilegiada para a Catedral Metropolitana e o Zócalo — backdrop único do coração do México. Ambiente gastronômico com pratos mexicanos. Negociar janela comercial com antecedência.",
  },
  {
    id: "cdmx-torre-latina",
    name: "Torre Latinoamericana",
    category: "observatory",
    address: "Francisco I. Madero 2, Centro Histórico, CDMX 06000",
    area: "Centro Histórico",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "06–12 jun",
    rating: 4.4,
    reviewCount: "22.000+",
    hours: "9h–22h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Ingresso ~$120 MXN (~$7 USD)",
    permit: "venue_specific",
    permitNote: "Contato comercial direto com a administração",
    tips:
      "Vista panorâmica de 360° da CDMX do 44º andar. Ícone da cidade desde 1956. Ótima visibilidade do Zócalo, Paseo de la Reforma e serras ao redor. Contato com administração do edifício para uso comercial.",
  },
  {
    id: "cdmx-fogo-polanco",
    name: "Fogo de Chão Polanco",
    category: "brazilian",
    address: "Presidente Masaryk 61, Polanco, CDMX 11560",
    area: "Polanco",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "06–12 jun",
    rating: 4.6,
    reviewCount: "5.200+",
    hours: "12h–23h (Seg–Sáb) · 12h–22h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Filial mexicana do Fogo de Chão em Polanco — bairro mais nobre de CDMX. A ~12 min do hotel de Uber. Ambiente sofisticado e clientela internacional. Boa acústica para gravações internas.",
  },

  // ── Atlanta · 14–16 jun ───────────────────────────────────────
  {
    id: "atl-centennial-park",
    name: "Centennial Olympic Park",
    category: "park",
    address: "265 Park Ave W NW, Atlanta, GA 30313",
    area: "Downtown",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "14–16 jun",
    rating: 4.7,
    reviewCount: "45.000+",
    hours: "7h–23h (todos os dias)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Georgia World Congress Authority — gwcc.com",
    tips:
      "Parque histórico dos Jogos Olímpicos de 1996. Fonte interativa das 5 argolas olímpicas é backdrop icônico. A 10 min do hotel de MARTA. Permit via GWCC — processar com antecedência para uso comercial.",
  },
  {
    id: "atl-glenn-hotel",
    name: "Glenn Hotel Sun Deck",
    category: "rooftop",
    address: "110 Marietta St NW, Atlanta, GA 30303",
    area: "Downtown",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "14–16 jun",
    rating: 4.5,
    reviewCount: "2.500+",
    hours: "17h–0h (Seg–Qui) · 17h–1h (Sex–Sáb) · 14h–22h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Glenn Hotel",
    tips:
      "Rooftop do hotel boutique Glenn com vista para o skyline de Atlanta e o Mercedes-Benz Stadium. A 10 min a pé do hotel. Ambiente sofisticado — ideal para gravações ao entardecer e à noite.",
  },
  {
    id: "atl-skyview",
    name: "SkyView Atlanta",
    category: "observatory",
    address: "168 Luckie St NW, Atlanta, GA 30303",
    area: "Downtown",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "14–16 jun",
    rating: 4.3,
    reviewCount: "6.000+",
    hours: "Seg–Qui 12h–22h · Sex 12h–23h · Sáb 10h–23h · Dom 10h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Ingresso ~$14–16 por pessoa",
    permit: "venue_specific",
    permitNote: "Contato: skyviewatlanta.com",
    tips:
      "Roda-gigante de 20 andares com vista panorâmica de Atlanta. Gôndolas climatizadas, ótimo para gravações diurnas e noturnas. Próxima ao Centennial Park. Contato comercial: skyviewatlanta.com.",
  },
  {
    id: "atl-fogo-de-chao",
    name: "Fogo de Chão Atlanta",
    category: "brazilian",
    address: "3101 Piedmont Rd NE, Atlanta, GA 30305",
    area: "Buckhead",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "14–16 jun",
    rating: 4.7,
    reviewCount: "7.500+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "Em Buckhead, bairro premium de Atlanta — a ~20 min do hotel de Uber ou MARTA. Ambiente elegante com boa iluminação para gravações. Negociar janela com a gerência local.",
  },
  {
    id: "atl-stats-brewpub",
    name: "Stats Brewpub",
    category: "sports_bar",
    address: "300 Marietta St NW, Atlanta, GA 30313",
    area: "Downtown / CNN Center",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "14–16 jun",
    rating: 4.2,
    reviewCount: "3.800+",
    hours: "11h–2h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Sports bar a 2 quarteirões do Centennial Park e do CNN Center. Mais de 100 TVs, cervejas artesanais locais e ótima energia em dias de Copa. A 12 min a pé do hotel.",
  },
  {
    id: "atl-rt60",
    name: "RT60 Rooftop Bar Atlanta",
    category: "rooftop",
    address: "89 Centennial Olympic Park Dr NW, Atlanta, GA 30313",
    area: "Downtown / Centennial Park",
    cidade: "atlanta",
    cidadeLabel: "Atlanta GA",
    periodo: "14–16 jun",
    rating: 4.4,
    reviewCount: "1.500+",
    hours: "17h–0h (Ter–Qui) · 17h–2h (Sex–Sáb) · Fechado Dom–Seg",
    goodDay: "no",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do RT60 Atlanta",
    tips:
      "Rooftop ao lado do Centennial Olympic Park com vista para o Downtown Atlanta. Dois pontos icônicos cobertos em uma visita. A ~10 min a pé do hotel. Negociar janela para uso comercial com a gerência.",
  },

  // ── Kansas City · 15–17 jun ───────────────────────────────────
  {
    id: "kc-wwi-memorial",
    name: "National WWI Museum & Memorial",
    category: "observatory",
    address: "2 Memorial Dr, Kansas City, MO 64108",
    area: "Downtown / Union Station",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.8,
    reviewCount: "15.000+",
    hours: "10h–17h (Ter–Dom — fechado seg)",
    goodDay: "yes",
    goodNight: "no",
    cost: "$",
    costNote: "Ingresso ~$16 por pessoa (torre incluída)",
    permit: "venue_specific",
    permitNote: "Contato: theworldwar.org",
    tips:
      "Torre memorial com vista panorâmica de Kansas City e do Union Station. Ícone arquitetônico da cidade. A 15 min a pé do hotel. Contato comercial via theworldwar.org — agendamento necessário.",
  },
  {
    id: "kc-1hotel-rooftop",
    name: "1 Hotel Kansas City — Rooftop",
    category: "rooftop",
    address: "1 W Pershing Rd, Kansas City, MO 64108",
    area: "Downtown / Union Station",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.6,
    reviewCount: "1.200+",
    hours: "16h–23h (Seg–Qui) · 14h–1h (Sex–Sáb) · 14h–22h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do 1 Hotel KC",
    tips:
      "Rooftop do hotel boutique 1 Hotel, a 15 min a pé do Hotel Phillips. Vista para o Union Station e o skyline de KC. Ambiente sustentável e sofisticado — ideal para gravações noturnas.",
  },
  {
    id: "kc-penn-valley-park",
    name: "Penn Valley Park",
    category: "park",
    address: "4800 Penn Valley Dr, Kansas City, MO 64108",
    area: "Downtown / Westside",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.5,
    reviewCount: "1.500+",
    hours: "Diariamente 6h–23h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Kansas City Film Office — filmkc.com",
    tips:
      "Parque urbano com boa vegetação e vistas para o Memorial Liberty. A 20 min a pé do hotel ou 8 min de RideKC Streetcar. Permit via Kansas City Film Office (filmkc.com).",
  },
  {
    id: "kc-fogo-de-chao",
    name: "Fogo de Chão Kansas City",
    category: "brazilian",
    address: "4951 Wyoming St, Kansas City, MO 64112",
    area: "Country Club Plaza",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.7,
    reviewCount: "3.800+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "No Country Club Plaza — área de compras europeia única nos EUA. A ~12 min de Uber do hotel. Ambiente elegante, bom para gravações internas. Negociar com a gerência.",
  },
  {
    id: "kc-percheron",
    name: "Percheron Rooftop",
    category: "rooftop",
    address: "2101 Central St, Kansas City, MO 64108",
    area: "Crossroads / Midtown",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.5,
    reviewCount: "900+",
    hours: "17h–0h (Ter–Qui) · 17h–2h (Sex–Sáb) · 14h–22h (Dom) · Fechado Seg",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Percheron",
    tips:
      "Rooftop no Crossroads Arts District — bairro mais criativo de KC. Vista do skyline e dos murais do distrito. A ~15 min do Hotel Phillips de Uber. Ambiente descontraído com coquetéis. Contatar gerência para janela comercial.",
  },
  {
    id: "kc-horsefeather",
    name: "Horsefeather Social",
    category: "rooftop",
    address: "1515 Wyandotte St, Kansas City, MO 64108",
    area: "Crossroads Arts District",
    cidade: "kansas-city",
    cidadeLabel: "Kansas City MO",
    periodo: "15–17 jun",
    rating: 4.7,
    reviewCount: "1.200+",
    hours: "16h–23h (Seg–Qui) · 16h–1h (Sex–Sáb) · 14h–21h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Horsefeather",
    tips:
      "Considerado o melhor rooftop bar de Kansas City — 4.7★. No Crossroads Arts District, a ~15 min do Hotel Phillips de Uber. Vista do skyline de KC. Ambiente acolhedor com cardápio criativo. Contatar gerência com antecedência para uso comercial.",
  },

  // ── Philadelphia · 17–19 · 22–23 jun ─────────────────────────
  {
    id: "phl-love-park",
    name: "Love Park / JFK Plaza",
    category: "park",
    address: "1500 JFK Blvd, Philadelphia, PA 19102",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia PA",
    periodo: "17–19 · 22–23 jun",
    rating: 4.5,
    reviewCount: "18.000+",
    hours: "24h (área externa)",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Philadelphia Film Office — film.org",
    tips:
      "Praça icônica com a escultura LOVE — símbolo de Philadelphia. A 8 min a pé do hotel. Permit via Philadelphia Film Office (film.org) — gratuito para espaços públicos, prazo 5–10 dias.",
  },
  {
    id: "phl-assembly-rooftop",
    name: "Assembly Rooftop at Logan Hotel",
    category: "rooftop",
    address: "1 Logan Square, Philadelphia, PA 19103",
    area: "Logan Square",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia PA",
    periodo: "17–19 · 22–23 jun",
    rating: 4.6,
    reviewCount: "2.800+",
    hours: "16h–0h (Seg–Qui) · 16h–1h (Sex–Sáb) · 14h–22h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Logan Hotel",
    tips:
      "Rooftop com vista para a Logan Circle Fountain e o skyline. A 10 min a pé do hotel. Ambiente sofisticado — ideal para gravações ao entardecer e noturnas.",
  },
  {
    id: "phl-one-liberty",
    name: "One Liberty Observation Deck",
    category: "observatory",
    address: "1650 Market St, Philadelphia, PA 19103",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia PA",
    periodo: "17–19 · 22–23 jun",
    rating: 4.5,
    reviewCount: "4.500+",
    hours: "10h–21h (Seg–Qui) · 10h–22h (Sex–Sáb) · 10h–20h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Ingresso ~$20 por pessoa",
    permit: "venue_specific",
    permitNote: "Contato: libertyone.com",
    tips:
      "Vista de 360° de Philadelphia do 57º andar. A 8 min a pé do hotel. Pontos icônicos visíveis: Lincoln Financial Field, Delaware River, centro histórico. Contato comercial via libertyone.com.",
  },
  {
    id: "phl-fogo-de-chao",
    name: "Fogo de Chão Philadelphia",
    category: "brazilian",
    address: "1337 Chestnut St, Philadelphia, PA 19107",
    area: "Center City",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia PA",
    periodo: "17–19 · 22–23 jun",
    rating: 4.6,
    reviewCount: "6.500+",
    hours: "Seg–Sex 11h30–22h · Sáb 12h–22h · Dom 12h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "none",
    tips:
      "A 5 min a pé do hotel — localização ideal para gravações rápidas. Ambiente elegante, iluminação controlada, boa acústica. Negociar janela de produção com a gerência.",
  },
  {
    id: "phl-xfinity-live",
    name: "Xfinity Live! Philadelphia",
    category: "sports_bar",
    address: "1100 Pattison Ave, Philadelphia, PA 19148",
    area: "South Philadelphia / Sports Complex",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia PA",
    periodo: "17–19 · 22–23 jun",
    rating: 4.4,
    reviewCount: "9.000+",
    hours: "11h–2h (todos os dias)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Maior sports complex do Nordeste dos EUA — 5 bares em um complexo próximo ao Lincoln Financial Field. Energia máxima em dias de Copa. A 20 min de SEPTA Broad Street Line.",
  },
  {
    id: "phl-attico",
    name: "Attico Rooftop",
    category: "rooftop",
    address: "219 S Broad St, Philadelphia, PA 19107",
    area: "Center City / Broad Street Corridor",
    cidade: "philadelphia",
    cidadeLabel: "Philadelphia PA",
    periodo: "17–19 · 22–23 jun",
    rating: 4.6,
    reviewCount: "1.800+",
    hours: "17h–0h (Ter–Qui) · 17h–1h (Sex–Sáb) · 14h–22h (Dom) · Fechado Seg",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Attico Rooftop",
    tips:
      "Rooftop elegante no coração do Broad Street Corridor com vista para o skyline de Philadelphia. A ~10 min a pé do hotel. Iluminação sofisticada — ideal para gravações ao entardecer e noturnas. Negociar janela comercial com antecedência.",
  },

  // ── Miami · 23–28 jun ─────────────────────────────────────────
  {
    id: "mia-margaret-pace",
    name: "Margaret Pace Park",
    category: "park",
    address: "1745 N Bayshore Dr, Miami, FL 33132",
    area: "Edgewater / Wynwood",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "23–28 jun",
    rating: 4.6,
    reviewCount: "4.000+",
    hours: "Diariamente 6h–23h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Miami-Dade Film Office — filmiami.org",
    tips:
      "Parque à beira da Baía de Biscayne com vista para Miami Beach e Downtown. A 10 min a pé do hotel. Permit via Miami-Dade Film Office (filmiami.org) — prazo de 5 dias úteis.",
  },
  {
    id: "mia-broken-shaker",
    name: "The Broken Shaker at Freehand Miami",
    category: "rooftop",
    address: "2727 Indian Creek Dr, Miami Beach, FL 33140",
    area: "Miami Beach",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "23–28 jun",
    rating: 4.5,
    reviewCount: "5.500+",
    hours: "15h–0h (Seg–Qui) · 15h–2h (Sex) · 13h–2h (Sáb) · 13h–0h (Dom)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Miami Beach Film Office + negociar com o local",
    tips:
      "Rooftop e pool deck do Freehand Miami — um dos bares mais premiados dos EUA. Vista para Miami Beach e o Atlântico. A 20 min do hotel de Uber. Negociar uso comercial com a gerência.",
  },
  {
    id: "mia-skyviews-wheel",
    name: "Skyviews Miami Observation Wheel",
    category: "observatory",
    address: "401 Biscayne Blvd, Miami, FL 33132",
    area: "Bayside / Downtown",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "23–28 jun",
    rating: 4.4,
    reviewCount: "3.200+",
    hours: "11h–23h (Dom–Qui) · 11h–0h (Sex–Sáb)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Ingresso ~$18–22 por pessoa",
    permit: "venue_specific",
    permitNote: "Contato: skyviewsmiami.com",
    tips:
      "Roda-gigante de 60m com vista para a Baía de Biscayne, Brickell e Miami Beach. A 15 min do hotel de Metrorail. Gôndolas climatizadas. Contato para uso comercial: skyviewsmiami.com.",
  },
  {
    id: "mia-boteco",
    name: "Boteco Miami",
    category: "brazilian",
    address: "916 NE 79th St, Miami, FL 33138",
    area: "Upper East Side / Wynwood Norte",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "23–28 jun",
    rating: 4.5,
    reviewCount: "2.800+",
    hours: "12h–23h (Seg–Qui) · 12h–1h (Sex–Sáb) · 12h–22h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    permit: "none",
    tips:
      "Bar e botequim brasileiro autêntico no coração da comunidade brasileira de Miami. A 15 min do hotel de Uber. Música ao vivo, petiscos brasileiros, atmosfera de botequim carioca. Ótimo para conteúdo cultural.",
  },
  {
    id: "mia-wharf",
    name: "The Wharf Miami",
    category: "sports_bar",
    address: "114 SW North River Dr, Miami, FL 33130",
    area: "Downtown / Brickell",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "23–28 jun",
    rating: 4.4,
    reviewCount: "8.500+",
    hours: "12h–0h (Seg–Qui) · 12h–2h (Sex–Sáb) · 12h–23h (Dom)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    permit: "none",
    tips:
      "Complexo outdoor à beira do Rio Miami com múltiplos bares e área esportiva. Vista para Brickell. A 20 min do hotel de Metrorail. Energia alta em dias de Copa — ótimo para gravações ao vivo.",
  },
  {
    id: "mia-cc-rooftop",
    name: "CC Rooftop Social Club",
    category: "rooftop",
    address: "255 NW 25th St, Miami, FL 33127",
    area: "Wynwood",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "23–28 jun",
    rating: 4.8,
    reviewCount: "2.500+",
    hours: "17h–0h (Qua–Qui) · 17h–2h (Sex) · 14h–2h (Sáb) · 14h–22h (Dom) · Fechado Seg–Ter",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do CC Rooftop",
    tips:
      "O rooftop mais bem avaliado de Miami — 4.8★. Pool rooftop com vista incrível para Wynwood e o skyline de Miami. A ~5 min do hotel de Uber. Ambiente animado com música ao vivo. Negociar janela exclusiva para gravações comerciais.",
  },
  {
    id: "mia-elevar",
    name: "Elevar Wynwood",
    category: "rooftop",
    address: "3400 Biscayne Blvd, Miami, FL 33137",
    area: "Edgewater / Wynwood",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "23–28 jun",
    rating: 4.3,
    reviewCount: "1.600+",
    hours: "17h–23h (Ter–Qui) · 17h–1h (Sex) · 14h–1h (Sáb) · 14h–22h (Dom) · Fechado Seg",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Negociar com a gerência do Elevar",
    tips:
      "Rooftop literalmente a 1 min a pé do hotel — opção mais conveniente para gravações rápidas. Vista para a Baía de Biscayne e o skyline de Miami. Ambiente descontraído com boa iluminação noturna. Contato com gerência para uso comercial.",
  },
];
