import type { CityConfig } from "./types-deslocamentos";

export const BH_CONFIG: CityConfig = {
  id: "bh",
  emoji: "🐷",
  cidade: "Belo Horizonte",
  periodo: "Brasileirão",
  contatoLocal: {
    nome: "Gabriel Marques",
    telefone: "+55 31 9694-8181",
  },
  origins: [
    {
      id: "hotel",
      name: "Hilton Garden Inn BH",
      addr: "Av. Prudente de Morais, 520, Cidade Jardim, Belo Horizonte - MG, 30380-002",
      lat: -19.9373,
      lng: -43.9472,
    },
  ],
  destinations: [
    {
      id: "mineirao",
      name: "Mineirão",
      addr: "Av. Antônio Abrahão Caram, 1001, São José, Belo Horizonte - MG, 31275-000",
      lat: -19.8659,
      lng: -43.971,
      category: "estadio",
    },
    {
      id: "confins",
      name: "Aeroporto de Confins (CNF)",
      addr: "Rod. LMG-800, km 7,9, Confins - MG, 33500-900",
      lat: -19.6357,
      lng: -43.9669,
      category: "aeroporto",
    },
    {
      id: "liberdade",
      name: "Praça da Liberdade",
      addr: "Praça da Liberdade, s/n, Funcionários, Belo Horizonte - MG, 30140-010",
      lat: -19.9321,
      lng: -43.9381,
      category: "ponto_turistico",
    },
    {
      id: "sao-francisco-pampulha",
      name: "Igreja São Francisco (Pampulha)",
      addr: "Av. Otacílio Negrão de Lima, 3000, Pampulha, Belo Horizonte - MG, 31365-450",
      lat: -19.8583,
      lng: -43.9789,
      category: "ponto_turistico",
    },
    {
      id: "praca-do-papa",
      name: "Praça do Papa",
      addr: "Av. Agulhas Negras, s/n, Mangabeiras, Belo Horizonte - MG, 30210-060",
      lat: -19.9575,
      lng: -43.9146,
      category: "outro",
    },
    {
      id: "xapuri",
      name: "Restaurante Xapuri",
      addr: "R. Mandacaru, 260, Trevo/Pampulha, Belo Horizonte - MG",
      lat: -19.8417,
      lng: -44.0036,
      category: "outro",
    },
  ],
  routes: [
    {
      from: "hotel",
      to: "mineirao",
      carN: "20–25 min",
      carH: "50–70 min",
      tp: "Sem linha direta; ônibus municipais reforçados em dia de jogo",
      dist: "10,8 km",
      diff: "dificil",
      costCar: "~R$15",
      costTp: "~R$5,50",
      note: "Acesso trava 1h30–2h antes/depois do jogo (desvios da BHTrans)",
    },
    {
      from: "hotel",
      to: "confins",
      carN: "45–55 min",
      carH: "1h20–1h40",
      tp: "Ônibus executivo (Terminal Rodoviário/Estação Central) ~1h15–1h40",
      dist: "43,9 km",
      diff: "dificil",
      costCar: "~R$45",
      costTp: "~R$24",
      note: "BR-040/Anel Rodoviário congestiona 7h–9h e 17h–19h30",
    },
    {
      from: "hotel",
      to: "liberdade",
      carN: "8–10 min",
      carH: "15–20 min",
      tp: "Várias linhas + caminhável (~15 min)",
      dist: "2,4 km",
      diff: "facil",
      costCar: "~R$4",
      costTp: "~R$5,50",
    },
    {
      from: "hotel",
      to: "sao-francisco-pampulha",
      carN: "20–25 min",
      carH: "35–45 min",
      tp: "Sem linha direta; baldeação necessária",
      dist: "11,5 km",
      diff: "moderado",
      costCar: "~R$14",
      costTp: "~R$8",
    },
    {
      from: "hotel",
      to: "praca-do-papa",
      carN: "12–15 min",
      carH: "20–30 min",
      tp: "Não disponível — subida, recomendado carro/app",
      dist: "5,7 km",
      diff: "moderado",
      costCar: "~R$8",
      costTp: "Não disponível",
    },
    {
      from: "hotel",
      to: "xapuri",
      carN: "28–35 min",
      carH: "50–65 min",
      tp: "Sem linha direta",
      dist: "16,6 km",
      diff: "dificil",
      costCar: "~R$20",
      costTp: "Não disponível",
    },
  ],
  alerts: [
    {
      category: "estadio",
      text: "Acesso ao Mineirão trava 1h30–2h antes e depois do jogo. A BHTrans faz desvios na região em dias de jogo.",
    },
    {
      category: "aeroporto",
      text: "Trajeto ao Confins (~44 km) é o mais longo da cidade. Reserve ao menos 1h no trânsito normal, mais em pico.",
    },
    {
      category: "transito",
      text: "BR-040/Anel Rodoviário (rota do aeroporto) congestiona nos picos 7h–9h e 17h–19h30.",
    },
    {
      category: "geral",
      text: "Topografia de morros deixa Mangabeiras e Praça do Papa mais lentos do que a distância sugere.",
    },
    {
      category: "geral",
      text: "BH tem só uma linha de metrô, que não serve nenhum destino mapeado — considere carro/app para a maioria das rotas.",
    },
    {
      category: "seguranca",
      text: "Entorno do Mineirão fica bem movimentado em dia de jogo, mas esvazia rápido depois — evite ficar sozinho aguardando transporte na saída, prefira sair em grupo ou de app.",
    },
  ],
};
