import type { CityConfig } from "./types-deslocamentos";

export const CHAPECO_CONFIG: CityConfig = {
  id: "chapeco",
  emoji: "🌽",
  cidade: "Chapecó",
  periodo: "Brasileirão",
  contatoLocal: {
    nome: "Paulo César",
    telefone: "+55 49 8804-5434",
  },
  origins: [
    {
      id: "hotel",
      name: "Mogano Premium Hotel",
      addr: "Av. Fernando Machado, 574, Centro, Chapecó - SC, 89814-210",
      lat: -27.0975,
      lng: -52.6188,
    },
  ],
  destinations: [
    {
      id: "arena-conda",
      name: "Arena Condá",
      addr: "Rua Clevelândia, 656, Centro, Chapecó - SC, 89801-561",
      lat: -27.0938,
      lng: -52.6122,
      category: "estadio",
    },
    {
      id: "aeroporto-xap",
      name: "Aeroporto de Chapecó (XAP)",
      addr: "Rua Atílio Fonta, 2400, Efapi, Chapecó - SC, 89809-000",
      lat: -27.1345,
      lng: -52.6685,
      category: "aeroporto",
    },
    {
      id: "praca-bertaso",
      name: "Praça Coronel Bertaso",
      addr: "Centro, Chapecó - SC",
      lat: -27.0965,
      lng: -52.618,
      category: "ponto_turistico",
    },
    {
      id: "monumento-desbravador",
      name: "Monumento O Desbravador",
      addr: "Av. Getúlio Vargas, Centro, Chapecó - SC",
      lat: -27.0985,
      lng: -52.616,
      category: "ponto_turistico",
    },
    {
      id: "parque-palmeiras",
      name: "Parque das Palmeiras",
      addr: "Rua Marechal Mascarenhas de Moraes, Parque das Palmeiras, Chapecó - SC",
      lat: -27.121,
      lng: -52.6295,
      category: "outro",
    },
  ],
  routes: [
    {
      from: "hotel",
      to: "arena-conda",
      carN: "4–7 min",
      carH: "10–18 min",
      tp: "Caminhável (~15–18 min) ou ônibus municipal",
      dist: "1,3 km",
      diff: "moderado",
      costCar: "~R$4",
      costTp: "~R$4,50",
      note: "Ruas ao redor bloqueadas em dias de jogo — chegar com antecedência",
    },
    {
      from: "hotel",
      to: "aeroporto-xap",
      carN: "15–20 min",
      carH: "25–35 min",
      tp: "Sem linha direta — táxi/app é a opção mais confiável",
      dist: "9 km",
      diff: "moderado",
      costCar: "~R$22",
      costTp: "Não disponível",
      note: "Aeroporto pequeno, poucos voos diários — confirmar horário com antecedência",
    },
    {
      from: "hotel",
      to: "praca-bertaso",
      carN: "2–4 min",
      carH: "5–8 min",
      tp: "Caminhável (~8 min)",
      dist: "0,6 km",
      diff: "facil",
      costCar: "~R$3",
      costTp: "Caminhável",
    },
    {
      from: "hotel",
      to: "monumento-desbravador",
      carN: "3–5 min",
      carH: "6–10 min",
      tp: "Caminhável (~12 min)",
      dist: "0,9 km",
      diff: "facil",
      costCar: "~R$3",
      costTp: "Caminhável",
    },
    {
      from: "hotel",
      to: "parque-palmeiras",
      carN: "10–14 min",
      carH: "18–25 min",
      tp: "Ônibus municipal (poucas linhas)",
      dist: "5 km",
      diff: "moderado",
      costCar: "~R$9",
      costTp: "~R$4,50",
    },
  ],
  alerts: [
    {
      category: "estadio",
      text: "Ruas ao redor da Arena Condá fecham para trânsito 1h30–2h antes e depois do jogo. Ir a pé ou de app é mais rápido do que carro próprio.",
    },
    {
      category: "aeroporto",
      text: "O Aeroporto de Chapecó (XAP) tem poucos voos diários. Confirme horários com antecedência — não há alternativa de última hora na mesma noite.",
    },
    {
      category: "transito",
      text: "Chapecó é uma cidade pequena e compacta — a maior parte do Centro fica a poucos minutos a pé ou de carro, sem grandes congestionamentos fora de dias de jogo.",
    },
    {
      category: "geral",
      text: "Transporte público é limitado fora do Centro. Para o aeroporto e o Parque das Palmeiras, carro ou aplicativo é a opção mais confiável.",
    },
    {
      category: "seguranca",
      text: "Cidade pequena e tranquila em geral — atenção normal recomendada perto da Arena Condá em dia de jogo, quando o movimento de torcida aumenta bastante nas ruas do entorno.",
    },
  ],
};
