import type { LocationCategory, DayNight, CostLevel } from "@/lib/locations";

export type PortugalLocPermit = "none" | "film_office" | "venue_specific";

export const PORTUGAL_LOC_PERMIT_LABEL: Record<
  PortugalLocPermit,
  { label: string; tone: "green" | "amber" | "orange" }
> = {
  none:           { label: "Sem permit",           tone: "green"  },
  film_office:    { label: "Film Office local",    tone: "amber"  },
  venue_specific: { label: "Negociar com o local", tone: "orange" },
};

export interface PortugalVenueItem {
  id: string;
  name: string;
  category: LocationCategory;
  address: string;
  area: string;
  cidade: "cdmx" | "miami" | "houston";
  cidadeLabel: string;
  periodo: string;
  rating: number;
  reviewCount: string;
  hours: string;
  goodDay: DayNight;
  goodNight: DayNight;
  cost: CostLevel;
  costNote?: string;
  permit: PortugalLocPermit;
  permitNote?: string;
  tips: string;
}

export const PORTUGAL_VENUES: PortugalVenueItem[] = [

  // ── Cidade do México · 08–12 jun ─────────────────────────────
  {
    id: "cdmx-torre-latinoamericana",
    name: "Torre Latinoamericana — Mirador",
    category: "observatory",
    address: "Eje Central Lázaro Cárdenas 2, Centro Histórico, CDMX 06010",
    area: "Centro Histórico",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "08–12 jun",
    rating: 4.4,
    reviewCount: "25.000+",
    hours: "Seg–Dom 09h30–22h (última subida 21h30)",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$",
    costNote: "Adulto: ~$100 MXN (~$6 USD). Bilhete online recomendado para evitar fila.",
    permit: "venue_specific",
    permitNote: "Contato com administração da torre para filmagem comercial.",
    tips:
      "Vista 360° do skyline de CDMX do alto de um dos edifícios mais icônicos do México — 44 andares de observação. A 20 min de carro do hotel (Metrô Bellas Artes, L2/L8, ~15 min / $6 MXN). Visual de dia e à noite com as luzes da cidade. Imprescindível para entradas ao vivo com skyline da Cidade do México.",
  },
  {
    id: "cdmx-chapultepec",
    name: "Bosque de Chapultepec",
    category: "park",
    address: "Bosque de Chapultepec, Cuauhtémoc, CDMX 11580",
    area: "Chapultepec",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "08–12 jun",
    rating: 4.7,
    reviewCount: "45.000+",
    hours: "Ter–Dom 05h–18h (fechado segunda-feira)",
    goodDay: "yes",
    goodNight: "no",
    cost: "free",
    permit: "film_office",
    permitNote: "Comisión de Filmaciones de la CDMX (filmaciones.cdmx.gob.mx) para filmagem comercial.",
    tips:
      "O maior parque urbano da Cidade do México — 686 hectares com lagos, o Museu Nacional de Antropologia e o Castelo de Chapultepec. A 10 min de carro do hotel / 20 min a pé pela Reforma. Excelente para externas com backdrop verde e cultural. Atenção: fechado às segundas. Não recomendado para gravações noturnas.",
  },
  {
    id: "cdmx-balcon-zocalo",
    name: "Balcón del Zócalo — Hotel Zócalo Central",
    category: "rooftop",
    address: "Av. 5 de Mayo 61, Centro Histórico, CDMX 06010",
    area: "Centro Histórico / Zócalo",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "08–12 jun",
    rating: 4.5,
    reviewCount: "8.500+",
    hours: "Seg–Dom 12h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    costNote: "Consumação obrigatória. Reserva antecipada recomendada para horários noturnos.",
    permit: "venue_specific",
    permitNote: "Negociar diretamente com o hotel para uso editorial — tarifa a definir.",
    tips:
      "O rooftop mais icônico do Centro Histórico — vista privilegiada da Catedral Metropolitana e da Plaza del Zócalo. A 20 min de Uber do hotel. Backdrop histórico único: impossível de replicar em qualquer outra cidade. Reservar com antecedência. Uso editorial: contato com gerência do hotel.",
  },
  {
    id: "cdmx-fogo-de-chao",
    name: "Fogo de Chão Mexico City",
    category: "brazilian",
    address: "Presidente Masaryk 360, Polanco, CDMX 11560",
    area: "Polanco",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "08–12 jun",
    rating: 4.5,
    reviewCount: "5.500+",
    hours: "Seg–Qui 13h–22h · Sex–Sáb 13h–23h · Dom 13h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência para autorização de câmera no salão.",
    tips:
      "Churrascaria brasileira premium em Polanco — o bairro mais sofisticado de CDMX. A 10 min de Uber do hotel. Ambiente reconhecível para o público brasileiro, frequentado por executivos e turistas internacionais. Reservar com antecedência durante a Copa. Preços em MXN: ~$700–900 MXN por pessoa (~$40–55 USD).",
  },
  {
    id: "cdmx-hard-rock",
    name: "Hard Rock Cafe Mexico City",
    category: "sports_bar",
    address: "Paseo de la Reforma 110, Hipódromo, Cuauhtémoc, CDMX",
    area: "Paseo de la Reforma",
    cidade: "cdmx",
    cidadeLabel: "Cidade do México",
    periodo: "08–12 jun",
    rating: 4.2,
    reviewCount: "12.000+",
    hours: "Dom–Qui 12h–00h · Sex–Sáb 12h–02h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência da unidade para autorização editorial.",
    tips:
      "Sports bar internacional na icônica Reforma — telões, memorabilia e transmissão garantida dos jogos da Copa. A 5 min de carro do hotel na Avenida Reforma. Ideal para coberturas de reação de torcedores e cobertura de jogo. Ambiente Copa consolidado com público turístico e local.",
  },

  // ── Miami FL · 12 jun–01 jul ─────────────────────────────────
  {
    id: "mia-sugar-rooftop",
    name: "Sugar — East Miami Hotel",
    category: "rooftop",
    address: "788 Brickell Plaza, Miami, FL 33131",
    area: "Brickell",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "12 jun–01 jul",
    rating: 4.4,
    reviewCount: "6.500+",
    hours: "Ter–Qui 17h–23h · Sex 17h–00h · Sáb 14h–00h · Dom 14h–22h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$$$",
    costNote: "Consumação mínima; reserva necessária. Acesso ao rooftop com consumação.",
    permit: "venue_specific",
    permitNote: "Contato com gerência do East Miami para filmagem comercial.",
    tips:
      "Rooftop no 40° andar do East Miami Hotel — vista panorâmica de Brickell, Downtown e Biscayne Bay. Na área de referência da base Miami. Um dos melhores rooftops da cidade para entradas ao vivo noturnas com skyline completo. Reservar com antecedência: lotado em semanas de Copa.",
  },
  {
    id: "mia-bayfront-park",
    name: "Bayfront Park",
    category: "park",
    address: "301 Biscayne Blvd, Miami, FL 33132",
    area: "Downtown Miami / Biscayne Bay",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "12 jun–01 jul",
    rating: 4.6,
    reviewCount: "22.000+",
    hours: "Seg–Dom 06h–22h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Miami-Dade Film & Entertainment (filmiami.org) para filmagem comercial.",
    tips:
      "Parque à beira do Biscayne Bay com vista direta do skyline de Miami — palco ao ar livre e espaços gramados. A 15 min de Uber de Brickell. Ponto de encontro da comunidade local com telões para eventos Copa a confirmar. Excelente para externas com skyline ao fundo e atmosfera de cidade.",
  },
  {
    id: "mia-wynwood-walls",
    name: "Wynwood Walls",
    category: "park",
    address: "2516 NW 2nd Ave, Miami, FL 33127",
    area: "Wynwood Arts District",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "12 jun–01 jul",
    rating: 4.7,
    reviewCount: "32.000+",
    hours: "Seg–Qui 11h–21h · Sex–Sáb 11h–22h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "$",
    costNote: "Entrada: ~$12 adulto. Ingresso online recomendado.",
    permit: "venue_specific",
    permitNote: "Negociar com Wynwood Arts para filmagem comercial — tarifa editorial disponível.",
    tips:
      "O museu de street art a céu aberto mais famoso do mundo — murais gigantes de artistas internacionais em bloco ao ar livre. A 12 min de Uber de Brickell. Visual único e altamente fotogênico para gravações externas. Ideal para coberturas de lifestyle da Copa em Miami. Reservar entrada online.",
  },
  {
    id: "mia-frost-science",
    name: "Frost Science Museum — Terraço Biscayne",
    category: "observatory",
    address: "1101 Biscayne Blvd, Miami, FL 33132",
    area: "Museum Park / Downtown",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "12 jun–01 jul",
    rating: 4.7,
    reviewCount: "18.000+",
    hours: "Ter–Dom 09h–17h (sextas até 21h) · Seg fechado",
    goodDay: "yes",
    goodNight: "warning",
    cost: "$$",
    costNote: "Adulto: ~$30. Planetário à parte. Bilhete online com desconto.",
    permit: "venue_specific",
    permitNote: "Contato com Miami-Dade Science Museum Events para filmagem editorial.",
    tips:
      "Museu de ciências premium com terraço aberto sobre o Biscayne Bay — vista panorâmica do skyline de Miami e das ilhas. A 15 min de Uber de Brickell. Planetário com cúpula para eventos especiais. Ótimo para externas de dia com backdrop de água e skyline. Verificar programação Copa no planetário.",
  },
  {
    id: "mia-fogo-de-chao",
    name: "Fogo de Chão Miami Beach",
    category: "brazilian",
    address: "836 1st St, Miami Beach, FL 33139",
    area: "South Beach / Lincoln Road",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "12 jun–01 jul",
    rating: 4.5,
    reviewCount: "7.200+",
    hours: "Seg–Qui 11h30–22h · Sex–Sáb 11h30–23h · Dom 11h–22h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência Miami Beach para autorização editorial.",
    tips:
      "Fogo de Chão no coração de South Beach — espaço amplo a 5 min a pé da praia. A 20 min de Uber de Brickell. Ambiente brasileiro garantido com público turístico internacional durante a Copa. Ideal para gravações de delegação ou almoços de grupo. Reservar com antecedência em semanas de jogo.",
  },
  {
    id: "mia-the-wharf",
    name: "The Wharf Miami",
    category: "sports_bar",
    address: "114 SW North River Dr, Miami, FL 33130",
    area: "Downtown / Little Havana",
    cidade: "miami",
    cidadeLabel: "Miami FL",
    periodo: "12 jun–01 jul",
    rating: 4.4,
    reviewCount: "15.000+",
    hours: "Seg–Qui 11h–02h · Sex–Sáb 11h–03h · Dom 11h–02h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "free",
    costNote: "Entrada gratuita; consumação à parte.",
    permit: "film_office",
    permitNote: "Miami-Dade Film & Entertainment (filmiami.org) para filmagem em área externa.",
    tips:
      "Complexo de bares ao ar livre às margens do Miami River — telões gigantes, live music e ambiente Copa. A 10 min de Uber de Brickell. O sports bar ao ar livre mais popular do Downtown Miami. Transmite jogos em telões durante a Copa. Ambiente festivo garantido em dias de jogo — chegar com antecedência.",
  },

  // ── Houston TX · 15–17 jun + 21–23 jun ──────────────────────
  {
    id: "hou-post-houston",
    name: "POST Houston — Skylawn Rooftop",
    category: "rooftop",
    address: "401 Franklin St, Houston, TX 77002",
    area: "Downtown Houston",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "15–17 jun · 21–23 jun",
    rating: 4.5,
    reviewCount: "5.000+",
    hours: "Qui–Sáb 17h–00h · Dom 12h–20h (verificar agenda de eventos)",
    goodDay: "warning",
    goodNight: "yes",
    cost: "$",
    costNote: "Acesso ao Skylawn gratuito em horários sem evento; taxa em dias de show.",
    permit: "film_office",
    permitNote: "Houston Film Commission (houstonfilmcommission.com) para filmagem comercial.",
    tips:
      "Antigo correio federal transformado em complexo cultural — Skylawn no topo com vista do skyline de Houston. A 8 min de carro do Home2 Suites e do Hampton Inn. Alta versatilidade para entradas ao vivo. Confirmar programação antes: venue para eventos pode restringir acesso em fins de semana.",
  },
  {
    id: "hou-discovery-green",
    name: "Discovery Green",
    category: "park",
    address: "1500 McKinney St, Houston, TX 77010",
    area: "Downtown / Convention Center",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "15–17 jun · 21–23 jun",
    rating: 4.7,
    reviewCount: "20.000+",
    hours: "Seg–Dom 06h–23h",
    goodDay: "yes",
    goodNight: "warning",
    cost: "free",
    permit: "film_office",
    permitNote: "Houston Film Commission para filmagem comercial no parque.",
    tips:
      "Parque urbano a 5 min a pé do Home2 Suites e a 8 min do Hampton Inn — ponto de encontro do Downtown Houston. Palco ao ar livre, lago artificial e alto tráfego de pedestres. Ideal para entrevistas externas e captação de atmosfera local. Transmissões de jogos da Copa a confirmar.",
  },
  {
    id: "hou-fogo-de-chao",
    name: "Fogo de Chão Houston",
    category: "brazilian",
    address: "8250 Westheimer Rd, Houston, TX 77063",
    area: "Galleria / Upper Kirby",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "15–17 jun · 21–23 jun",
    rating: 4.6,
    reviewCount: "6.200+",
    hours: "Seg–Qui 11h30–21h30 · Sex–Sáb 11h30–22h · Dom 11h–21h",
    goodDay: "yes",
    goodNight: "yes",
    cost: "$$$",
    permit: "venue_specific",
    permitNote: "Contato com gerência para autorização de câmera no salão.",
    tips:
      "Churrascaria brasileira premium na Galleria — o mais espaçoso e movimentado de Houston. A 20 min de carro dos hotéis (Uber ~$15). Espaço amplo para gravações de grupo. Reservar com antecedência em semana de Copa.",
  },
  {
    id: "hou-pitch-25",
    name: "Pitch 25 Beer Park",
    category: "sports_bar",
    address: "2120 Walker St, Houston, TX 77003",
    area: "East Downtown / EaDo",
    cidade: "houston",
    cidadeLabel: "Houston TX",
    periodo: "15–17 jun · 21–23 jun",
    rating: 4.4,
    reviewCount: "8.500+",
    hours: "Seg–Qui 14h–00h · Sex 14h–02h · Sáb 11h–02h · Dom 11h–00h",
    goodDay: "warning",
    goodNight: "yes",
    cost: "free",
    costNote: "Entrada gratuita; consumação à parte. Estacionamento gratuito no local.",
    permit: "film_office",
    permitNote: "Houston Film Commission para filmagem comercial na área externa.",
    tips:
      "Complexo ao ar livre com beer garden, mesas de foosball e telões — o sports bar mais amplo do Downtown Houston. A 10 min de carro dos hotéis. Copa: ambiente garantido nos dias de jogo. Estacionamento gratuito — raro no Downtown de Houston.",
  },
];
