export type Difficulty = "facil" | "moderado" | "dificil";

export interface UruguaiRoute {
  destino: string;
  endereco: string;
  carN: string;
  carH: string;
  tp: string;
  dist: string;
  diff: Difficulty;
  mapsUrl: string;
}

export interface UruguaiBase {
  id: string;
  emoji: string;
  cidade: string;
  periodo: string;
  hotel: string;
  hotelAddr: string;
  nota?: string;
  fuso?: string;
  referenciaLabel?: string;
  referenciaAddr?: string;
  routes: UruguaiRoute[];
  transitoInfo?: string[];
  insights: string[];
}

export const URUGUAI_BASES: UruguaiBase[] = [
  // ── BASE 1 — Cancún ───────────────────────────────────────────
  {
    id: "cancun",
    emoji: "🏖",
    cidade: "Cancún",
    periodo: "10–13 jun",
    hotel: "Fairfield Inn & Suites by Marriott Cancún Downtown",
    hotelAddr: "Av. Tulum 220, 77500 Cancún, Q.R., México",
    nota: "Cancún não é sede de jogos da Copa. Base de chegada e período pré-Copa.",
    fuso: "EST (UTC -5h) · BRT = EST +2h | EDT (Miami/Boston) = EST +1h",
    routes: [
      {
        destino: "Aeroporto Cancún (CUN)",
        endereco: "Carr. a Aeropuerto Cancún s/n, 77569 Cancún, Q.R.",
        carN: "15 min",
        carH: "20–30 min",
        tp: "ADO ~$90 MXN / Táxi ~$300–450 MXN / Uber ~$150–200 MXN",
        dist: "16 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Tulum+220,+Cancun&daddr=Carr+a+Aeropuerto+Cancun",
      },
      {
        destino: "Terminal ADO Centro",
        endereco: "Av. Uxmal 5, Centro, 77500 Cancún, Q.R.",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 8 min / $0",
        dist: "0,5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Tulum+220,+Cancun&daddr=Av+Uxmal+5,+Cancun",
      },
      {
        destino: "Zona Hoteleira (Hotel Zone)",
        endereco: "Zona Hotelera, Cancún, Q.R.",
        carN: "20 min",
        carH: "30 min",
        tp: "Ônibus R-1 ~$12 MXN / Uber ~$120–180 MXN",
        dist: "12–20 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Tulum+220,+Cancun&daddr=Zona+Hotelera,+Cancun",
      },
      {
        destino: "Playa del Carmen",
        endereco: "Playa del Carmen, Quintana Roo, México",
        carN: "1h",
        carH: "1h15",
        tp: "ADO ~$180–250 MXN / ~1h",
        dist: "68 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Av+Tulum+220,+Cancun&daddr=Playa+del+Carmen,+Quintana+Roo",
      },
      {
        destino: "Tulum",
        endereco: "Tulum, Quintana Roo, México",
        carN: "1h30",
        carH: "1h45",
        tp: "ADO ~$280–350 MXN / ~2h",
        dist: "130 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Av+Tulum+220,+Cancun&daddr=Tulum,+Quintana+Roo",
      },
      {
        destino: "Chichén Itzá",
        endereco: "Chichén Itzá, Yucatán, México",
        carN: "2h30",
        carH: "2h45",
        tp: "ADO ~$350–500 MXN / ~2h45",
        dist: "200 km",
        diff: "dificil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Tulum+220,+Cancun&daddr=Chichen+Itza,+Yucatan",
      },
      {
        destino: "Miami (próxima base)",
        endereco: "Miami, FL — voo CUN → MIA",
        carN: "—",
        carH: "—",
        tp: "Voo CUN → MIA ~1h30 / $100–350 | CUN → FLL ~1h30 / $80–280",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Tulum+220,+Cancun&daddr=Miami+International+Airport,+FL",
      },
    ],
    transitoInfo: [
      "ADO (ônibus intermunicipal): principal modal entre Cancún, Playa del Carmen e Tulum. Terminal a 500m do hotel na Av. Uxmal.",
      "Ônibus urbano R-1: liga o Downtown à Zona Hoteleira por ~$12 MXN. Frequente durante o dia.",
      "Uber: disponível e bem estruturado em Cancún. Opção recomendada para deslocamentos urbanos.",
      "Táxi credenciado: usar apenas táxis de hotéis ou apps. Evitar táxis irregulares abordados na rua.",
      "⚠️ Aeroporto CUN: Uber/Didi NÃO operam na área de desembarque. Counter de táxi credenciado dentro do terminal (~$300–450 MXN) ou ADO bus (~$90 MXN, ~30 min).",
    ],
    insights: [
      "Aeroporto CUN: Uber e Didi proibidos no desembarque. Counter de táxi credenciado dentro do terminal. ADO saída do aeroporto é opção mais barata.",
      "Terminal ADO está a 500m do hotel — ótimo para traslados ao aeroporto e para Playa del Carmen.",
      "Fuso: Cancún é EST (UTC -5h). BRT = EST +2h | Miami/Boston (EDT) = EST +1h. Cancún não tem horário de verão.",
      "Moeda: México usa MXN. ~1 USD = $17–18 MXN / ~1 BRL = $3,30 MXN. ATMs no hotel e no aeroporto.",
      "Segurança: Centro de Cancún é seguro durante o dia. Evitar ruas desertas à noite fora da área turística.",
      "Uber amplamente disponível em Cancún — recomendado para a maioria dos trajetos urbanos.",
    ],
  },

  // ── BASE 2 — Miami 1ª ─────────────────────────────────────────
  {
    id: "miami-1",
    emoji: "🌴",
    cidade: "Miami 1ª",
    periodo: "13–16 jun",
    hotel: "Airbnb (a confirmar)",
    hotelAddr: "Endereço a confirmar — distâncias a partir de Brickell, Miami como referência",
    nota: "Airbnb pendente — buscas a partir de Brickell, Miami como referência",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Hard Rock Stadium",
    referenciaAddr: "347 Don Shula Dr, Miami Gardens, FL 33056",
    routes: [
      {
        destino: "Hard Rock Stadium (Copa)",
        endereco: "347 Don Shula Dr, Miami Gardens, FL 33056",
        carN: "25 min",
        carH: "35–50 min",
        tp: "Metrorail + shuttle ~40 min / $2,25",
        dist: "23 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=347+Don+Shula+Dr,+Miami+Gardens,+FL",
      },
      {
        destino: "Miami Intl Airport (MIA)",
        endereco: "2100 NW 42nd Ave, Miami, FL 33142",
        carN: "20 min",
        carH: "30–45 min",
        tp: "Metrorail Orange Line ~25 min / $2,25",
        dist: "12 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=2100+NW+42nd+Ave,+Miami,+FL",
      },
      {
        destino: "Fort Lauderdale Airport (FLL)",
        endereco: "100 Terminal Dr, Fort Lauderdale, FL 33315",
        carN: "40 min",
        carH: "55–70 min",
        tp: "Tri-Rail + shuttle ~55 min / $5,25",
        dist: "40 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=100+Terminal+Dr,+Fort+Lauderdale,+FL",
      },
      {
        destino: "Brightline Miami Central",
        endereco: "600 NW 1st Ave, Miami, FL 33136",
        carN: "10 min",
        carH: "15 min",
        tp: "Metrorail/Metromover ~15 min / $2,25",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=600+NW+1st+Ave,+Miami,+FL",
      },
      {
        destino: "Greyhound Miami",
        endereco: "3801 NW 21st St, Miami, FL 33142",
        carN: "15 min",
        carH: "20 min",
        tp: "Metrorail ~20 min / $2,25",
        dist: "9 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=3801+NW+21st+St,+Miami,+FL",
      },
      {
        destino: "South Beach",
        endereco: "South Beach, Miami Beach, FL 33139",
        carN: "20 min",
        carH: "30 min",
        tp: "Metrobus ~30 min / $2,25",
        dist: "10 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=South+Beach,+Miami+Beach,+FL",
      },
      {
        destino: "Wynwood / Brickell",
        endereco: "Wynwood, Miami, FL 33127",
        carN: "10 min",
        carH: "15 min",
        tp: "Metromover gratuito (Brickell) / Uber $10–15",
        dist: "3–5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=Wynwood,+Miami,+FL",
      },
      {
        destino: "Boston (próxima base)",
        endereco: "Boston, MA — voo MIA → BOS",
        carN: "—",
        carH: "—",
        tp: "Voo MIA → BOS ~3h / $100–350 | FLL → BOS ~2h50 / $80–280",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=Boston+Logan+International+Airport,+MA",
      },
    ],
    transitoInfo: [
      "Metrorail: liga MIA Airport ao Downtown Miami em ~25 min / $2,25. Linha Orange.",
      "Metromover: gratuito no Downtown/Brickell. Ótimo para deslocamentos curtos na região central.",
      "Brightline: trem de alta velocidade Miami → Fort Lauderdale (~30 min / $10–20) → Orlando (~3h / $25–79).",
      "Tri-Rail: trem regional Miami → Fort Lauderdale → West Palm Beach. Conecta com Metrorail no Government Center.",
      "Uber/Lyft: amplamente disponíveis. Principal modal para Hard Rock Stadium em dias de jogo.",
      "Hard Rock Stadium em dias de Copa: sem transporte público direto adequado. Uber é obrigatório. Ir 1h30 antes.",
    ],
    insights: [
      "Hard Rock Stadium em dia de Copa: estacionamento caótico. Uber obrigatório. Pedir carro com antecedência.",
      "MIA Airport: aeroporto grande e confuso. Chegar 2h30 (doméstico) ou 3h (internacional) antes.",
      "FLL (Fort Lauderdale): alternativa mais tranquila e geralmente mais barata que MIA para voos domésticos.",
      "Fuso: Miami é EDT (UTC -4h). BRT = EDT +1h. Cancún (EST) = EDT -1h.",
      "Brightline: ótimo para Fort Lauderdale sem depender de carro ou Uber.",
      "Metromover gratuito: cobre Downtown e Brickell — ideal para deslocamentos curtos sem custo.",
    ],
  },

  // ── BASE 3 — Boston ───────────────────────────────────────────
  {
    id: "boston",
    emoji: "🦞",
    cidade: "Boston",
    periodo: "16–20 jun",
    hotel: "The Midtown Hotel MOD Collection by Sonesta",
    hotelAddr: "220 Huntington Ave, Boston, MA 02115",
    nota: "Hóspedes: Lais Amorim · Dayana Natale · Weverson da Silva · João Pedro Rodrigues",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Gillette Stadium",
    referenciaAddr: "1 Patriot Pl, Foxborough, MA 02035",
    routes: [
      {
        destino: "Gillette Stadium (Copa)",
        endereco: "1 Patriot Pl, Foxborough, MA 02035",
        carN: "40 min",
        carH: "55–80 min",
        tp: "Commuter Rail + shuttle ~80 min / $15",
        dist: "56 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=1+Patriot+Pl,+Foxborough,+MA",
      },
      {
        destino: "Boston Logan (BOS)",
        endereco: "1 Harborside Dr, Boston, MA 02128",
        carN: "20 min",
        carH: "30–45 min",
        tp: "Green E → Orange → Blue (Airport) ~45 min / $2,40",
        dist: "10 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=East+Boston,+MA+02128",
      },
      {
        destino: "Back Bay Station (Amtrak)",
        endereco: "145 Dartmouth St, Boston, MA 02116",
        carN: "5 min",
        carH: "8 min",
        tp: "A pé 8 min / $0",
        dist: "0,6 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=145+Dartmouth+St,+Boston,+MA",
      },
      {
        destino: "South Station (Amtrak + bus)",
        endereco: "700 Atlantic Ave, Boston, MA 02110",
        carN: "15 min",
        carH: "20 min",
        tp: "Green E → Orange ~20 min / $2,40",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=700+Atlantic+Ave,+Boston,+MA",
      },
      {
        destino: "Symphony Station (T Green E)",
        endereco: "Symphony, Boston, MA 02115",
        carN: "3 min",
        carH: "5 min",
        tp: "A pé 5 min / $0",
        dist: "0,4 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Symphony+Station,+Boston,+MA",
      },
      {
        destino: "Fenway Park",
        endereco: "4 Jersey St, Boston, MA 02215",
        carN: "5 min",
        carH: "8 min",
        tp: "Green D ~8 min / $2,40",
        dist: "2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=4+Jersey+St,+Boston,+MA",
      },
      {
        destino: "Newbury Street",
        endereco: "Newbury St, Boston, MA 02116",
        carN: "8 min",
        carH: "10 min",
        tp: "A pé 15 min / $0",
        dist: "1,2 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Newbury+St,+Boston,+MA",
      },
      {
        destino: "Miami (próxima base)",
        endereco: "Miami, FL — voo BOS → MIA",
        carN: "—",
        carH: "—",
        tp: "Voo BOS → MIA ~3h / $100–350 | BOS → FLL ~2h50 / $80–280",
        dist: "—",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=220+Huntington+Ave,+Boston,+MA&daddr=Miami+International+Airport,+FL",
      },
    ],
    transitoInfo: [
      "Estação mais próxima do hotel: Symphony (Green Line E) — a 5 min a pé.",
      "Back Bay Station (Amtrak + Orange Line) — a 8 min a pé. Hub para Commuter Rail rumo ao Gillette.",
      "Hasta Logan (BOS): Green E → Orange Line → Blue Line (Airport) — ~45 min / $2,40.",
      "Gillette Stadium: Back Bay Station → Commuter Rail Providence/Stoughton Line → Canton Junction + shuttle Copa em dias de jogo. Tempo total ~75–80 min / ~$15.",
      "Tarifa MBTA: $2,40 por viagem. Cartão CharlieCard recomendado.",
      "⚠️ Gillette em dias de Copa: trens lotam. Sair pelo menos 2h30 antes do jogo.",
    ],
    insights: [
      "Back Bay Station a 8 min a pé — usar para Amtrak e Commuter Rail (Gillette). Estação de referência da base.",
      "Gillette Stadium em dia de Copa: Commuter Rail obrigatório. Trens lotam — sair 2h30 antes do jogo.",
      "Boston Logan (BOS): chegar 2h30 (doméstico) ou 3h (internacional) antes do voo.",
      "Fuso: Boston é EDT (UTC -4h). BRT = EDT +1h. Mesmo fuso que Miami.",
      "Symphony Station a 5 min a pé — acesso direto ao MBTA Green Line E para toda a cidade.",
      "Commuter Rail para Gillette: saída da Back Bay ou South Station, linha Providence/Stoughton até Canton Junction.",
    ],
  },

  // ── BASE 4 — Miami 2ª ─────────────────────────────────────────
  {
    id: "miami-2",
    emoji: "🌴",
    cidade: "Miami 2ª",
    periodo: "20–24 jun",
    hotel: "Airbnb (a confirmar)",
    hotelAddr: "Endereço a confirmar — distâncias a partir de Brickell, Miami como referência",
    nota: "Airbnb pendente — mesmos deslocamentos da Miami 1ª (Base 2)",
    fuso: "EDT (UTC -4h) · BRT = EDT +1h",
    referenciaLabel: "Estádio Copa: Hard Rock Stadium",
    referenciaAddr: "347 Don Shula Dr, Miami Gardens, FL 33056",
    routes: [
      {
        destino: "Hard Rock Stadium (Copa)",
        endereco: "347 Don Shula Dr, Miami Gardens, FL 33056",
        carN: "25 min",
        carH: "35–50 min",
        tp: "Metrorail + shuttle ~40 min / $2,25",
        dist: "23 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=347+Don+Shula+Dr,+Miami+Gardens,+FL",
      },
      {
        destino: "Miami Intl Airport (MIA)",
        endereco: "2100 NW 42nd Ave, Miami, FL 33142",
        carN: "20 min",
        carH: "30–45 min",
        tp: "Metrorail Orange Line ~25 min / $2,25",
        dist: "12 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=2100+NW+42nd+Ave,+Miami,+FL",
      },
      {
        destino: "Fort Lauderdale Airport (FLL)",
        endereco: "100 Terminal Dr, Fort Lauderdale, FL 33315",
        carN: "40 min",
        carH: "55–70 min",
        tp: "Tri-Rail + shuttle ~55 min / $5,25",
        dist: "40 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=100+Terminal+Dr,+Fort+Lauderdale,+FL",
      },
      {
        destino: "Brightline Miami Central",
        endereco: "600 NW 1st Ave, Miami, FL 33136",
        carN: "10 min",
        carH: "15 min",
        tp: "Metrorail/Metromover ~15 min / $2,25",
        dist: "5 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=600+NW+1st+Ave,+Miami,+FL",
      },
      {
        destino: "South Beach",
        endereco: "South Beach, Miami Beach, FL 33139",
        carN: "20 min",
        carH: "30 min",
        tp: "Metrobus ~30 min / $2,25",
        dist: "10 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=South+Beach,+Miami+Beach,+FL",
      },
      {
        destino: "Guadalajara (próxima base)",
        endereco: "Guadalajara, México — voo MIA → GDL",
        carN: "—",
        carH: "—",
        tp: "Voo MIA → GDL direto ~3h30 / $200–500 | Via conexão ~5–7h / $150–380",
        dist: "—",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Brickell,+Miami,+FL&daddr=Guadalajara,+Mexico",
      },
    ],
    transitoInfo: [
      "Mesmos modais da Miami 1ª (Base 2). Metrorail, Metromover, Brightline e Uber disponíveis.",
      "Metrorail Orange Line: liga MIA Airport ao Downtown em ~25 min / $2,25.",
      "Metromover: gratuito no Downtown/Brickell.",
      "Brightline: Miami → Fort Lauderdale (~30 min / $10–20).",
      "⚠️ MIA para voos internacionais (MIA → GDL): usar MIA, não FLL. Chegar 3h antes do voo.",
    ],
    insights: [
      "Conexão Miami → Guadalajara (24 jun): voo MIA → GDL direto ~3h30. Chegar 3h antes ao terminal internacional.",
      "MIA Airport: chegar 3h antes para voos internacionais (MIA → GDL). Não usar FLL para este trecho.",
      "Hard Rock Stadium em dia de Copa: Uber obrigatório. Pedir carro com antecedência.",
      "Fuso: Miami é EDT (UTC -4h). BRT = EDT +1h. Guadalajara (CDT) = EDT -1h.",
      "Brightline: ótimo para Fort Lauderdale. Para voos internacionais, ir direto à MIA.",
      "Uber/Lyft amplamente disponíveis em Miami — principal modal para Hard Rock Stadium.",
    ],
  },

  // ── BASE 5 — Guadalajara ──────────────────────────────────────
  {
    id: "guadalajara",
    emoji: "🌮",
    cidade: "Guadalajara",
    periodo: "24–28 jun",
    hotel: "Becquer Hotel Guadalajara",
    hotelAddr: "Av. Guadalupe 596, Chapalita, 44500 Guadalajara, Jal., México",
    nota: "Uber e Didi proibidos no desembarque do aeroporto GDL — usar táxi credenciado do counter oficial dentro do terminal.",
    fuso: "CDT (UTC -5h) · BRT = CDT +2h | EDT (Miami/Boston) = CDT +1h",
    referenciaLabel: "Estádio Copa: Estadio Akron",
    referenciaAddr: "Cto. J.V.C. 2800, El Bajío, 45014 Zapopan, Jal.",
    routes: [
      {
        destino: "Estadio Akron (Copa)",
        endereco: "Cto. J.V.C. 2800, El Bajío, 45014 Zapopan, Jal.",
        carN: "20 min",
        carH: "30–45 min",
        tp: "Uber ~$150–250 MXN / Táxi ~$350–450 MXN",
        dist: "18 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Cto+JVC+2800,+El+Bajío,+Zapopan",
      },
      {
        destino: "Aeroporto GDL (Miguel Hidalgo)",
        endereco: "Carr. Guadalajara-Chapala km 17.5, Jalisco",
        carN: "25 min",
        carH: "35 min",
        tp: "Táxi oficial do counter ~$350–500 MXN / Uber ~$150–200 MXN (fora do terminal)",
        dist: "20 km",
        diff: "moderado",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Carr+Guadalajara-Chapala+km+17.5,+Jalisco",
      },
      {
        destino: "Terminal Nueva Central de Autobuses",
        endereco: "Av. de las Torres 4831, San Pedro Tlaquepaque, Jal.",
        carN: "20 min",
        carH: "30 min",
        tp: "Uber ~$100–150 MXN / Táxi ~$200–300 MXN",
        dist: "15 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Av+de+las+Torres+4831,+San+Pedro+Tlaquepaque",
      },
      {
        destino: "Centro Histórico de Guadalajara",
        endereco: "Centro Histórico, Guadalajara, Jal.",
        carN: "15 min",
        carH: "25 min",
        tp: "Uber ~$80–120 MXN / Metrô Linha 1 ~30 min / $10,50 MXN",
        dist: "10 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Centro+Historico,+Guadalajara",
      },
      {
        destino: "Tlaquepaque (artesanato)",
        endereco: "San Pedro Tlaquepaque, Jalisco, México",
        carN: "20 min",
        carH: "30 min",
        tp: "Uber ~$100–150 MXN",
        dist: "12 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=San+Pedro+Tlaquepaque,+Jalisco",
      },
      {
        destino: "Zapopan Centro",
        endereco: "Zapopan Centro, Jalisco, México",
        carN: "20 min",
        carH: "30 min",
        tp: "Macrobús ~25 min / $15 MXN / Uber ~$80–130 MXN",
        dist: "12 km",
        diff: "facil",
        mapsUrl: "https://maps.google.com/?saddr=Av+Guadalupe+596,+Chapalita,+Guadalajara&daddr=Zapopan+Centro,+Jalisco",
      },
    ],
    transitoInfo: [
      "Hotel em Chapalita: sem metrô direto. Usar Macrobús (BRT) na Av. Vallarta ou Uber para conexões centrais.",
      "Uber e Didi: disponíveis e mais baratos que táxi em GDL — opção recomendada no bairro.",
      "⚠️ Aeroporto GDL: Uber/Didi PROIBIDOS na área de desembarque. Usar exclusivamente táxi credenciado do counter oficial dentro do terminal (~$350–500 MXN).",
      "Estadio Akron: sem estação de metrô próxima. Uber ou táxi oficial são as únicas opções viáveis.",
      "Metrô Tren Ligero (Linhas 1 e 2): cobre centro e eixos principais. Tarifa $10,50 MXN (~$0,60 USD).",
    ],
    insights: [
      "Aeroporto GDL: Uber/Didi proibidos no desembarque. Usar táxi credenciado do counter oficial. Fora do terminal (~200m) é possível chamar Uber.",
      "Estadio Akron em dia de jogo: trânsito intenso em Zapopan. Sair 2h antes. Uber é a melhor opção.",
      "Moeda: México usa MXN (Peso Mexicano). ~$17–18 MXN = $1 USD / ~$3,30 MXN = $1 BRL (jun/2026).",
      "Segurança: Chapalita e Zapopan são bairros seguros. Cautela no Centro Histórico à noite.",
      "Fuso: Guadalajara é CDT (UTC -5h). BRT = CDT +2h — 1h atrás de Miami (EDT).",
      "Uber e Didi amplamente disponíveis em GDL — mais baratos e confiáveis que táxi para trajetos no bairro.",
    ],
  },
];
